### ISSUE TITLE
Activar autologin

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#1]
Permitir acceso automático al sistema sin tener que introducir usuario y contraseña

**Comment by jasvazquez** [comment]
Aunque observo que existe la posibilidad de hacerlo desde la interfaz de usuario
![image](https://user-images.githubusercontent.com/604744/101200362-7ad0cb00-3666-11eb-98fc-2f3e85de713c.png)

me está dando tantos problemas (y me parece tan poco lógico su funcionamiento) que he preferido activar el autologin (para _usuario_) lanzando el siguiente código desde la terminal de comandos

```
cat << EOF >> /etc/lightdm/lightdm.conf 

[Seat:*]
pam-service=lightdm
pam-autologin-service=lightdm-autologin
autologin-user=usuario
autologin-user-timeout=0
session-wrapper=/etc/X11/Xsession
greeter-session=lightdm-greeter

EOF
```

@aosucas499 cierro la tarea pero en realidad:
+ ni se ha generado una ISO nueva 
+ ni tenemos (de momento) definido un flujo de trabajo. 

Te reservo la potestad de abrir la tarea (si lo consideras oportuno) y te emplazo a una charla para decidir cómo nos organizamos 😉

**Comment by aosucas499** [comment]
Lo podemos incluir, el debate interno que tengo es que habrá gente que por seguridad en algún centro o que lo quiera instalar en su dispositivo personal, quizás quiera instalar el sistema con login. Desde luego con tu código solo lo habilitaríamos para el típico usuario "usuario" que es poco productivo para la seguridad. Veo factible el incluirlo en el script y que si se instala con usuario, no pida login.

**Comment by jasvazquez** [comment]
Siempre podemos 
+ "documentar" que es el comportamiento por defecto para usuario/usuario (y sugerir/documentar que se cree otro usuario si desea algo de "intimidad")
+ Revisar la opción de menú  que tan extraño comportamiento ofrece actualmente

![image](https://user-images.githubusercontent.com/604744/101243221-fc743780-36fe-11eb-8f2c-d6545bd34aff.png)

**Comment by jasvazquez** [comment]
Otra posibilidad que se me ocurre es [mejorar el script](https://github.com/aosucas499/minino-TDE/blob/11d6005aa8af57729c307094ac92a233c0513841/update-minino.sh) ofreciendo una interfaz gráfica (no sería excesivamente costoso) en la que elegir cómo se desea personalizar Minino.

Se me ocurre [poner un "checkbox"](https://es.wikipedia.org/wiki/Casilla_de_verificaci%C3%B3n) para elegir (o no) el inicio automático sin introducir la clave 🤔

**Comment by aosucas499** [comment]
Buena idea. Por lo pronto he incluido tu código en el script.

**Comment by jasvazquez** [comment]
Andrés, doy por cerrada (nuevamente) esta tarea tras dar de alta la tarea #12 como puedes observar justo encima de este comentario 👍🏻
