### ISSUE TITLE
Incluir tutorial de instalación

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/minino-TDE#10]
Hay gente que no se maneja muy bien con la instalación de sistemas eligiendo particiones, vendría bien un tutorial en PDF con imágenes o incluso en vídeo (by el Padrino) en la que se explique cómo instalar el sistema, creación de particiones, incluyendo al menos una recomendación mínima de partición SWAP.

**Comment by profeIAP** [comment]
Buena idea, el amigo Eloy nos podría venir de perlas con sus habilidades "multimedia" y capacidad de "transmisión" ¿No te parece que estamos tardando en incluirlo en el repositorio oficialmente? 🤔

**Comment by jasvazquez** [comment]
Se me ocurre que podría incluirse en el documento (o wiki) que estamos hablando en la tarea #18, concretamente [a partir de este comentario](https://github.com/aosucas499/minino-TDE/issues/18#issuecomment-739541427)

**Comment by aosucas499** [comment]
Google Docs te encargas tú que eres un artista de los tutoriales escritos y yo lo voy pasando a la wiki. ¿Ok?

**Comment by jasvazquez** [comment]
Este es largo, de ahí que un vídeo (como propusimos inicialmente) sería una opción más acertada ¿No te parece? 🤔

**Comment by aosucas499** [comment]
No sé, mi cabeza solo ve etiquetas y tareas abiertas. Podemos preguntar en el grupo y a ver si así tenemos más opiniones o gente que se pase por aquí. Vamos a tomarnos unos días de descanso. Lo merecemos.

**Comment by aosucas499** [comment]
Esto valdría, ¿no? [wiki - instrucciones de instalación](https://github.com/aosucas499/minino-TDE/wiki/Instalaci%C3%B3n)
