### ISSUE TITLE
Optimizar arranque Firefox

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#11]
Existe la posibilidad de "precargar" (en el arranque del sistema) determinados programas y procesos. La idea (porque no deja de ser eso) sería incluir Firefox (si el rendimiento general y el tiempo de arranque actual no se resiente) en base a que la actividad principal a la que se dedicarán estos equipos es la navegación web para poder abrir las herramientas web que se usan actualmente en la docencia (Moodle, Drive, Meet, ...)

**Comment by aosucas499** [comment]
Creo que eso influiría en el increíble arranque que tiene el sistema. Y no siempre va a ser usado (sí en su mayoría) para usar el navegador.
