### ISSUE TITLE
Permitir personalizar el script de actualización

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#12]
Modificar el [script que actualiza la iso de Minino](https://github.com/aosucas499/minino-TDE/blob/bd59d47548c159f7a2c4f58e0254180b99fc0ebc/update-minino.sh) para permitir elegir al usuario qué modificaciones quiere que sean llevadas a cabo tal y como hemos decidido en la tarea #1 

En un principio, y con los requisitos actuales, se entiende que sería suficiente con el [uso de Zenity para mostrar diálogos](https://andalinux.wordpress.com/2008/08/13/zenity-o-como-interactuar-graficamente-con-el-usuario-desde-un-script/) sencillos en pantalla

**Comment by aosucas499** [comment]
Buena herramienta, no la he usado, estamos en tus manos con esta mejora 😄

**Comment by jasvazquez** [comment]
Sin problemas, intentaré dedicarle un rato esta tarde y montar un prototipo. 
Es sencillo de usar y nos puede dar muchas satisfacciones 💪🏻 
Si más adelante se nos queda "corto" siempre podemos tirar de Python o herramientas similares para montar algo más complejo 👍🏻

**Comment by jasvazquez** [comment]
Bueno, como prueba de concepto no está mal ¿Qué te parece @aosucas499? 😉 

![image](https://user-images.githubusercontent.com/604744/101250559-e4f87700-371d-11eb-8181-0690543d143a.png)

**Comment by jasvazquez** [comment]
Implementado @aosucas499 en el commit 269e418
Si no se entiende algo, avisa y comento más el código 👍🏻

**Comment by aosucas499** [comment]
He estado pensando en esto y no me convence. La idea del update-script yo la veo simplemente como un script para actualizar entre versiones ISOs. La idea de la personalización que has hecho me encanta pero creo que podríamos incluirla mejor como una app paralela y dejar el script-update para actualizaciones necesarios que no necesiten la opinión del usuario.

**Comment by jasvazquez** [comment]
Por no mezclar temas, opto por crear la tarea #16 👍🏻
