### ISSUE TITLE
Modo incógnito por defecto

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#13]
Me planteo si sería interesante (sobre todo si el público objetivo es el alumnado aunque puedan usarlo el profesorado) si sería de interés (evitar que se guarden contraseñas principalmente) activar por defecto dicho modo en el navegador web.

**Comment by aosucas499** [comment]
Es interesante, el curso pasado yo tenía el Firefox para el alumnado siempre en modo "no guardar nada", pero en el grupo parece que no les hacía mucho. Me hicieron referencia a que siempre estaba en modo incógnito. Yo lo prefiero, sería cuestión de preguntar.

**Comment by jasvazquez** [comment]
¿Para qué preguntar cuando tenemos la posibilidad de hacerlo opcional gracias a #12? 😉 
Salvo que me digas lo contrario, voto por añadirlo como opción al menú del script de configuración ¿Te parece)? 🤔

**Comment by aosucas499** [comment]
Genial idea 😄

**Comment by jasvazquez** [comment]
Era la solución más "lógica"
Ha sido una gran idea incluir la opcionalidad en el script 💪🏻 
Cambio las etiquetas a esta tarea tras tomar la decisión 👍🏻

**Comment by aosucas499** [comment]
jajajajaj me vas a matar con tanta etiqueta y nuevos "temas"

**Comment by jasvazquez** [comment]
Sorry Andrés 😅 todavía estoy en fase "de pruebas" hasta encontrar la combinación mínima más eficiente para lo que nos  traemos entre manos... prometo (y espero estar haciéndolo así, avisa si no es el caso) no cambiar "a lo loco... Panchito"

![image](https://user-images.githubusercontent.com/604744/101287610-961c1180-37f1-11eb-991f-1ab406c6e4d2.png)

**Comment by aosucas499** [comment]
No te preocupes, me acostumbraré a tu nivel organizativo/creativo.

**Comment by jasvazquez** [comment]
Implementado en el commit 3d297c7

**Comment by aosucas499** [comment]
Tras probar tu implementación, los navegadores abren en modo privado, pero con tan solo pulsar en abrir nueva ventana vuelve al modo normal, creo que es debido a que en la configuración de la foto sigue dejando la opción de recordar historial, etc...

![minino-firefox64-private](https://user-images.githubusercontent.com/72696244/101294963-de9bf500-381a-11eb-9d81-13482241026b.png)

Yo lo hice en su momento gráficamente dejando algo así o incluso activando el modo permanente.


![minino-firefox64-private-2](https://user-images.githubusercontent.com/72696244/101294983-068b5880-381b-11eb-8acb-db4602c8c662.png)

Habría que buscar cuando haya tiempo la forma de hacerlo así pero con código si es posible.

También he observado que en el código referente al  firefox 83, lo hace con el usuario=usuario, quizás sería mejor usar $USER para que si el que instala con systemback cambia el nombre del usuario siga funcionando:

sudo sed -i -e 's/firefox\/firefox/firefox --private-window/g' /home/usuario/.local/share/applications/firefox-noroot.desktop
por
sudo sed -i -e 's/firefox\/firefox/firefox --private-window/g' /home/$USER/.local/share/applications/firefox-noroot.desktop

**Comment by jasvazquez** [comment]
Buen apunte el de usar `$USER` Andrés, anoto crear nueva tarea para extender el comportamiento a todos los usuarios del sistema 👍🏻 

Se observa que el comportamiento comentado es normal pues debe existir la posibilidad de "salir" del modo incógnito y no vernos "enclaustrados" en el mismo máxime si la finalidad de esta tarea es arrancar por defecto en dicho modo, no impedir el uso del modo de navegación "normal" 😉

**Comment by aosucas499** [comment]
Me parece buena opción entonces  😉

**Comment by aosucas499** [comment]
De todas maneras tengo previsto pasar el firefox 83 al sistema en lugar de que resida en el HOME

**Comment by jasvazquez** [comment]
Lo anoto como tarea pues de tipo IDEA (no es urgente ni necesario pero es algo interesante de tener) 👍🏻
