### ISSUE TITLE
Evaluar consumo principales navegadores web

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#14]
Como ayuda a las distintas pruebas que se están realizando en los equipos de dotación, podría ser interesante conocer el consumo de memoria base que tienen [los distintos navegadores que vamos localizando](/home/jasvazquez/Descargas/sistema/illedelinux-debian-jwm.iso)

![image](https://user-images.githubusercontent.com/604744/101285581-46841880-37e6-11eb-9d0a-63ffdf0de7e0.png)

Para realizar dichas pruebas podríamos hacer uso d[el script que utilicé en su día](https://andalinux.wordpress.com/2010/06/22/firefox-vs-chrome-consumo-de-memoria/) para comparar Firefox con Chrome.

La idea que subyace es poder ordenar los distintos navegadores (tanto en consumo como en funcionalidad) a la hora de elegir el que mejor podría sernos de utilidad

**Comment by jasvazquez** [comment]
@aosucas499 cuando tengas un rato, échale una pensadita y me dices si esta tarea merece la pena o no tenerla en cuenta.

¿Crees interesante catalogar los diferentes navegadores en función del consumo de recursos que tengan y su funcionalidad (sirven para Meet, abren Moodle, se trabaja de un modo fluido en Google Docs, ...)?

**Comment by aosucas499** [comment]
Todo estudio es digno de tener en cuenta y más teniendo ya tu script para analizarlos. Por los comentarios de la gente los navegadores que tenemos van bastante bien, cada uno para lo suyo, pero es cierto que se necesita un cierto feedback o análisis de funcionalidades.

**Comment by jasvazquez** [comment]
¿Sería interesante abrir dicha posibilidad al profesorado (si es que alguien se anima a colaborar, con la hoja de cálculos que publicamos, al final creo que soy el único que escribe cosas 🤣 ) con un Google Forms (o similar), lo dejamos para ir haciéndolo poco a poco como tareas independientes o simplemente nos olvidamos del tema?

Se me ocurre la posibilidad de ofrecer una opción en el menú de Minino-TDE (fácilmente implementable con Zenity 💪) y permitir instalar para probar los distintos navegadores que estamos indicando... desde esa misma opción se podría abrir el Google Forms para que el compañer@ nos deje su impresión de la prueba realizada 🤔

**Comment by aosucas499** [comment]
No me hace la idea de incluir más navegadores para que vayan probando. Funciona bien y está testado con alumnado que usa google gsuite y moodle. Su rendimiento es bueno incluso en dispositivos con 1gb de RAM. Otra cosa si quieres es hacer una rama testing para los que quieren probar cosas nuevas.
