### ISSUE TITLE
Elegir kernel en función del ordenador

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#15]
Tras conversación con @aosucas499 sobre el fantástico rendimiento de Minino en los portátiles de dotación y achacando dicho comportamiento al uso de una versión anterior del kernel, me planteo la posibilidad de (automáticamente y en función del equipo en el que se vaya a utilizar el sistema) hacer un downgrade/upgrade según convenga para aprovechar mejor el equipo.

De este modo, sacaríamos más partido a equipos antiguos pero si alguien se anima a instalarlo en un equipo más moderno no se vería mermado en su rendimiento y funcionalidad.

**Comment by aosucas499** [comment]
No lo veo si lo que piensas es en incluir una modificación de kernel en el update script. Si lo que te planteas es usar un kernel más actual para equipos más modernos creo que es mejor usar otra distribución para esos menesteres, partir de 0 como me contaste con otras opciones y dejar este minino tal cual.

**Comment by jasvazquez** [comment]
En realidad es 
+ pensando en esa posible nueva versión (basada en Arch, en [illedelinux-debian](https://sourceforge.net/projects/illedelinux/files/) o la que se tercie que se porte relativamente bien y nos guste)
+ o incluso si descubrimos que un kernel se porta algo mejor en unos equipos de dotación que en otros (por falta de drivers o por incompatibilidades)

La idea es intentar ajustar lo máximo posible el sistema a cada equipo para intentar exprimirlos lo máximo posible 😅

**Comment by aosucas499** [comment]
Ah genial entonces. Ya me habías asustado y [te iba a mandar esto](https://andalinux.wordpress.com/2014/02/04/proyectos-minimalistas-o-menos-es-mas/)

**Comment by jasvazquez** [comment]
Descuida, el _memento mori_ siempre lo tengo presente. 
Todavía no se me ha ido la pinza del todo 🤣 

![image](https://user-images.githubusercontent.com/604744/101287153-c8783f80-37ee-11eb-8ad2-cf48c2dc1fbb.png)
