### ISSUE TITLE
Aplicar downgrade al kernel en Debian

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#17]
Es curioso observar lo bien que se comporta Minino y que otras distribuciones basadas igualmente en Debian (9 o incluso 10) con kernels más actuales y un consumo igual o menor, el rendimiento no se acerque ni de lejos.

A modo de experimento y para confirmar\refutar la teoría de tratarse de la versión del kernel usada por Minino 

![image](https://user-images.githubusercontent.com/604744/101287772-a7b1e900-37f2-11eb-997f-00064454ff9c.png)

sería interesante comprobar si podemos hacer un downgrade del kernel a una de estas distribuciones candidatas a convertirse en una alternativa más actual del sistema

**Comment by aosucas499** [comment]
Mi teoría del kernel es solo una teoría, teoría por eliminación, también podemos preguntarles a los creadores.

**Comment by jasvazquez** [comment]
Sería una buena opción ¿Te parece que creemos tarea y les preguntemos? 😉 
¿Para qué pegar cabezazos cuando igual no les importa darnos algo de luz al respecto, no te parece?

**Comment by aosucas499** [comment]
Genial.

**Comment by jasvazquez** [comment]
Sé que [andas agobiado con tanta tarea](https://github.com/aosucas499/minino-TDE/issues/18#issuecomment-739558758), pero voy a optar por abrir la tarea nuevamente (observa que es una IDEA que no hay por qué implementar, sólo queda anotada por si nos "aburrimos" o encontramos una forma sencilla de llevarla a cabo, para que no se olvide 😉 )

**Comment by aosucas499** [comment]
¿Aburrirnos? En 5 días esto en vez de un minino es un perrito.

**Comment by aosucas499** [comment]
En este proyecto no he pensado en cambiar a ninguna otra distribución candidata, va bien como está.
