### ISSUE TITLE
Ofrecer la posibilidad de instalar Gimp opcionalmente

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#18]
Puesto a permitir personalizar el sistema quizás sea más adecuado enseñar a instalar cualquier programa en Debian (tenemos centro de software dentro de Minino) que dar la opción de seleccionarlo.

Si diese problemas (como ocurre con OnBoard) lo entendería pero no tiene sentido que conforme crezcan las solicitudes de programas, optemos por incluir todos y cada uno de ellos aquí 🤔

**Comment by aosucas499** [comment]
Totalmente de acuerdo, como hablamos aquí #3, no veo necesario incluir Gimp con lo fácil que es instalarlo. Me parece una idea genial no incluir programas o la opción en el zenity cuando sea fácil hacerlo desde el centro de software con los repos de debian jessie o como dijiste una vez esto va a ser un (no recuerdo tu expresión) "poyaqueestamos añade..."

**Comment by jasvazquez** [comment]
Genial, duda resuelta a falta de matizar un punto ¿hace falta documentar cómo se instala software o confiamos que el profesorado lo buscará en Internet?

Igualmente se me ocurre usar la wiki o, incluso quizás mejor, crear un documento en Google Docs (la gente se maneja mejor con ellos) tipo "Usando Minino-TDE" 🤔

**Comment by aosucas499** [comment]
Me gusta la idea de la wiki. También se puede crear en google docs y poner el enlace en la wiki, lo que veas mejor.

**Comment by jasvazquez** [comment]
No soy partidario de tener que estar actualizando dos documentos distintos: si podemos evitarnos algún esfuerzo más allá del que ya estamos haciendo, mejor que mejor (tiempo que podemos dedicar a cosas más productivas 😉 )

La elección la veo de este modo:

1. Compartir el enlace de la wiki y así la gente visita este rincón de Github (igual conseguimos "apoyos")
1. Usar Google Docs que la gente maneja mejor y donde también podemos hacer referencias a este rincón

Creo que el Google Docs (sobre todo conforme aumente el tamaño de los textos) puede ser más cómodo de editar y la estética (con una buena plantilla) nos ofrecería una buena carta de presentación (que las cosas tienen que funcionar bien pero también entrar por los ojos ¿no te parece? 😅 )

**Comment by aosucas499** [comment]
Esto lo cerramos ya, ¿no? Me está agobiando un poquito tantos temas abiertos jajaja

**Comment by jasvazquez** [comment]
No te agobies: las DUDAS e IDEAS no cuentan
En el flujo de trabajo actual que estamos definiendo (sobre la marcha) son los TODO y FIX los que marcan el "tajo pendiente" 😉

**Comment by jasvazquez** [comment]
Sin embargo no hemos tomado una decisión: ¿wiki o docs? 😏

**Comment by aosucas499** [comment]
Me parece buena la idea de WIKI porque está en el mismo lugar que el proyecto. Haz tú el docs y yo lo voy pasando a la wiki.

**Comment by aosucas499** [comment]
Pero esta tarea era sobre GIMP. Seguimos en la que has puesto sobre tutorial de instalación y ahí hablamos.
