### ISSUE TITLE
Preguntar por optimizaciones de Minino

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#19]
Tras estar [hablando sobre el curioso rendimiento que presenta Minino](https://github.com/aosucas499/minino-TDE/issues/17#issuecomment-739537507) y nuestras dudas de si el motivo real (o no) es la versión 3.16 del kernel en la tarea #17, se nos ocurre preguntar a los autores de Minino por si pueden darnos algo de luz al respecto y encontramos una forma de extrapolar dicha mejora a alguna versión más actualizada de Debian que nos permita acceder a versiones del software más recientes

**Comment by jasvazquez** [comment]
Andrés, te la asigno a ti por ser el "interlocutor oficial" con los compañeros de Minino 😅

**Comment by aosucas499** [comment]
Perfect!

**Comment by aosucas499** [comment]
Me llama la atención lo que comentan en su web sobre Wayland o systemd y el abandono del proyecto. Les escribiré para preguntar lo que comentaste en tu primer comentario. También recordar que yo le apagué muchos servicios activos a la distro, se pueden ver desconectados en la aplicación del menú minino o utilidades llamada servicios.

**Comment by jasvazquez** [comment]
Ya somos dos a los que nos ha llamado la atención dicha frase 🤔

**Comment by aosucas499** [comment]
Yo les escribí ayer, en cuanto contesten te cuento aquí.

**Comment by aosucas499** [comment]
Respuesta del email:

Hola, Andrés, perdona la tardanza.
Te comento algunas notas que quizás te puedan servir:
Lo más importante son los demonios del inicio, lo hemos dejado pelaísimo, sólo lo necesario para arrancar el entorno y la sesión gráfica. La sesión gráfica también suele tener por defecto servicios o programas que no nos interesan, así que también los quitamos.
Decidimos exactamente qué es lo que queremos cargar, que en definitiva es: la sesión X, encima de ella, un administrador de ventanas y encima de él, un panel de trabajo. LXDE nos permite decidir qué cargar en los archivos de configuración .config/lxsession y .config/lxpanel

El wifi también es un applet que consume, así que lo pusimos como un switch para que fuera opcional encenderlo o no según necesiadades.

En cuanto el kernel, según nuestras pruebas, un kernel de 32 bit va más rápido y consume bastante menos que uno de 64 bit. Además esto es así sorprendentemente en cualquier máquina (sea nueva o vieja), además, la opción de 64 bit también ocupa más espacio en disco.

También hacemos ajustes en el disco duro (ej. no escribir la marca de tiempo) y también usamos [prelink](https://ubunlog.com/prelink-mejorar-velocidad-carga-aplicaciones/) en todo el sistema para acelerar la carga de programas.

Así a bote pronto, son las cuatro cosillas que fundamentalmente hemos hecho para acelerar todo.

Un saludo.

**Comment by jasvazquez** [comment]
Francamente interesante las cuatro "pinceladas" que te han dado.

Me planteo estudiar seriamente la pila de "servicios" definidas para montar el entorno gráfico del sistema 🤔

**Comment by jasvazquez** [comment]
Andrés, ¿sería abusar preguntar a los compañeros qué optimización creen que puede influir en el rendimiento que el navegador web (funciona igual de bien en Chromium que en Firefox) a la hora de usar Google Docs?

Parece broma, pero me maravilla que Minino no tiene los lags que presenta cualquier otra distribución por muy optimizada que esté 🤔

**Comment by aosucas499** [comment]
Buenísima idea, yo lo veo bien. Hay gente con ganas de colaborar. La verdad es que a mí en su día también me dejó perplejo. Y más cuando veía que le quitaba algún servicio y actualizaba navegadores viendo cómo funcionaban.

 Hoy por ejemplo, entré en clase de un compañero y tenía examen con sus estudiantes. Tenía un chuck norris que le dejé hace un año, le pregunto y me dice que lo tenía en el cajón porque a veces se bloqueaba con lo que le puse (versión Guadalinex unofficial de unos compañeros, openbox+repositorios y kernel nuevo). Le dije dejamelo que mientras hacen el examen te voy a dar una cosa a probar. Al salir a las 2, me busca y me dice, "tío, que le has hecho al pc ese tan viejo, he estado navegando como en el nuevo de la clase". Le dije "has visto a ese lindo gatito" jajjaa

**Comment by jasvazquez** [comment]
Si es que el gatito "ronea" cosa mala 🤣👍🏻

**Comment by jasvazquez** [comment]
¿Tú [has visto esto]( https://minino.galpon.org/es/comment/2837#comment-2837) en los foros de Minino? 😳

**Comment by aosucas499** [comment]
Lo vi, pero parece que al final...cerraron

**Comment by jasvazquez** [comment]
Pero sería interesante conocer dónde se quedaron y (sobre todo) qué dejaron hecho. 
No digo que podamos nosotros sortear el escollo que encontraron pero sí que nos daría mucha información para conocer por qué Minino ha llegado a ser lo que es y por donde tirar a la hora de optimizar un sistema operativo para equipos de bajos recursos ¿No te parece? 🤔
