### ISSUE TITLE
Instalar teclado en pantalla

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#2]
Actualmente da problemas pero sería interesante poder contar con este teclado en pantalla especialmente por la existencia de equipos a los que no les funcionan ciertas teclas.

**Comment by jasvazquez** [comment]
No sabiendo si el objetivo realmente es contar expresamente con OnBoard o con un teclado en pantalla me planteo la siguiente posibilidad... ¿Cómo lo ves @aosucas499?

![Peek 08-12-2020 19-26](https://user-images.githubusercontent.com/604744/101525375-820c1780-398b-11eb-8f73-71189bc5f954.gif)

**Comment by aosucas499** [comment]
El objetivo era incluir teclado en pantalla para algunos que comentaron que tenían teclas rotas en algunos dispositivos. Ese florence es más bonito que el marchbox!!! Y por lo que veo no da problemas. Por mí inclúyelo en el update-minino y cerramos la tarea de onboard! Enhorabuena!!
