### ISSUE TITLE
Cambiar el tema por defecto del sistema

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#21]
El tema actual es excesivamente antiguo y un cambio de imagen podría "rejuvenecerlo".

Es sólo una IDEA porque ni es necesario ni corre prisa pero estaría bien un cambio de imagen: supone poco coste y hay soluciones muy elegantes por ahí

![image](https://user-images.githubusercontent.com/604744/101290292-83a9d400-3801-11eb-8e99-959ed2117b16.png)

![image](https://user-images.githubusercontent.com/604744/101290247-3d547500-3801-11eb-80cb-1faf2b084d6f.png)

![image](https://user-images.githubusercontent.com/604744/101290329-ca97c980-3801-11eb-9b62-c7fb34b7d09c.png)

**Comment by aosucas499** [comment]
No me hace cambiar nada que pueda influir en el rendimiento o apariencia. Me gusta cómo es. Son buenas ideas si  hacemos otra distro como las ideas que tuviste con arch pero me gustaría dejar este proyecto tal cual, con los arreglos de algunos fix para usar en los centros y dejarla estable tal cual está.

**Comment by jasvazquez** [comment]
¿Algo así como mantener la "imagen corporativa" de Minino-TDE? 😏 ¿Un tributo a los compañeros que lo han desarrollado originalmente y cedido a la Comunidad?

Lo respeto Andrés pero el cambio del tema no influiría en el rendimiento general (espero)

Personalmente me gustaría estirar Minimo "classic" todo lo posible (nos da margen para mejorar y definir su evolución) pero sin perder de vista la posibilidad de actualizarlo (manteniendo su rendimiento actual) por seguridad y funcionalidad.

Considero que el objetivo principal (la razón de ser de Minino-TDE y la finalidad que no me gustaría perder de vista) debería ser seguir ofreciendo la posibilidad de aprovechar los equipos antiguos de dotación independientemente del medio usado para ello (Minino, Arch, Debian 10+lxde, Slax, ...) de ahí que empezar a definir una "estética propia" que ayude a distinguir Minino-TDE al resto de docentes (independientemente de la distro que usemos como "motor" que lo sustente) sería un factor interesante a tener en cuenta 🤔

**Comment by aosucas499** [comment]
No te lo niego, pero los temas influyen en el rendimiento, y esa puede ser uno de las claves de minino. Pensar en cambiarle a esta distro el entorno de escritorio, o la base debian...no lo veo.

**Comment by jasvazquez** [comment]
No creo que sea la clave de su rendimiento el tema usado ni que influya tanto como temes. 

Yo no soy amante de la estética (aunque la aprecie) y dejo las distros que me instalo como salen de la caja pero esta agradecería cualquier retoque por pequeño que fuese 😅😇

**Comment by jasvazquez** [comment]
Igual se puede plantear crear tarea a medio plazo (IDEA) el probar si cambia el tiempo de arranque o la usabilidad del sistema en general 🤔
