### ISSUE TITLE
Objetivo del proyecto

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#22]
Tras la conversación mantenida (entre otras) en la tarea #17 considero Interesante fijar los objetivos y expectativas de Minino-TDE y su posible evolución a Perrete-TDE 🤣

Sigo pensando que no deberíamos perder de vista el que considero debería ser uno de los objetivos básicos de este trabajo (por entender que es su finalidad): aprovechar los equipos de dotación antiguos que todavía se usan en muchos centros andaluces y a los que Guadalinex no da respuesta.

¿Nos centramos únicamente en mantener lo que hay y dar un servicio más que decente mientras sea posible o lo hacemos sin perder de vista la necesidad de encontrar una forma viable de seguir ofreciendo dicha posibilidad?

**Comment by aosucas499** [comment]
Me gusta la idea de mantener este sistema que va genial, reparando posibles incompatibilidades con algún dispositivo de los centros, (como el que no he tenido tiempo de mirar sobre el sonido en Samsung) y añadir alguna necesidad que surja en los compañeros. Es decir, este sistema tal cual con pequeñas reparaciones. Yo veo mejor que la idea de ofrecer algo con más futuro lo creemos a partir de otro proyecto. Yo me apunto porque me encantan tus ideas, pero mi gatito me gusta así, así ha sido bien recibido y así me gusta.

**Comment by jasvazquez** [comment]
¿Aún siendo conscientes que tendrá una vida relativamente corta?

Yo apostaría por incluir los cambios que vayan surgiendo pero de modo que estas modificaciones (tal y como estamos haciendo hasta ahora) puedan ser portadas a Perrete-TDE (verás que al final se le queda el mote 🤣) 

Si lo hacemos bien (y de ahí que me resulte interesante #21 por dar cierta continuidad al proyecto) podamos dar el salto (cambiando el motor a uno más actual y con soporte para las nuevas versiones del software) sin que se note por nuestros compañer@s 🤔

**Comment by jasvazquez** [comment]
Tras comentar/debatir sobre el alcance del proyecto creo que podríamos dar por cerrada esta tarea.
@aosucas499, siéntete libre de abrirla nuevamente si consideras que no es así 👍🏻
