### ISSUE TITLE
Extender modo incógnito a cualquier usuario del sistema

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#27]
Sugiere @aosucas499 la posibilidad de activar el modo incógnito a cualquier usuario del sistema y no solo a _usuario/usuario_ en la tarea #13.

Al crear esta tarea me surge la duda (y así lo etiqueto): ¿tiene sentido activarlo para todos en lugar de únicamente para _usuario/usuario_?

Con un usuario "público" como es _usuario/usuario_ tiene sentido proteger que no se guarden "por despiste" (o equivocación) contraseñas, se dejen abiertas sesiones en distintos servicios web o que queden registradas las páginas visitadas recientemente pero, si alguien ha creado su propio usuario en el ordenador, y sólo él conoce la contraseña para utilizar dicho usuario... ¿qué sentido tiene proteger (más aún) su privacidad? (sólo él puede entrar) 🤔

**Comment by aosucas499** [comment]
Pues es una duda razonable. Quizás se podría activar la sesión privada en los navegadores solo para el usuario público.

**Comment by jasvazquez** [comment]
Pues lo damos por resuelto tal y como está ahora: sólo _usuario/usuario_ (que es el usuario "público") cuenta con la posibilidad de  iniciar sesión por defecto en los navegadores en modo incógnito 👍🏻
