### ISSUE TITLE
Pasar Firefox 83 a la raíz del sistema

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#28]
Tras sugerencia de @aosucas499 consideramos interesante [quitar Firefox del directorio `$HOME` de _usuario/usuario_](https://github.com/aosucas499/minino-TDE/issues/13#issuecomment-740569978) sobre todo teniendo en cuenta que podemos contar con varios usuarios en el sistema y no tiene sentido limitarlo al usuario "público"

**Comment by jasvazquez** [comment]
Como te has asignado la tarea entiendo que la estás implementado, por lo que cambio la etiqueta a TODO (ha dejado de ser una IDEA a ser una REALIDAD 😉 )
Si lo he malinterpretado, ten a bien deshacer el cambio de etiquetas 👍🏻

**Comment by aosucas499** [comment]
Sí, tengo el script original que era para usar con Guadalinex para actualizar firefox sin root, ya que no es necesario en minino, lo voy simplemente a actualizar con las carpetas del sistema. Bien interpretado😉

**Comment by aosucas499** [comment]
Se me pasó escribir que lo añadí al script, ya está para el sistema y he añadido colores al script cuando se instala algo.
[commit](https://github.com/aosucas499/minino-TDE/commit/92c1728b9cce0f22311ac19d4e488f8b110c856d)

**Comment by jasvazquez** [comment]
No esperaba menos de ti, ya me tenías hasta extrañado 🤣 
Genial lo de los colores... tenía pendiente hacerlo 😉 
Siento haber bajado el ritmo estos días (evaluaciones "mandan"), ya me desquitaré 👍🏻

**Comment by aosucas499** [comment]
jajajajajajajajaj Yo igual no te preocupes, con las evaluaciones.
