### ISSUE TITLE
Modificar activación modo incógnito en navegadores

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#29]
Tras implementarse #28, Firefox 83 no estará en `$HOME` como espera por lo que debe cambiarse su comportamiento para que apunte a la ruta correcta.

**Comment by jasvazquez** [comment]
No entiendo la DUDA, compi
Igualmente sigo empecinado en etiquetar como FUNCIONALIDAD (es un comportamiento, no un programa) la tarea 😉

**Comment by aosucas499** [comment]
Me tienes que perdonar compi, creo que la he cambiado sin querer, buscaba otra tarea para cambiar. Sorry!

**Comment by jasvazquez** [comment]
No faltaba más... disculpado queda D. Andrés 👍🏻
