### ISSUE TITLE
Instalar Gimp

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#3]
Suele ser una herramienta muy usada y de las primeras que suelen instalarse. 

El principal problema es el rendimiento que pudiese llegar a tener por lo que es posible que requiera cierta optimización.

**Comment by aosucas499** [comment]
**Sin Gimp, consumo de RAM:**

![minini-no-gimp-ram](https://user-images.githubusercontent.com/72696244/101209133-90002680-3673-11eb-960f-8a751294c7e1.png)

**Con Gimp instalado,  consumo de RAM:**

![minino-gimp-ram](https://user-images.githubusercontent.com/72696244/101209218-b0c87c00-3673-11eb-98c4-bbe1b101f512.png)

**No parece que esta versión de GIMP consuma recursos excesivos si la comparamos con otras aplicaciones como Firefox.**

![minino-firefox64-ram](https://user-images.githubusercontent.com/72696244/101209444-0866e780-3674-11eb-9ef6-a3a5c1483b58.png)

**Comment by aosucas499** [comment]
Si lo ves bien añado el comando al script. Esperando feedback...

**Comment by jasvazquez** [comment]
Veo que lo has añadido al script (aunque comentado)

Por mí está bien pues es uno de los programas que (sí o sí) necesito tener instalado en cualquier equipo que uso 👍🏻

**Comment by aosucas499** [comment]
Añadido pues. Que no te falte de "na". Pero no debemos perder la perspectiva del proyecto,  su uso en sistemas antiguos con pocos recursos, que puedan ser prestados al alumnado y puedan usar las herramientas mínimas necesarias que se le van a pedir desde el centro: moodle, gsuite...

**Comment by profeIAP** [comment]
Claro Andrés pero, si no se usa, no "consume".
De momento y por muy modesto que sea el disco duro tenemos espacio suficiente para incluirlo.
El objetivo sigue claro: un sistema operativo decente en equipos de pocos recursos y antiguos para poder usar herramientas webs de hoy en día 😉

**Comment by jasvazquez** [comment]
Claro Andrés pero, si no se usa, no "consume".
De momento y por muy modesto que sea el disco duro tenemos espacio suficiente para incluirlo.
El objetivo sigue claro: un sistema operativo decente en equipos de pocos recursos y antiguos para poder usar herramientas webs de hoy en día 😉
