### ISSUE TITLE
Limitar personalización de Minino

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#31]
Tras la implementación de las tareas #12 y #26 se presenta la posibilidad de que el profesorado pueda usar varias veces el script de personalización lo cual, en algunas de las opciones ofrecidas (como es el caso de #1) provocará fallos inevitablemente (cada vez que se active la opción de _autologin_ se volverá a introducir (innecesariamente) una nueva entrada en `/etc/lightdm/lightdm.conf`

La duda está entre permitir personalizar el sistema
1. **una** sola **vez** (eliminando los iconos y el propio script del sistema para que no pueda volver a usarlo)
1. **varias veces** (debiendo implementar el "hacer" y "deshacer" de cada opción de configuración que incluyamos o bien implementando un mecanismo que gestione el "estado de partida" de modo que podamos restaurarlo cada vez que intenten personalizar el sistema)

**Comment by aosucas499** [comment]
Si es solo la tarea #1 ¿ qué te parece crear ya que tenenos la carpeta customize, tener un lightdm.conf para cuando hay autologin y otro para login normal? Al seleccionarlo en el script se copiaría sustituyendo y no habría problemas de repetición. También lo he pensado porque observé que cuando instalas con otro usuario distinto de usuario, la pantalla de login muestra usuario para seleccionar aunque no exista, cosa que seguro podemos solucionar en el lightdm.conf con alguna opción que hay para que no muestre el usuario a elegir y haya que escribirlo.

**Comment by jasvazquez** [comment]
Es una opción que he estado barajando pero presupone que el `lightdm.conf` sólo lo cambiamos nosotros desde el script: si alguien lo edita (vete a saber para qué) se lo estaríamos "machacando" cada vez con la versión "original"

Otra posibilidad sería anotar un "hash" y si no coincide con el esperado, eliminar la opción del menú de personalización (no creo que podamos deshabilitarla)

**Comment by aosucas499** [comment]
[Lightdm.conf](https://wiki.archlinux.org/index.php/LightDM_(Espa%C3%B1ol))

¿Qué podrían querer cambiar? La aplicación que había en minino no cambiaba nada o la podríamos borrar no? En todo caso lo que veas mejor, si ves alguna manera la implantamos.

**Comment by jasvazquez** [comment]
Ten en cuenta que no todo es cambiar ficheros completos: actualmente tenemos como opción la instalación de software como el acceso por _ssh_ (tarea #23)

Igual la solución planteada en #32 de usar Timeshift podría ser una alternativa global (tanto para la actualización de Minino-TDE como para la personalización realizada por el usuario)

Si me apuras y queremos dejarlo todo como "lo tenía el usuario" siempre podemos anotar (IDEA peleona) las últimas opciones que eligió y mostrarle (o aplicarlas directamente, aunque esto serviría de poco si hemos añadido nuevas opciones en la siguiente versión del sistema) el menú de configuración ya precargado con sus "preferencias" 🤔

**Comment by jasvazquez** [comment]
Cambio la etiqueta a TODO tras priorizar su realización debido a las dudas que me plantea sacar una nueva ISO de Minino-TDE en la que los usuarios puedan activar y desactivar opciones sin obtener el resultado esperado

**Comment by aosucas499** [comment]
Ok, esperamos que esté cerrada para generar la ISO. Estoy experimentando con varios instaladores a parte de systemback y refracta.

**Comment by jasvazquez** [comment]
La cierro tras el último commit asociado a esta funcionalidad 9f3ef09

**Comment by aosucas499** [comment]
Menudo curro, va genial. ¡Enhorabuena!

**Comment by jasvazquez** [comment]
Me alegra que te guste, Andrés. Algo de trabajo sí ha tenido pero creo que era la solución que merecía el tema 😉

Gracias por probarlo: aunque lo sometí a una batería de tests exhaustiva siempre queda el temor a haber pasado algo por alto 😅

**Comment by aosucas499** [comment]
Gracias a ti. Hay líneas que ni entiendo, estudiaré ese código para aprender😉

**Comment by jasvazquez** [comment]
Genial. Cualquier duda que te surja, pregunta: así queda constancia y podría ayudar a otros 👍🏻
