### ISSUE TITLE
Software Teams para Linux

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#33]
Manolo García pregunta hoy en Telegram si sería posible contar con este programa en Minino-TDE.
Parece complicado pero no estaría de mas echarle un vistazo

**Comment by aosucas499** [comment]
Lo veo casi imposible, contando que solo tienen debs para 64 bits. 
[Link](https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/download-app#desktopAppDownloadregion)

**Comment by jasvazquez** [comment]
No, si complicado (de serie) ya parece.

Habrá que evaluar si realmente merece la pena el esfuerzo en base a los usuarios que pueda llegar a tener realmente 🤔

**Comment by aosucas499** [comment]
Si fuese para Gsuite...pero encima de que como dices Teams va a tener poca acogida, Microsoft me da.... pereza (perrete que soy jajaj)

**Comment by jasvazquez** [comment]
A mí no me mire, que solo de pensarlo me da urticaria ¿¡¿Darle gratuitamente soporte a Microsoft?!? 😳🙈

Aquí los [repositorios](https://docs.microsoft.com/es-es/microsoftteams/get-clients) por si nos animamos a hacer pruebas

**Comment by aosucas499** [comment]
Cierro tras observar que solo hay paquetes para sistemas de 32 bits.

[https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/]()
