### ISSUE TITLE
Problemas con firmware-b43-installer

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#34]
Laura López comenta en telegram TDE que no consigue hacer funcionar la wifi en unos portátiles HP que tiene

![IMG_20201212_001616_303](https://user-images.githubusercontent.com/604744/101963549-45e8e900-3c0f-11eb-80be-8446bbacb48a.jpg)

@aosucas499 propone la siguiente [solución](https://lignux.com/solucion-al-driver-broadcom-bcm4311-para-wireless-en-ubuntu-linux-mint-y-derivadas/)

**Comment by aosucas499** [comment]
La solución fue una rápida búsqueda en google jajaja, pero sí, la política debian es no incluir los drivers "non-free". Así que lo podremos solucionar rápido incluyendolos en el kernel o añadiendo los repos non-free de debian jessie al sources.list

**Comment by jasvazquez** [comment]
Posible, aunque me llama la atención el mensaje de no poder acceder al repositorio.

Necesito verlo en el ordenador. En el móvil poco más puedo hacer y menos a las horas que son

![IMG_20201212_002635_112](https://user-images.githubusercontent.com/604744/101964186-d7a52600-3c10-11eb-8a52-50701e7b8144.jpg)

**Comment by jasvazquez** [comment]
Cerrada la tarea tras comprobar que el problema se debía a que Laura no tenía conexión a internet en el equipo y que el paquete se puede instalar sin problemas de los repositorios

**Comment by aosucas499** [comment]
😆

**Comment by aosucas499** [comment]
¿Ves necesario añadirlo al customize como opción o al update minino para que tenga más drivers incluidos?

**Comment by jasvazquez** [comment]
Corrígeme si me equivoco Andrés (no lo he comprobado 😅) pero ¿No viene de serie el paquete en Jessie? Pregunto porque no entiendo la necesidad de añadirlo a _customize_

**Comment by aosucas499** [comment]
No lo he probado. Pensé que es de esos que viene en el apartado "non free" de debian y que por lo tanto no lo teníamos. Lo miro porque de memoria ando ya..m

**Comment by jasvazquez** [comment]
Definitivamente, nos podemos olvidar... viene de serie y sin activar ningún repositorio 👍🏻 

![image](https://user-images.githubusercontent.com/604744/102587868-dc844100-410c-11eb-85b2-253ded7c735b.png)

**Comment by aosucas499** [comment]
Genial!!!
