### ISSUE TITLE
Cachear DNS localmente

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#35]
Pensando en un uso de los portátiles centrado en los servicios online (quizás porque lo primero que hago al arrancar sea abrir el correo electrónico en el navegador web y uso en exceso los servicios de Google) y, tras ver que en la mayoría de las veces (durante excesivo tiempo) aparece en la barra de estado del navegador mensajes del tipo "Esperando a lawebquesea.com...", se me ocurre como posible optimización el cachear la resolución de las direcciones web que más use el usuario.

**Comment by aosucas499** [comment]
Genial. ¿Cómo se hace eso?

**Comment by jasvazquez** [comment]
Existen diferentes alternativas ([p.e. ésta](https://geekflare.com/es/linux-server-local-dns-caching/)) pero habría que hacer algunas pruebas y ver si realmente mejora el rendimiento en los equipos que nos traemos entre manos.

__OFF-TOPIC__ no termino de entender las nuevas etiquetas compi 😏 
+ la de DUDA podría pero no creo que fuese necesaria (bastaba con preguntar directamente en los comentarios como has hecho 👍🏻 
+ la de SOFTWARE la veo más como una funcionalidad del sistema (y así la etiqueté) que afectará a todos los programas que hagan uso de la red 😉

**Comment by aosucas499** [comment]
Aquí igual, no quería cambiar la etiqueta a nada. Creo que jugaba con ponérsela a la que creé hoy y me he equivocado dos veces. Sorry.

**Comment by jasvazquez** [comment]
Misterio resuelto. No te disculpes por ello Andrés: estamos aprendiendo 👍🏻

**Comment by jasvazquez** [comment]
Como anotación personal dejo indicado que necesité crear el siguiente enlace simbólico al probar _Garuda_ en uno de mis ordenadores

`sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf`
