### ISSUE TITLE
Mostrar asteriscos al introducir claves en la terminal

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#36]
Mi alumnado suele confundirse mucho cuando escriben contraseñas en la línea de comandos y muchos de nuestros compañer@s deben, sentirse igual. 

Es un [cambio sencillo](https://www.omgubuntu.co.uk/2016/08/make-sudo-password-visible-terminal) y requiere poco trabajo por lo que sería interesante incluirlo de serie.

Se puede modificar directamente `/etc/sudoers` y así resulta más sencillo incluirlo en el script que actualiza Minino.

Aunque en el artículo se habla de añadirlo separando mediante comas los valores, se puede añadir sin problemas en una línea nueva como un 

``Defaults pwfeedback``

**Comment by aosucas499** [comment]
Perfecta idea.

**Comment by aosucas499** [comment]
He intentado añadirla desde terminal con "echo >>", con "sed -i $a". Todo me da fallo de permiso denegado. Con visudo habría que hacerlo interactivamente, voy a probar en copiar un archivo con esa línea en /etc/sudoers.d/

**Comment by aosucas499** [comment]
Acabo de ver que te la has asignado, te la dejo pues.

**Comment by jasvazquez** [comment]
Sí, ya me estaba "aburriendo" ver una TODO sin quitar de en medio 😉 

![image](https://user-images.githubusercontent.com/604744/102813408-0bc6d680-43c9-11eb-8246-8e89f6248e14.png)

**Comment by aosucas499** [comment]
La cosa pide ISO ¿no?
