### ISSUE TITLE
Refracta o systemback

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/minino-TDE#37]
Dado que le instalé en su día a minino systemback para personalizar mejor mis instalaciones en los equipos del centro y era algo personal me planteo la duda de si no sería mejor usar refracta que ya viene incluida de fábrica en el sistema para generar la ISO y las instalaciones, ya que parece que a muchos les resulta complejo systemback en el tema de particiones. 

[Minino crear iso](https://minino.galpon.org/es/faq#faqs-block_faq-3)

**Comment by jasvazquez** [comment]
Sí que está dando problemas a los compañeros pero entiendo que es (a mí también me costó un par de pruebas) por lo poco intuitivo que resulta el tener que pulsar en la flecha para asignar a la partición que se tiene seleccionada en el listado de la izquierda 🤷🏻‍♂️ 

Puede que el manual de #10 ayude a resolver esa duda (aunque no todos leen y otros ni lo van a buscar siquiera)

Si Refracta ayuda a simplificar el proceso y permite cierto grado de personalización (como poder elegir el tamaño de la partición de _swap_) por mí encantado aunque me surge la duda de si al final la elección de particiones es cosa de la propia Minino e, independientemente de cómo la "empaquetemos", volverá a aparecer tan nefasto menú nuevamente (no recuerdo, la única vez que he instalado la Minino pura, si salía el menú o si es cosa de Systemback)

**Comment by aosucas499** [comment]
Si el menú nefasto al que te refieres es el de la flecha no es el minino original, es systemback.

**Comment by jasvazquez** [comment]
Pues entonces igual hay que cambiarlo 😅 👍🏻

**Comment by aosucas499** [comment]
Probamos refracta al generar la ISO y vemos qué tal se da. Yo recuerdo que había varias formas y alguna la liaba, se confundía de dispositivo al arrancar en live y te instalaba el sistema en el pendrive, reconocía al pen como sda y el disco duro como sdb.  Los tipos de instalación vienen explicados aquí, en el apartado características. Desatendido, automático, etc... [link](https://minino.galpon.org/es/que-es)

**Comment by jasvazquez** [comment]
Pues entonces lo pasamos a IDEA (ya no hay DUDA que valga) y cuando consideremos oportuno a TODO para meterle mano

**Comment by jasvazquez** [comment]
Lo paso a ESTUDIO para cubrir las pertinentes pruebas comentadas 👍🏻

**Comment by aosucas499** [comment]
Pues cerramos tarea con la elección de Refracta por su facilidad de instalación y abanico de posibilidades.
