### ISSUE TITLE
Configuración región horaria

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#38]
Teniendo en cuenta que _update-minino.sh_ es de "consumo interno" para generar las nuevas versiones de Minino ¿Es realmente necesario tener que indicar la zona horaria a utilizar o (de ser factible y sencillo) podríamos optar por usar el parámetro adecuado y evitar tener que elegir correctamente la zona?

![image](https://user-images.githubusercontent.com/604744/102791563-7b2bce80-43a7-11eb-9408-2b9e87718e52.png)

Entiendo que cuesta relativamente poco pero (de ser posible)... ¿podemos obviarlo?

**Comment by aosucas499** [comment]
¿Te gusta así más? [commit](https://github.com/aosucas499/minino-TDE/commit/5bb77d4eff7b65ccadab3ff63f4f20b6f965df6f)
