### ISSUE TITLE
Crear nueva ISO de Minino-TDE

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#39]
Tras comentario de @aosucas499 en #36 sobre la idoneidad (o no) de crear una nueva ISO me animo a crear esta tarea para no "guarrear" dicha tarea con algo que le es "ajeno" 😏 😅 

La verdad es que (salvo la tarea #6) pocas tareas TODO quedan en el tintero (el resto son IDEAs que pueden quedar para una futura _release_)

Sólo me preocupa #31 y las consecuencias que pueda tener (no probado ni buscada alternativa para mitigar posibles problemas) que alguien se ponga activar/desactivar opciones 🤔

**Comment by jasvazquez** [comment]
Tras implementar la #31 parece que ya podemos acometer esta tarea ¿No te parece @aosucas499? 😉

**Comment by aosucas499** [comment]
Sin duda, estoy probando diferentes instaladores. Un compañero italiano ha sacado una herramienta magnífica para generar ISO y sobretodo usar instaladores, estoy probando, échale un vistazo. 
[https://github.com/pieroproietti/penguins-eggs](https://github.com/pieroproietti/penguins-eggs)

**Comment by jasvazquez** [comment]
Tiene muy buena pinta y, el uso de puppets, abre interesantes posibilidades 🤔

**Comment by aosucas499** [comment]
Échale un vistazo a la ISO: http://bit.ly/2KOpodK

No he podido usar la herramienta penguin eggs, hablé con el autor pero lleva mucha modificación para adaptarla a las nuevas distros. Además el instalador calamares quizás fuese lento en algún chuck norris. Pero el aprendizaje de la herramienta ha valido la pena para aplicar en la iso de educaandos y si hacemos algún perrete jajja

He borrado el systemback que complica a la gente y le he restaurado refracta. Haré una wiki con los pasos para instalar del refracta que trae minino de siempre, la opción desatendida es la más fácil y la que puede traer menos problemas a los que solo quieran instalar en un pc y no complicarse. 
Los cambios que he hecho desde la última modificación están en el archivo [prepareIso.sh](https://github.com/aosucas499/minino-TDE/blob/main/prepareIso.sh). En cuánto la mires y probemos lo paso al updateminino para que se vayan quedando los cambios y borro ese script del repositorio.

**Comment by jasvazquez** [comment]
Hola compi

He estado probando la ISO y va realmente bien, aunque me he encontrado que el _customize-minino_ estaba fallando (ni funcionaba ssh ni dejaba instalarlo y la opción siempre aparece marcada como si estuviese activa en el sistema)

Al final resulta que falta un `apt update` motivo por el cual no encuentra el paquete _openssh-server_

![image](https://user-images.githubusercontent.com/604744/103559323-3d09d100-4eb6-11eb-8b22-e1cbaf679296.png)

**Comment by jasvazquez** [comment]
En otro orden de cosas este mensaje puede despistar 

![default-password](https://user-images.githubusercontent.com/604744/103559634-c28d8100-4eb6-11eb-9b6b-4adb941ed219.png)

pero entiendo que poco vamos a poder hacer al respecto (salvo desear que no lo lean los que vayan a usarlo pues está "oculto" en las opciones avanzadas del instalador 😅 )

Igualmente me llama la atención encontrar estas opciones 

![modo-avanzado](https://user-images.githubusercontent.com/604744/103559735-e8b32100-4eb6-11eb-9571-774a0dcc497d.png)

aunque el autologin nos ignora pongamos lo que pongamos y los scripts pre/post podrían ser interesantes como forma (utilizando nuestro _update-minino.sh_) de actualizar la iso por defecto de Minino 🤔

**Comment by aosucas499** [comment]
> Hola compi
> 
> He estado probando la ISO y va realmente bien, aunque me he encontrado que el _customize-minino_ estaba fallando (ni funcionaba ssh ni dejaba instalarlo y la opción siempre aparece marcada como si estuviese activa en el sistema)
> 
> Al final resulta que falta un `apt update` motivo por el cual no encuentra el paquete _openssh-server_
> 
> ![image](https://user-images.githubusercontent.com/604744/103559323-3d09d100-4eb6-11eb-8b22-e1cbaf679296.png)

Corrígelo en el cusomize-minino que voy a rehacer la ISO por lo que te cuento en el siguiente post y se queda incluído.

**Comment by aosucas499** [comment]
> En otro orden de cosas este mensaje puede despistar
> 
> ![default-password](https://user-images.githubusercontent.com/604744/103559634-c28d8100-4eb6-11eb-9b6b-4adb941ed219.png)
> 
> pero entiendo que poco vamos a poder hacer al respecto (salvo desear que no lo lean los que vayan a usarlo pues está "oculto" en las opciones avanzadas del instalador  )
> 
> Igualmente me llama la atención encontrar estas opciones
> 
> ![modo-avanzado](https://user-images.githubusercontent.com/604744/103559735-e8b32100-4eb6-11eb-9571-774a0dcc497d.png)
> 
> aunque el autologin nos ignora pongamos lo que pongamos y los scripts pre/post podrían ser interesantes como forma (utilizando nuestro _update-minino.sh_) de actualizar la iso por defecto de Minino

Pues se me olvidó incluir la modificación en el script porque modifiqué el instalador y le quité el texto del usuario minino. Miré lo de los scripts pre y postinstall. Estuve pensando en crear la iso con el acceso directo al instalador en el escritorio y que el post-install lo borrara del escritorio al instalar el sistema, pero esa idea es genial. Podemos mirarlo para futuras releases...

**Comment by jasvazquez** [comment]
Genial... ahí queda y creo tarea como IDEA para una futura _release_ 👍🏻

**Comment by aosucas499** [comment]
He generado como tres veces hoy la ISO, sigo viendo el fallo del customize, sale activado el ssh y si le das a aplicar no lo instala. En el [código](https://github.com/aosucas499/minino-TDE/blob/a143c77579f296d8a26228cd39abb2c890168a23/update-minino.sh#L159) he incluido el apt get update pero nada. 

También he probado que la ISO al arrancar traiga el icono del instalador en el escritorio pero lo de que lo borre del escritorio al instalar no lo consigo, y eso que estaba en el código, lo he puesto de dos maneras pero nada. Así se queda ya. Cuando se solucione se modifica la ISO, la tengo en DRIVE y con la gestión de versiones siempre tendrá el mismo enlace.

También tenemos [wiki](https://github.com/aosucas499/minino-TDE/wiki).

Te dejo a ti que lo anuncies en los canales de Telegram y el foro TDE cuando lo consideres oportuno. Un saludo y gracias compañero.

**Comment by jasvazquez** [comment]
Lo miro mañana Andrés (llevo unos días "enfilado" con la forma de poder aplicar Scrum con GitHub para mis alumnos de Bachillerato y me tenía algo agobiado el tema. Me pasa por tirarme al charco continuamente... un día de estos pego una "buchá" 😅) y te cuento (prefiero que generes tú la ISO que tienes más pericia 💪🏻

**Comment by aosucas499** [comment]
😆😆😆😆😆😆 cuando puedas, no hay prisa. Ya he pensado en dejarla por hoy.

**Comment by aosucas499** [comment]
Tras comprobar que lo has solucionado he generado la ISO. He vuelto a modificar el post script del instalador para que borre el icono del escritorio después de instalar, pero sigue sin funcionar. Más adelante lo intentaré que me tiene muy "jarto". En la wiki por ahora viene la explicación de que se borre a mano tras instalar. La ISO está generada en el mismo enlace y tenemos [wiki para la instalación](https://github.com/aosucas499/minino-TDE/wiki/Instalaci%C3%B3n), cuando comuniques la nueva ISO en telegram y el foro TDE cerramos esta tarea.

**Comment by jasvazquez** [comment]
Vaya, me alegro que (ahora sí) te haya funcionado el _customize-minino.sh_ 😅 

¿Creamos tarea para resolver el problema que mencionas y damos por buena (=distribuible) la última ISO que has generado o tienes en mente probar alguna cosa más? 🤔

**Comment by aosucas499** [comment]
Nada más en mente compañero, distribuye 😉

**Comment by jasvazquez** [comment]
Como hablamos, cierro la tarea tras darle difusión a la nueva versión en Telegram y [foro TDE](https://educacionadistancia.juntadeandalucia.es/aulavirtual/mod/forum/discuss.php?d=1197#p3845).
Buen trabajo, compi 👍

**Comment by aosucas499** [comment]
Buen trabajo el tuyo compañero!!!

**Comment by jasvazquez** [comment]
Esto es trabajo en equipo, que bastante "tute" llevas 🤣👍🏻

**Comment by aosucas499** [comment]
Total, me voy a jubilar de PC.

**Comment by jasvazquez** [comment]
¿Jubilar de PC? Eso no lo he entendido 😳

**Comment by aosucas499** [comment]
Quitarme de usar el PC un tiempo jajaka

**Comment by jasvazquez** [comment]
Ya veo que quieres dedicarte en cuerpo y alma a las Vexia 😏🤣
