### ISSUE TITLE
Menú gráficos duplicado en ImageMagik

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#4]
Eliminar el menú que aparece repetido

**Comment by jasvazquez** [comment]
@aosucas499 existe una posible solución gráfica

![image](https://user-images.githubusercontent.com/604744/101202660-d81a4b80-3669-11eb-86ec-7bd565eea705.png)

Pero me gustaría encontrar la forma de hacerlo desde la terminal de comandos 😅

**Comment by jasvazquez** [comment]
Incluso sin usar la terminal 🤣 
![image](https://user-images.githubusercontent.com/604744/101202930-3fd09680-366a-11eb-90bf-e521b272f71d.png)

**Comment by jasvazquez** [comment]
Y aquí está el fichero que "molesta"... sólo habría que lanzar un ``rm`` desde la terminal 😉 
![image](https://user-images.githubusercontent.com/604744/101203082-74dce900-366a-11eb-9c32-e237540ab5bc.png)

**Comment by jasvazquez** [comment]
Solucionado... basta con lanzar un

```
sudo rm /usr/share/applications/display-im6.q16.desktop
```

**Comment by aosucas499** [comment]
Añadimos un script al código donde añadir las mejoras/funcionalidades para aplicar a la iso.

**Comment by jasvazquez** [comment]
Me parece una gran idea @aosucas499 👍🏻
