### ISSUE TITLE
Ultraportátiles verdes

### ISSUE THREAD

**Issue by MaestroMallo** [aosucas499/minino-TDE#43]
En dos ultraportátiles verdes, los samsung, se instala bien pero luego no funciona el audio.

En otros 2 se para la instalación cuando se indica la zona horaria, directamente al poner Madrid, se sale de la ventana de instalación y vuelve al escritorio.

**Comment by jasvazquez** [comment]
Hola @MaestroMallo, bienvenido.
Sería útil conocer el modelo exacto de este ultraportátil ¿Lo tendrías a mano?
Samsung tenemos algunos azules en mi centro pero verdes no (igual son los mismos "pintados" 😉 )

**Comment by aosucas499** [comment]
Para el problema de la hora, prueba la instalación "básica" o experto.

**Comment by jasvazquez** [comment]
¿@MaestroMallo nos confirmas si se ha resuelto con la sugerencia de Andrés?
Gracias

**Comment by aosucas499** [comment]
Esto es que el compañero ha usado la versión antigua que venía con el sonido bajado o que lo ha solucionado y no entra por aquí. Los samsung verdes están más que comprobados, de hecho creé la primera versión en ellos que son los que tengo en el centro. Cierro.

**Comment by jasvazquez** [comment]
Me parece perfecto, una cosa menos 👍🏻

**Comment by aosucas499** [comment]
Y comentar que la iso actual arranca el sistema con el volumen bajado. Se quedó así hasta que solucionemos lo de los Toshiba pequeñitos

**Comment by jasvazquez** [comment]
Igual vamos a tener que crear tarea específica para tratar los problemas de sonido y abordar una posible solución lo más genérica posible 🤔
