### ISSUE TITLE
No funciona el sonido después de instalar minino en Toshiba Tecra M5

### ISSUE THREAD

**Issue by Profetonino** [aosucas499/minino-TDE#44]
Aparentemente todo funciona bien, pero el sonido no hay manera.

**Comment by aosucas499** [comment]
¿Este modelo es el chuck norris? Lo digo porque siempre ha ido bien y este modelo tiene una ruedecita física para el volumen en el frontal o el lateral. Me pasó muchas veces que estaba en el mínimo la "ruedecita".

**Comment by jasvazquez** [comment]
¿@Profetonino pudiste comprobar si el problema era por la "ruedecita"?
Físicamente no tengo Chuck Norris (para poder hacer pruebas), para mí sería un alivio 😅

**Comment by acmaraverm** [comment]
Tenía el mismo problema con el sonido al instalar Minino en los Chuck Norris... Acabo de comprobar lo que comenta @jasvazquez sobre la ruedecita y es así... tenía el audio apagado... al girar la ruedecita ya funciona perfectamente el sonido. Os hablo del Toshiba PTM50E (azul).

A veces la solución es mucho más obvia de lo que todos pensamos...

**Comment by jasvazquez** [comment]
Genial, muchísimas gracias por confirmarlo 😍
Entonces, salvo que @Profetonino diga lo contrario, optaré por cerrar esta tarea ¡Una menos! 😅👍🏻
Gracias a los dos por ayudar a mejorar Minino-TDE
