### ISSUE TITLE
Instalación de Minimo OS (versión 7 enero) en Toshiba PTM50E (Chuck Norris)

### ISSUE THREAD

**Issue by acmaraverm** [aosucas499/minino-TDE#45]
Buenos días,

Antes de nada agradeceros el trabajo y dedicación que estáis haciendo para hacernos la vida un poco más fácil a los coordinadores TDE. La verdad es que hacéis una labora encomiable y es digno de alabar.

Os escribo porque estoy intentando salvar un carro de portátiles de los Toshiba PTM50E (los que llamáis Chuck Norris). He instalado la última versión de Minino OS siguiendo las indicaciones que se recogen en esta página, pero al finalizar el proceso, reiniciar y retirar el USB, me sigue apareciendo el sistema operativo que tenía anteriormente (Guadalinex Edu Slim). Me salta el error de que la instalación se ha realizado correctamente, pero no es así. 

Muchas gracias de nuevo por vuestra ayuda.

**Comment by acmaraverm** [comment]
He conseguido arreglarlo eliminando las particiones anteriores y creando unas nuevas con GParted antes de instalar la nueva versión de Minino.

**Comment by aosucas499** [comment]
Sí, el problema es en la instalación "Desasistida". A veces, no siempre, en el chuck norris que yo haya probado, intercambia los /devices. Piensa que el pendrive es /dev/sda y el disco duro /dev/sdb. La solución es usar la opción de instalación básica u otra.
Gracias por el feedback.

**Comment by aosucas499** [comment]
El nuevo instalador está dando problemas. Escribe la gente diciendo que le falla en Pc's que nunca falló, por eso lo cambié a systemback. Tenemos que estudiar la posibilidad de modificar el instalador (daría trabajillo), dejar dos versiones, una con systemback o buscar otra alternativa.

**Comment by jasvazquez** [comment]
Seguimos la conversación en la tarea #48 que has creado
