### ISSUE TITLE
Toshiba nb500 (Problema con driver sonido)

### ISSUE THREAD

**Issue by jaimecarrascogarcia** [aosucas499/minino-TDE#46]
Hola! Al instalar el sistema, no funciona el driver...he encontrado [esta solución](https://www.linux.org/threads/solved-peppermint-on-toshiba-nb500-no-audio.28042/)...y parece que funciona pero al meter los códigos que se indican en ella para que realmente reinicies la computadora y no tengas que realizar el proceso de seleccionar la tarjeta de sonido cada vez que inicias, no me ha funcionado...si alguien lo soluciona y de paso lo "incluye" en customize-minino. Agradecido. Un saludo!!

**Comment by jasvazquez** [comment]
Agradecidos a ti, Jaime... intento sacarle un rato y probar en el NB500 que tengo "secuetrado" en casa con Minino-TDE 😉

**Comment by jasvazquez** [comment]
Se observa que, en cada reinicio, se desactiva el "hack" de activar el _headphone_ como salida de audio.
Esta tarea es parecida (tiene la misma solución) que la #6 por lo que descartamos esta en favor de la más antigua Jaime 👍🏻
