### ISSUE TITLE
Propuesta "Actualizador Sistema"

### ISSUE THREAD

**Issue by jaimecarrascogarcia** [aosucas499/minino-TDE#47]
Hola! Propongo, incluir alguna aplicación, dentro del sistema operativo que te facilite el "actualizar" el mismo tipo "Minino Update" para que los sistemas siempre tengan la última versión. Creo que sería una buena idea, para mantener el sistema siempre a la última y resolver fallos....

Un saludo y dejo el tema abierto a debate....

**Comment by jasvazquez** [comment]
Hola Jaime, diría que la idea que propones va en la línea de la tarea #32 creada por @aosucas499 🤔

**Comment by jasvazquez** [comment]
La etiqueto como DUDA mientras acordamos si es equivalente a la propuesta de la tarea #32

**Comment by jasvazquez** [comment]
Cierro la tarea tras comprobar que es similar a la propuesta de la tarea #32
