### ISSUE TITLE
Crear script para actualizar la hora

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#5]
Se hace necesario implementar un script que permita actualizar la hora del equipo mediante el protocolo NTP

**Comment by jasvazquez** [comment]
~Esta tarea empieza a "quemarme".~

~Para asentar un "flujo de trabajo" común, comentar que lo habitual en metodologías ágiles (de las que ya irás comprobando que soy un "adepto") es que las correcciones (etiqueta FIX en nuestro caso) deben ser acometidas antes que ninguna otra (no están permitidos los fallos 😉 y, si se tienen, deben corregirse a la mayor brevedad posible)~

~¿Cómo podemos  meterle mano? ¿Quién podría hacer las pruebas que necesitamos?~

**Comment by aosucas499** [comment]
¿Te quema la tarea de la hora o en general las pruebas?

**Comment by jasvazquez** [comment]
Mil perdones Andrés... confundí la tarea. 
Me llevo el comentario a donde procede hacerlo 😅 🙈

**Comment by jasvazquez** [comment]
Cuidado Andrés, [estas líneas](https://github.com/aosucas499/minino-TDE/blob/9babc1c4de063577d40d9ba5c53374f921118043/update-minino.sh#L18-L21)  están dando problemas debido a la ruta relativa que estamos usando

![image](https://user-images.githubusercontent.com/604744/101286208-7da7f900-37e9-11eb-897b-5d8315bd7554.png)

**Comment by jasvazquez** [comment]
Aunque, ahora que lo pienso, me surge la duda... 
+ ¿por qué has optado por incluir la ejecución del script como algo opcional? 
+ ¿no debería ser por defecto en todos los equipos?

**Comment by aosucas499** [comment]
Como te comento en #12, no me convence mezclar el update-script con las elecciones para el usuario. Al querer añadirlo a tu modificación del script me he liado con la idea.

**Comment by jasvazquez** [comment]
Por no mezclar temas, opto por crear la tarea #16 👍🏻

**Comment by aosucas499** [comment]
Con respecto a lo de las rutas relativas, pensando en que el update-script sea algo para simplemente actualizar de una versión a otra, yo pensé en aplicar en la iso antigua este script usando un "git clone aosucas499/minino-tde". ¿Cómo lo aplicas o lo has pensado tú?

**Comment by jasvazquez** [comment]
Ambas cosas no están reñidas: se puede hacer un ``git clone aosucas499/minino-tde /tmp/minimo-tde`` de modo que sepas que (sí o sí) tu script va a estar siempre en la carpeta ``/tmp/minimo-tde``

No sé si he logrado explicarlo 😅

**Comment by aosucas499** [comment]
Claro que te explicas bien, el que no se explica bien hoy soy yo.
Debería no dar problemas igualmente aunque descargues el proyecto en la carpeta /tmp, ¿no? Creo recordar que puse que busque los archivos necesarios en la carpeta ntp que se descarga del proyecto junto al script. Le echo un vistazo.

**Comment by aosucas499** [comment]
> Cuidado Andrés, [estas líneas](https://github.com/aosucas499/minino-TDE/blob/9babc1c4de063577d40d9ba5c53374f921118043/update-minino.sh#L18-L21) están dando problemas debido a la ruta relativa que estamos usando
> 
> ![image](https://user-images.githubusercontent.com/604744/101286208-7da7f900-37e9-11eb-897b-5d8315bd7554.png)

Me funciona aunque lo descargue en /tmp/minino-tde. Me he perdido en porqué te ha fallado ahí. ¿Descargaste solo el update script sin la carpeta?

**Comment by jasvazquez** [comment]
Altamente probable (creo recordar que usé un ``wget`` y luego me sorprendió ver que habías subido una carpeta nueva 😅 )

Igual sería interesante modificar el script para que lo primero que haga es un `git clone` de nuestro repositorio (un script "auto contenido") en la línea de [lo que planteo en este comentario](https://github.com/aosucas499/minino-TDE/issues/16#issuecomment-739540338). De este modo, podríamos incluir un nuevo icono en el menú tipo "Actualizar Minino-TDE" que descargue la última versión del script y actualice el sistema sin que el profesorado tenga que preocuparse de detalles técnicos 🤔

**Comment by aosucas499** [comment]
Genial.

**Comment by aosucas499** [comment]
Cerramos el issue de la hora, está incluido en la parte del script que vamos a dejar para actualizar ISO's.
