### ISSUE TITLE
En ocasiones Minino se instala en el pendrive

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#52]
@aosucas499 tras probar [el código de la captura de pantalla que has subido](https://github.com/aosucas499/minino-TDE/issues/49#issuecomment-766403357) (especialmente en la línea `mount | grep "/live/image" | cut -d " " -f 1`) observo que está algo obsoleto y que "acierta por casualidad" cuando determina la partición en la que se encuentra el disco duro del equipo.

En vbox ni por casualidad

![image](https://user-images.githubusercontent.com/604744/105640262-68605a00-5e7d-11eb-92c7-4b7730b4d30b.png)

pero en el NB500 que tengo adoptado tampoco lo hace

![Captura_dom ene 24 18:52:05](https://user-images.githubusercontent.com/604744/105640390-b07b7e80-5e75-11eb-8eae-eb92171e7671.png)

porque ya no parece que se monte en _/live/image_

**Comment by aosucas499** [comment]
Genial, estupenda investigación.¿Alguna idea para mejorarlo?

**Comment by jasvazquez** [comment]
Tengo un par de ideas pero necesito madurarlas un poco... quedan en mi cabeza como "threads" de baja prioridad, seguramente mañana (o pasado) se me encienda la "mono neurona" 🤣

**Comment by jasvazquez** [comment]
El tema de las Vexia es el que me "descuadra" (y eso que entiendo que no debería estar entre los dispositivos objeto de Minino a día de hoy 😅 ) ya que, [al tratarse de una tarjeta de memoria](https://github.com/aosucas499/minino-TDE/issues/49#issuecomment-766400760) lo que usa como disco, me impide listar particiones y/o discos con un simple `grep /dev/sd` 🤔

**Comment by aosucas499** [comment]
Ya te contaré con detenimiento. Me ha traído loco, pero eso sí, he aprendido muchísimo de arranques uefi, grub, etc....
Sí, las particiones son mmcblk*.

**Comment by jasvazquez** [comment]
Duda "tonta" (que ya estoy licuado) ¿Puedo entender que en las Vexia, el instalador que te ha funcionado ha sido el manual eligiendo particiones, verdad?

Lo digo porque el famoso código en una Vexia te asignaría `/dev/sda` como destino de la instalación y, dicha partición no existe en las tablets 🤔

**Comment by aosucas499** [comment]
Sí. El desatendido en su versión manual. Aunque lo dificil es arrancar un sistema de 64 bits con bios excluiva uefi 32 bits.

**Comment by jasvazquez** [comment]
Con temor (por ir a ciegas y no tener datos de equipos en los que ha dado problemas) doy por cerrada la tarea (aunque las pruebas que hagan los compañer@s determinarán si habrá que retomar, o no, el tema 😅 )

En principio es algo más robusto de lo que había:

+ Lista los discos existentes en el equipo
+ Elimina de la lista anterior cualquier partición que pueda estar montada (normalmente el pendrive pero quién asegura que alguien pruebe a montar algo del disco antes de decidir instalar 🙈 Juego con que es algo poco probable... pero no imposible)
+ Se queda con la unidad más baja que esté sin montar (si es _sda_ de lujo; si está montada, se queda con _sdb_ y así sucesivamente)

Cuando quieras/puedas puedes crear una nueva ISO. Sería interesante, antes de publicarla, poder hacer alguna prueba de instalación con un equipo físico (si me la pasas, tengo aquí un nuevo NB500) en lugar de con una VBox (pues, [como hemos visto](https://github.com/aosucas499/minino-TDE/issues/52#issue-792866781), gestiona de forma diferente las particiones)

**Comment by aosucas499** [comment]
Eres un crack. Enhorabuena por tu trabajo. He generado la ISO y la he probado en virtualbox y va genial. Aquí te paso el enlace para que la pruebes en los dispositivos reales.
[minino-tde-testing](https://drive.google.com/file/d/1AFOcrOuHGwzmxOwo_7ajE3k69VT8l33O/view?usp=sharing)

**Comment by jasvazquez** [comment]
Se agradece Andrés, pero no las tengo todas conmigo, de ahí mis reticencias respecto a la solución planteada. Puedo probarla en el NB500 y creo que tengo algún Samsung (no sé el modelo) en el centro. 
Sería interesante contactar con algunos de los que han tenido problemas para que prueben ¿Te parecería descabellado? 🤔

**Comment by aosucas499** [comment]
No me parece descabellado. Si te vale, yo voy a empezar esta semana a instalar mi clase de informática con 30 Chuck Norris que me dieron problemas de instalación en modo desatendido-automático y los dejé sin instalar pensando en ponerlos de conejillo de indias cuando se reparase el instalador.

**Comment by jasvazquez** [comment]
Y tanto que vale, Andrés. No cabría mejor prueba ni "tester" 👍🏻

**Comment by jasvazquez** [comment]
Vuelvo a abrir la incidencia tras ser varios los [compañer@s que comentan que les sigue fallando](https://t.me/coordinacionTicAndalucia/7925) 😅

**Comment by aosucas499** [comment]
Pues yo hoy he instalado 10 chuck norris en automático y todo perfecto

**Comment by jasvazquez** [comment]
Igual Antonio no está haciéndolo en un Chuck Norris y/o tenemos la oportunidad de encontrar cuál es el problema con algunos equipos.
Voy a dejarla abierta unos días (para darle tiempo a poder comentar en la tarea) y si no hay "feedback" la vuelvo a cerrar 👍🏻

**Comment by aosucas499** [comment]
Por hablar. El onceavo ha reconocido el pendrive como sda. Primer fallo.

**Comment by jasvazquez** [comment]
No diré que me alegro de oírlo pero sí que nos viene genial

¿Puedes pasarme el resultado *completo* de lanzar un `mount`?

**Comment by aosucas499** [comment]
![IMG_20210202_134654](https://user-images.githubusercontent.com/72696244/106602759-b4865b00-655d-11eb-80fa-f5b8fe259d90.jpg)
![IMG_20210202_134712](https://user-images.githubusercontent.com/72696244/106602762-b6e8b500-655d-11eb-950a-dcece92fdb83.jpg)

**Comment by jasvazquez** [comment]
Y para terminar de abusar de su cortesía amigo Andrés... ¿mucho pedir un `lsblk`? 😅

**Comment by aosucas499** [comment]
Casi jajaja. He abandonado la clase jajaj. Mañana que sigo, en nada que falle otro te lo mando.

**Comment by aosucas499** [comment]
Por ahora han fallado 3 de 13

**Comment by jasvazquez** [comment]
Cachis.... esta noche no voy a poder dormir con tanta intriga 😏🤣

La buena noticia de ese 3/13 es que tenemos "conejillos de indias" para hacer pruebas 😉 (que precisamente lo que estaba echando de menos y me preocupaba 👍🏻)

**Comment by aosucas499** [comment]
![IMG_20210203_101935](https://user-images.githubusercontent.com/72696244/106782153-1e7c2e80-664a-11eb-941d-63669e62cc15.jpg)

**Comment by jasvazquez** [comment]
Muchas gracias compañero... parece que el disco del equipo está en el /dev/sdb
¿A qué `mount` de los que mandaste ayer corresponde esa captura?
Necesito "casar" mount y lsblk para ver cómo se comporta (y cómo debería hacerlo) el script en el equipo 👍🏻

**Comment by aosucas499** [comment]
Pues son diferentes compañero. Pero todos los que te mandé ayer y hoy hacen lo mismo, montar el sdb como disco duro y sda el usb. Aunque eso ya lo sabías. Me quedan 4 o 5 por instalar, en cuánto me falle uno te hago todos los comandos en el mismo.

**Comment by jasvazquez** [comment]
No tiene ningún sentido... la variable `discoduro`, con los datos proporcionados, debería quedar como `sdb` sí o sí
Si no te es demasiada molestia, redirecciona la salida de los comandos a ficheros y me los mandas (para probar contra el script)

![image](https://user-images.githubusercontent.com/604744/106786253-a106ed00-664e-11eb-9d7e-e019864561d4.png)

Porque no estar usando la última versión del instalador no es algo posible ¿verdad? (sé que estás usando la última ISO. la beta, pero... ¿y si Minino está cogiendo otro script?) No sé, estoy entrando en modo "paranoico"  🙈

**Comment by aosucas499** [comment]
Me haces dudar con que si en alguno de los dos pendrives he utilizado la versión anterior, yo juraría que no. Olvida esas fotos y las próximas los hago a 100% y mandando todo del mismo. Mi cabeza no anda muy allá últimamente con tanta cosa.

**Comment by jasvazquez** [comment]
No me extraña, andamos locos algunas veces 🙈

**Comment by aosucas499** [comment]
[lsblk.lst](https://github.com/aosucas499/minino-TDE/blob/main/tools/lsblk.lst)

[mount.lst](https://github.com/aosucas499/minino-TDE/blob/main/tools/mount.lst)

**Comment by jasvazquez** [comment]
Se comprueba que, en la beta, incluso con la configuración indicada por Andrés, la elección de la partición a usar como _discoduro_ es la correcta (_sdb_)

![image](https://user-images.githubusercontent.com/604744/107123030-97be9000-689b-11eb-9d2f-deee91ab62ab.png)

Procedo a revisar cuándo (y dónde) se está usando el código que hemos modificado (la única explicación que encuentro es que no se esté llamando a la función `partauto()` que hemos modificado 🤷🏻‍♂️ )

**Comment by jasvazquez** [comment]
Definitivamente, el fichero utilizado es `/usr/local/bin/minino-installer-b` y no existe otra referencia a la función `partauto()` en el sistema

Se activa la opción de _debug_ en el script de instalación

```
exec 19>/tmp/kk.logfile
BASH_XTRACEFD=19

set -x
```

**Comment by jasvazquez** [comment]
Se detecta que el script desmonta unidades y deja el sistema (entre otros) sin el disco de swap dando errores si se intenta instalar (con 1GB) cualquier cosa (ni un mísero comando _less_ con _apt_) aunque, a todos los efectos el usuario sólo ve el mensaje "en verde" (dando la sensación de haber finalizado el proceso correctamente) y no se percata del problema

![image](https://user-images.githubusercontent.com/604744/107126788-39e97280-68b2-11eb-96b2-6adc8d576eaa.png)

Físicamente, si estás delante del equipo llega a apreciarse el error y se nota (de lejos) que tarda muchísimo menos el proceso (no aplica el `rsync` para volcar a disco los ficheros de Minino)

@aosucas499: 

+ ¿sueles dejar los equipos en modo "desatendido" cuando se están instalando para poder seguir con la instalación de otros?
+ ¿tienen algo diferente los equipos donde está dando problemas? (no termino de entender cómo es posible que cambie la asignación de las unidades)
+ ¿en los equipos con problemas haces algo antes de lanzar el instalador? (por si se monta las unidades y por éllo falla)
+ ...

**Comment by aosucas499** [comment]
1. Sí.
2. Son todos iguales. Chuck Norris.
3. Solamente lanzo un "df" para ver dónde se ha montado el live y ejecutar la versión manual o automática.

**Comment by jasvazquez** [comment]
Simulo el cambio de "nomenclatura":

+ añadiendo a la máquina virtual un segundo disco
+ montando el primer disco (para simular) que es el pendrive en VBox

el script selecciona correctamente el segundo disco (_sdb_) para hacer la instalación

![image](https://user-images.githubusercontent.com/604744/107127550-25f43f80-68b7-11eb-97c3-27d3e42719fb.png)

**Comment by jasvazquez** [comment]
@aosucas499:

+ ¿podrían tener Windows los equipos en los que falla?
+ ¿están particionados los discos de los equipos con problemas?
+ ¿instalación desde pendrive o desde cdrom?
+ ¿has podido usar [PloP Manager](https://www.google.com/search?q=plop+manager&sxsrf=ALeKk01fryWa1feQs6R6EN15OxCTQWtT2A:1612638956563&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjdo6Ch_NXuAhWah1wKHSMrAHAQ_AUoAnoECAcQBA&biw=1918&bih=918)?

**Comment by aosucas499** [comment]
> @aosucas499:
> 
>     * ¿podrían tener Windows los equipos en los que falla?
> 
>     * ¿están particionados los discos de los equipos con problemas?
> 
>     * ¿instalación desde pendrive o desde cdrom?
> 
>     * ¿has podido usar [PloP Manager](https://www.google.com/search?q=plop+manager&sxsrf=ALeKk01fryWa1feQs6R6EN15OxCTQWtT2A:1612638956563&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjdo6Ch_NXuAhWah1wKHSMrAHAQ_AUoAnoECAcQBA&biw=1918&bih=918)?

1. No. ¿Menuda pregunta a estas alturas? En mi centro no entra eso jajaja
2. Tenían este sistema [link](https://sites.google.com/site/guadalinexunofficial/inicio) versión ggcloud i386 que ya han borrado. Supongo que tenía una partición ext4 y otra swap.
3. USB
4. Plop Manager no era necesario, arrancaba perfectamente el pendrive.

**Comment by aosucas499** [comment]
Confirmado que el pendrive que estuve usando tiene tu código y es el minino-testing.

**Comment by jasvazquez** [comment]
@aosucas499:

1. ¿el fallo es determinista o espúreo? (cuando un equipo falla lo hace siempre o según le parece?
2. Si te proporciono el modo ¿podrías ejecutar el instalador automático en un equipo que falle y proporcionar el fichero de depuración?

**Comment by aosucas499** [comment]
1. Pues no he repetido la instalación en ninguno.
2. Claro

**Comment by jasvazquez** [comment]
Sospecho que es "espúreo" pero sería interesante hacer la prueba nuevamente, Andrés

Respecto a la depuración, bastaría con lanzar el siguiente comando

```
/bin/bash -x /usr/local/bin/minino-installer-b 2> /tmp/minino-tde.log
lsblk > /tmp/minino-discos.lst
```

Gracias, monstruo 👍🏻

**Comment by jasvazquez** [comment]
Tras no recibir "feedback" y no poder avanzar (por no tener equipos en los que me falle) me desasigno temporalmente la tarea y la etiqueto como DUDA hasta que haya noticias/información que nos permita progresar 🤷🏻

**Comment by aosucas499** [comment]
Done [log](https://github.com/aosucas499/minino-TDE/blob/9c2735ce316e5a9a58271658ca40c8cc13e0e93b/tools/minino-tde.log)

**Comment by jasvazquez** [comment]
Pues, aunque tengo pendiente volver a echarle un vistazo con algo más de tiempo (y calma) he cometido el tremendo error de no pedir, junto al comando que puse algo más arriba un listado de particiones.

Corrijo mi "craso error" 😅  para cuando tengamos una nueva ocasión de probarlo (sorry, man)

**Comment by jasvazquez** [comment]
No obstante, en el log proporcionado llama (poderosamente) la atención la siguiente entrada

![image](https://user-images.githubusercontent.com/604744/109045885-6a177a80-76d4-11eb-9417-fabe2eeabea5.png)

**Comment by jasvazquez** [comment]
Descarto log tras comprobar que se trata de una instalación "manual" y, por tanto, poco significativa para determinar por qué falla la instalación "automática" de Minino

![imagen](https://user-images.githubusercontent.com/604744/109156512-38a0bc80-7771-11eb-991f-a3dee0e4e264.png)

**Comment by aosucas499** [comment]
Lo sientoz supuse que valía la manual...las prisas y no pensar. Otro día te lo hago en automático aunque detecte mal las particiones. ¿Qué comando necesitas a parte del debug?

**Comment by jasvazquez** [comment]
El `lsblk` para ver la configuración real del equipo y sus discos (te lo he dejado [anotado más arriba](https://github.com/aosucas499/minino-TDE/issues/52#issuecomment-774955547))

**Comment by aosucas499** [comment]
Ok. Me pusieron ayer la vacuna y ando con la cabeza para arrancármela  ajaja....espeso total

**Comment by jasvazquez** [comment]
Se entiende perfectamente: a saber cómo "termino" yo cuando me la pongan (estoy en capilla)

**Comment by jasvazquez** [comment]
#IDEA ¿y si preguntamos al usuario dónde lo quiere instalar @aosucas499?

![imagen](https://user-images.githubusercontent.com/604744/111915050-be640f00-8a74-11eb-8383-7b9a7b6aabc3.png)

**Comment by aosucas499** [comment]
Qué bonito queda!!!!. El problema creo que radica en que la información que muestra del disco duro y el usb (en los que da el problema del intercambio) no era muy aclaratoria. Pero no estoy seguro. Si quieres añadelo y pruebo cuando pueda en un chuck norris. Igualmente cuando tenga tiempo quiero probar la herramienta easter egg para crear un instalador debian.

**Comment by jasvazquez** [comment]
Éso va a ser el "perrete" que tengo de fondo de escritorio 😏 🤣 

Como pequeña mejora le he incluido la comprobación del atributo RM (*R*emovable *M*edia) que nos permite conocer (y  marcar por defecto una de las opciones) si el disco es fijo o "removible" (sospechoso de ser un pendrive)

![imagen](https://user-images.githubusercontent.com/604744/111915710-eb65f100-8a77-11eb-8189-0fd3f9f6c4f0.png)

Aún así no me fío, de ahí que me haya liado la manta a la cabeza e implementado el menú de selección

**NOTA:** no he entendido tu frase "...El problema creo que radica en que la información que muestra del disco duro y el usb (en los que da el problema del intercambio) no era muy aclaratoria..." ¿me das algún detalle extra? 🤔

**Comment by aosucas499** [comment]
Es una mejora bastante importante la del RM. Pues lo que te decía es que cuando instalaba en los chuck norris, costaba detectar realmente cuál era el usb o el disco duro, incluso con el comando df. Porque no mostraba la cantidad de GB de los discos bien creo recordar. Pero vamos, tiene muy buena pinta, yo lo pruebo cuando lo finalices porque tiene pintaza.

**Comment by jasvazquez** [comment]
Me alegra que te guste 👍🏻 

En base a tu comentario estoy tentado a dejar sólo la detección del RM  y olvidarme del menú de selección (no me gusta molestar "innecesariamente" a los usuarios 😏 )

**Comment by jasvazquez** [comment]
Bueno, mejora subida pero, "a ciegas"... cuesta resolver el problema 😅 

Al menos ahora podrán elegir la unidad de destino y, al mostrar las unidades que pueden usarse, igual descubrimos (por salir a la luz situaciones que no cuadren a los usuarios) qué ocurre cuando falla el instalador 🤔 

Cruzo los dedos 👍🏻
