### ISSUE TITLE
Se baja el brillo al conectarlo a pantalla externa

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#53]
Comenta [Javier Ávalos](https://t.me/coordinacionTicAndalucia/7659):

> Samsung verde (no recuerdo el modelo) conectado a una tele por vga. Se ve la imagen si arranca el portátil y está el vga conectado, si lo conectas después no lo reconoce. La pantalla se ve tenue y el monitor/tele se ve bien

**Comment by chipygr** [comment]
Puede ser por algo parecido a lo que les pasa a agunas pizarras por la conexion del vga? Los q no van amplificados.

**Comment by jasvazquez** [comment]
No sabría decirte. 

Por lo que comenta Javier, le ocurre lo mismo al conectar el portátil con un monitor.

Además, parece que sólo presenta el problema si se hace una vez arrancado el equipo: si se enciende el ordenador con un monitor (o pizarra) conectado, parece que no da el problema 🤔

Sería interesante que alguien confirme este problema (yo sólo tengo el NB500 de Toshiba) para confirmar el problema o descartar que sea un problema de la instalación que él tiene.

**Comment by chipygr** [comment]
Yo los tengo en el cole, este finde no os sirvo de tester pero lo veo muy raro para ser un error de software.

**Comment by jasvazquez** [comment]
Genial. No hay prisa: este fin de semana (si hay suerte) con suerte consigo encontrar una solución al tema del instalador que está siendo prioritario 😅

**Comment by jasvazquez** [comment]
Jose Luís [comenta en el grupo de Telegram](https://t.me/coordinacionTicAndalucia/7757) (y tiene sentido) que los equipos sufren cuando el cable de vídeo es relativamente largo y mucho más con un netbook que está usando batería.

**Comment by chipygr** [comment]
Si, es a lo que hacia referencia. A ver si pueban y confirman que es eso, pero me huele a que si.

**Comment by jasvazquez** [comment]
Esto lleva 14 días pendiente y nadie ha comentado ni aportado nada... ¿lo descartamos? 🤔

**Comment by aosucas499** [comment]
Descartamos, mi experiencia dice que cuando alguien tiene un problema y no aparece en tiempo o nadie lo reporta es que lo han solucionado.

**Comment by jasvazquez** [comment]
Pues cerrada queda hasta que aparezca alguien indicando lo contrario 👍🏻
