### ISSUE TITLE
Falla el micro en Toshiba NB200

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#54]
Jaime González [comenta](https://t.me/coordinacionTicAndalucia/7661) que no puede usar el micro del netbook en las videoconferencias de la Moodle

**Comment by jaimecarrascogarcia** [comment]
Efectivamente, el micro del nb200 no funciona. Lo puedo confirmar.
Parece que subiendo el volumen del micro y todo lo que veo en Mute, lo detecta, aunque la calidad del sonido deja mucho que desear...![image](https://user-images.githubusercontent.com/77231941/106433299-4ca61680-6470-11eb-8c8a-762c586ff988.jpeg)
Observando tu foto veo que estás en el menu de reproducir, no? Pulsa en f4 que es para grabación a ver si salen controles de micro añadidos.

**Comment by jasvazquez** [comment]
Pues pocos milagros vamos a poder hacer 😔
Quizás sea cuestión de dejarlos "subidos" antes de generar la ISO 
¿Qué opinará @aosucas499?

**Comment by aosucas499** [comment]
¿Es solo en este modelo o en todos? Lo digo porque en la tablet tampoco me iba el micro y quizás sea algo general.

**Comment by jaimecarrascogarcia** [comment]
La verdad no he probado el micro hasta ahora en ningun Pc, ya he conseguido que se escuche decentemente. Subiendolo todo asi, incluso he puesto el "parche" del nb500. En fin, pero reiniciando no se guarda....!![image](https://user-images.githubusercontent.com/77231941/106443497-d5c34a80-647c-11eb-9517-49bd6b182f66.jpeg)

**Comment by aosucas499** [comment]
Prueba con el siguiente comando al terminar de configurar alsamixer: sudo alsactl store

**Comment by jaimecarrascogarcia** [comment]
Perdón por el retraso pero los lunes por la tarde son horror..
Acabo de probar el comando y no, no funciona, cuando reinicias vuelve a su estado...
He probado el fix del nb500 y me apaga el speaker así que suponía que no tenía sentido pero...lo probé....

**Comment by aosucas499** [comment]
Podriamos hacer un script que se instale solo para ese modelo en customize-minino y que se ejecute en cada inicio con el comando amixer subiendo el volumen del micro, ¿no?

**Comment by aosucas499** [comment]
Me he puesto a pensar y recuerdo que había en los postscript de la instalación de guadalinex edu unos comando relacionados con los nb200. Lo miro por si tenemos la solución ahí.

**Comment by jasvazquez** [comment]
Claro que es posible esa personalización, aunque sin el equipo, las pruebas tendréis que hacerlas vosotros y me vais a tener que ir proporcionando una serie de datos que necesitaría (volveríamos a ir a "ciegas")

Quedo a la espera de que puedas mirar eso scripts de Guadalinex para ver qué hacemos 👍🏻

**Comment by jaimecarrascogarcia** [comment]
Sin problema, quedo a la espera de vuestras indicaciones "para probar" maestros!!

**Comment by jasvazquez** [comment]
@aosucas499 sé que andas bastante liado estos días con las Vexia... ¿sabrías decirnos algo que nos ayudase a localizar los scripts que comentas? (por buscarlos nosotros, igual hasta el amigo @jaimecarrascogarcia se anima y hace la investigación 😅 ) y darle una vuelta de tuerca a este tema 👍🏻

**Comment by aosucas499** [comment]
Aquí tienes el [script](https://github.com/aosucas499/minino-TDE/blob/269f4cdb1547871e8d9476179301359d85daf8a8/tools/late_commands.sh#L54), después te busco el paquete .deb al que hace referencia.

**Comment by aosucas499** [comment]
Por ahora no lo encuentro. Buscando en los repos [catcorner](http://centros.edu.guadalinex.org/Edu/catcorner/pool/main/c/) y [precise](http://centros.edu.guadalinex.org/Edu/precise/pool/main/c/) de guadalinex, no lo veo, que es donde suelo buscar. He montado la iso en el sistema y con find tampoco aparece.

![Captura de pantalla de 2021-02-09 19-54-17](https://user-images.githubusercontent.com/72696244/107413637-40c1f080-6b11-11eb-8db9-a42f97224d1f.png)
![Captura de pantalla de 2021-02-09 19-54-34](https://user-images.githubusercontent.com/72696244/107413653-44557780-6b11-11eb-9645-d9cb1d1acf12.png)

**Comment by jasvazquez** [comment]
Gracias monstruo pero sin prisa: hace un rato ha muerto la fuente de alimentación (y espero que haya quedado ahí porque el "explotío" ha sido brutal) de mi ordenador de trabajo 😤🙈

**Comment by aosucas499** [comment]
OMG cómo te apañas????

**Comment by jaimecarrascogarcia** [comment]
Compis, he llegado tarde al foro ¿No?

**Comment by jaimecarrascogarcia** [comment]
Tengo un NB200 por aqui.....si hace falta me indicais!!!

**Comment by jasvazquez** [comment]
Por equipos en casa no va a ser pero sin el equipo principal (que lo tengo realmente como me gusta trabajar y donde estoy cómodo realmente) imagina.

Mañana le compraré la fuente y rezaré porque no haya sido la placa o alguno de los discos también 😅

**Comment by aosucas499** [comment]
Buscando el paquete en internet he encontrado que está en los repos de una versión antigua de guadalinex que nunca había mirado, la basada en Ubuntu 10 lucid. Mañana lo miro en el pc a ver que contiene el paquete. 
Aquí pongo las direcciones, aunque por el tamaño parece el mismo paquete.

[1.Bonnie](http://guadalinex-edu.cica.es/Edu/bonnie/pool/main/c/cga-toshiba-nb200-sound-config/) 

[2.Lucid](http://guadalinex-edu.cica.es/lucid/pool/main/c/cga-toshiba-nb200-sound-config/)

**Comment by aosucas499** [comment]
![Captura de pantalla de 2021-02-12 17-57-28](https://user-images.githubusercontent.com/72696244/107798110-00a27e00-6d5c-11eb-8220-111cc4482299.png)
![Captura de pantalla de 2021-02-12 17-57-43](https://user-images.githubusercontent.com/72696244/107798119-039d6e80-6d5c-11eb-827c-7ffb7dc553d3.png)

Lo que contiene el paquete son esos dos scripts, el primero, el de instalación a simple vista hace, como ya vi cuando miré alguna posible solución por internet de esa tarjeta de sonido, es añadir ese línea al archivo alsa-base.conf. Lo curioso es que en minino no tenemos ese archivo.

Yo propongo que alguien con el nb200 en casa y minino sin haberle "toqueteado" la configuración de sonido, le instale el [paquete](https://github.com/aosucas499/minino-TDE/raw/main/tools/cga-toshiba-nb200-sound-config_0.1-1_all.deb) a ver qué pasa. Posteriormente podemos investigar si podemos instalarle una versión de alsa diferente sino funciona.

**Comment by jasvazquez** [comment]
Normal que no encuentres el fichero: habrá cambiado en Minino respecto a las versiones de Guadalinex que has encontrado.

La buena noticia es que sirve cualquier nombre de fichero (de hecho, ya tenemos uno con la configuración de la tarjeta de sonido que, si no contiene lo mismo que has encontrado, cambia realmente poco por desgracia)

Esa carpeta (modprobe.d) incluye parámetros para los distintos módulos que carga el kernel y le está indicando que es una Intel y que detecte AUTOmáticamente el modelo)

**Comment by chipygr** [comment]
Yo tengo uno en casa. Decidme q hacer y pruebo

**Comment by jasvazquez** [comment]
Genial, anotado quedas para las prácticas, gracias 👍🏻

**Comment by jasvazquez** [comment]
Bueno, pues parece que no existe tal fichero actualmente en Minino-TDE (parece que me confundí con la pruebas que estuve haciendo para resolver el sonido en el Toshiba NB500 de la #46 😅 )

![imagen](https://user-images.githubusercontent.com/604744/107853267-217ada00-6e15-11eb-89ae-6308f9edf0bb.png)

Pues se agradecería que alguno de los compañeros (@chipygr o @jaimecarrascogarcia) probasen a:

1. Lanzar `sudo bash -c 'echo "options snd-hda-intel index=0 model=auto" > /etc/modprobe.d/snd-alsa.conf'` (y reiniciar el equipo para ver si se arregla el problema así)
2. Lanzar un `lspci` (y colgar una captura aquí del resultado) para ver qué hardware tiene el Toshiba NB200

Quedo a la espera de novedades, gracias a ambos por la ayuda y predisposición 👍🏻

**Comment by chipygr** [comment]
me da un permiso denegado
![índice](https://user-images.githubusercontent.com/77987435/107857461-b9d18880-6e2e-11eb-911d-0393f7a2558a.jpg)

**Comment by jasvazquez** [comment]
Reviso comando: lo escribí sin probar y es posible que el `sudo` esté dando problemas.

**Comment by jasvazquez** [comment]
Efectivamente, modifico comando sobre el comentario original (para evitar que otros puedan confundirse 👍🏻 )

**Comment by jasvazquez** [comment]
Aprovecho para buscar en Internet la tarjeta de sonido. Debe ser ésta pero no estaría de más confirmación:

>  Audio: Card Intel 82801G (ICH7 Family) High Definition Audio Controller driver HDA Intel

**Comment by chipygr** [comment]
Hecho. estos son los resultados
![photo5857057020954392394](https://user-images.githubusercontent.com/77987435/107857737-9a3b5f80-6e30-11eb-9a75-baf7d890486f.jpg)
![photo5857057020954392393](https://user-images.githubusercontent.com/77987435/107857738-9ad3f600-6e30-11eb-8ac8-9bbb8f6cd50e.jpg)
![photo5857057020954392392](https://user-images.githubusercontent.com/77987435/107857739-9ad3f600-6e30-11eb-8e66-2139c79e34f7.jpg)

**Comment by aosucas499** [comment]
> Hecho. estos son los resultados
> ![photo5857057020954392394](https://user-images.githubusercontent.com/77987435/107857737-9a3b5f80-6e30-11eb-9a75-baf7d890486f.jpg)
> ![photo5857057020954392393](https://user-images.githubusercontent.com/77987435/107857738-9ad3f600-6e30-11eb-8ac8-9bbb8f6cd50e.jpg)
> ![photo5857057020954392392](https://user-images.githubusercontent.com/77987435/107857739-9ad3f600-6e30-11eb-8e66-2139c79e34f7.jpg)

Algún fallo al escribir has cometido. "bash" no "bush"

**Comment by jasvazquez** [comment]
Bush, George Bush... padre 😉 
Has estado más rápido que yo buscando el motivo del ">" final 👍🏻

**Comment by jasvazquez** [comment]
Igualmente, recurda @chipygr que cuando tengas creado el fichero, debes reiniciar el equipo para que intente usarlo

**Comment by chipygr** [comment]
A ver entonces... yo pensaba que estaba todo ok y probe el micro con el recordmydeskop y se me oia... eso si, tras subirle el micro en el alsa mix...
Voy a mandar el bash a ver que pasa

**Comment by chipygr** [comment]
Hecho con el bash y se queda el prount tambien, lo dejo a ver si reacciona

**Comment by jasvazquez** [comment]
¿Funciona el micro con calidad aceptable? 

@jaimecarrascogarcia ya comentó que subiendo volumen funciona pero que la calidad no era buena

**Comment by chipygr** [comment]
A ver... yo me escuchaba... es el micro de un portatil... no van a cantar un casting para operacion triunfo 28, no?... seria cuestion de probarlo en una videoconferencia... lo pruebo a ver

**Comment by jasvazquez** [comment]
😂 Totalmente de acuerdo (para lo que es el equipo, con ser funcional nos podemos dar con un canto en los dientes)

Quedo a la espera de esas pruebas 👍🏻

¿El micro mantiene la configuración cada vez que reinicias el equipo? 🤔

**Comment by chipygr** [comment]
Hecho pruebas con la sala de videoconferencias de Moodle en mi misma casa, (no se si influira positiva o negativamente...) es infumable... un lag enorme. oirse se oye pero a tirones, esto es: "Hol         a     est          amos        prob        ando...."
Oirse se oye, y habiendo reiniciado, de hecho he restaurado minino y sigo oyendolo... no se si estas pruebas han servido de algo... voy a volver a instalar desde 0 y comprobar el micro, porque creo que no habia problema salvo el subirlo desde el alsamixer

**Comment by jasvazquez** [comment]
Claro que sirven, y mucho.

Si te parece, prueba a borrar el fichero que hemos creado con un `sudo rm /etc/modprobe.d/snd-alsa.conf` y reiniciar el equipo para ver si el lag lo ha introducido dicho cambio.

**Comment by chipygr** [comment]
Procedo a hacer las pruebas desde cero, habiendo reinstalado Minino.
Desde 0
1- Pruebo salida audio con Alsa abierto. No obtenemos sonido porque está silenciado. Desclicamos Sonido ok. (que recuerdos el winamp version linux)
Por cierto, lo de la calidad del micro no sé como la comprobo D. Jaime, pero la de los altavoces es atroz... que será lo malo, la salida o la entrada de audio....
2- Reinicio a ver si guarda configuración. Guardada, se oye el minino ronronear.
3- Probamos microfono. Entro en Recordmydesktop. Activo calidad de sonido a 100. Hago captura probando voz. No obtengo audio.
4- Abro Alsa y desactivo silenciar y subo volumen de Mic. No hay mejora.
5- Subo el volumen de Mic Boos. No obtengo sonido en micro.
6- Subo volumen Capture, no activo la función. Sin mejora.
7- Desactivo Grab. Sin mejora.
8- Subo volumen Digital. Sin mejora.
9- Desactivo Silenciar de Internal y subo volumen. Sin mejora.
10- Subo volumen de Internal2 y veo que ha desactivado sonido principal. Desclico silenciar y se escucha un acople de micro. Bajo volumen de internal2 a la mitad y hago prueba.
No obtengo mejoría pero tambien observo que el auto-Mute se ha activado en Alsa. Lo desactivo pero no hay mejora.
11- Desactivo Silenciar de beep. No hay mejora.
12- Reinicio.
13- Vuelvo a probar por si no guardaba cambios antes del reinicio y seguimos igual.
14- Al ver video, detecto que se ha bajado el volumen de mic Boos. Vuelvo a probar al subirlo pero nada.
Llegados a este punto, algo ha ido mal, porque ayer cuando di los pasos en el terminal, no lo hice bien y esta mañana al subirlo todo en Alsa, si me ha ido el micro.
15- Procedo a dar los pasos indicados. Ahora no me va el micro....
16- Tras intentarlo de varias maneras, vuelve a irme el audio tras activar Grab...
17- Vuelvo a testear en orden inverso tras volver a 0.
18- Desde 0, Abro alsa, desactivo el silencio Master y lo subo al maximo. Subo el capture. Ya tengo micro.
19- Probando Sala de Videoconferencias. Le cuesta un monton, CPU 100%. A los 5 min de espera seguimos igual... se oye con muchisimo lag y se corta al segundo. Imposible así.

**Comment by aosucas499** [comment]
Impresionante review compañero. 
Me está pasando igual con la tablet. He reparado todo excepto el micro, pero lo voy a dejar porque las llamadas van a saltos. Estos dispositivos no dan para videollamadas modernas. (No sé si en el pasado fueron funcionales las videollamadas) .
Por probar algo si quieres, antes de la llamada, busca una aplicación llamada "frecuencia cpu" o algo parecido, en el menú de herramientas de minino y selecciona la opción performance, a ver si así poniendo el microprocesador a tope te mejoran las llamadas. Porque el problema no es de micro o sonido, como bien apuntas es la CPU, no da para las apps de hoy día.

**Comment by chipygr** [comment]
Probado con alto rendimiento el hacer videoconferencia desde la Moodle y no es viable. Este dispositivo no nos sirve para esto, pero el sonido y el micro sin problemas para otras tareas.

**Comment by aosucas499** [comment]
Me lo temía. Gracias compañero.

**Comment by chipygr** [comment]
A vosotros

**Comment by jasvazquez** [comment]
Gracias @chipygr 

¿Hablamos de Minino recién instalado verdad? (me refiero a sin aplicar cambios de ningún tipo?)
Imagino que habrás grabado alguna cosilla con Audacity o similar y escuchado algún audio

Perdón por insistir, es sólo por dejar constancia y cerrar la tarea si lo consideráis oportuno 👍🏻

**Comment by chipygr** [comment]
Probado con el MWave, creo que se llama... Todo desde cero, solo toque en el alsa subi y baje volumen y activé y desactivé opciones... de hecho para hacerlo funcionar solo habia que subir el volumen del capture para que captara el micro, simple...

**Comment by jasvazquez** [comment]
Gracias Jaime.
Si os parece bien a todos, cierro la incidencia hasta "nueva orden" 👍🏻
