### ISSUE TITLE
Documentar cómo crear pendrive con la ISO de Minino-TDE

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#55]
Tras [conversación con Gema](https://t.me/c/1191811099/56135) en el grupo de Telegram, sería interesante dejar constancia en la wiki del proyecto sobre cómo crear un liveUSB a partir de la ISO.

No es necesario esmerarse mucho (corremos riesgo de cansar y/o aburrir al lector/a), bastará con unas pinceladas "en modo texto" (incluyendo las imágenes imprescindibles) o un vídeo corto (si encontramos uno explicando cómo usar Etcher o similar en internet y añadimos una explicación de dónde descargar la ISO) también serviría

**Comment by jasvazquez** [comment]
@jaimecarrascogarcia me tomo la licencia de asignarte la tarea (ya te irás acostumbrando e incluso estoy convencido que, más pronto que tarde, terminarás cogiendo tareas tú mismo 🤣 👍🏻 )

**Comment by jasvazquez** [comment]
Creo que _Etcher_ podría ser la solución más sencilla y eficiente (por ser multiplataforma y así no tenemos que distinguir si están usando Windows, Linux o Mac)

**Comment by jaimecarrascogarcia** [comment]
Estupendo, antes de subirla por aquí o las mandare para que la veais....!!! Me pongo a ello compis

**Comment by jasvazquez** [comment]
No temas... súbela directamente y ya se irá corrigiendo (no hagas trabajo en balde que el tiempo es un bien escaso 😉 )

**Comment by jasvazquez** [comment]
¿Te manejas con [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) (el lenguaje de marcas de la wiki)?

**Comment by jaimecarrascogarcia** [comment]
La verdad es que no, ¿para que sirve?

**Comment by jasvazquez** [comment]
Para dar formato a textos planos como este que escribimos en los comentarios de Github 😉

En el enlace que te he puesto (usando markdown 😇) tienes ejemplos de uso por si lo necesitas.

Cualquier duda, pregunta 👍🏻

**Comment by jaimecarrascogarcia** [comment]
# [CREAR LIVE ISO MININO.pdf](https://github.com/aosucas499/minino-TDE/files/5899914/CREAR.LIVE.ISO.MININO.pdf)
* Aquí os dejo un "breve tutorial"....ya me decís que os parece.
* Como ves compañero aquí practicando con MARKDOWN....jaja

**ESPERO VUESTRO FEEDBACK**

**Comment by chipygr** [comment]
Claro y al grano

**Comment by jasvazquez** [comment]
Pues no sé qué opinará el amigo @aosucas499 pero yo veo dos posibilidades:

1. Incluir en la wiki (justo delante de las instrucciones de instalación que existen actualmente) un enlace al pdf que has generado
2. Copiar y pegar el contenido del pdf a una página de la wiki

Ambas soluciones resolverían el problema de los compañeros/as menos "duchos" en la tarea pero creo que (con la primera opción) no vas a aprender a generar contenido en la wiki (ni a perfeccionar tu "markdown-fu" pequeño saltamontes 😏 🤣 )

**Comment by aosucas499** [comment]
Muy bien Jaime. Pero me ha puesto la piel de gallina ver las instrucciones de etcher para Windows. Eso va en contra de todo esto. Más teniendo en cuenta que existe la opción para linux. No te pediría corregirlo, pero por favor hazlo, me ha dolido ver una pantalla de Windows y un archivo .exe jajja

**Comment by jaimecarrascogarcia** [comment]
Ya estoy creando el punto 2 !!!!! A ver como sale......;)

**Comment by chipygr** [comment]
Jejeje, es cierto, con una opcion aprenden unos y con la otra aprenden igual pero a la vez el brincamontes sigue en su progresivo avance.

**Comment by jaimecarrascogarcia** [comment]
jajajaaj...pero tened en cuento que la mayoría usa Windows....quizás las 2 opciones en una pagina de WIKI???Una versión windows otra versión LINUX? estoy haciendo la wiki a ver si me "sale"

**Comment by aosucas499** [comment]
Tú también usabas Windows 🙄...en serio, sin Windows 😆

**Comment by jasvazquez** [comment]
Vaya @aosucas499, ¿¡¿al final vas a ser más talibán que yo?!? (que oficialmente me declaro "liberal" al respecto 🤣)

@jaimecarrascogarcia, no creo que sea necesario tanto esfuerzo y optaría por una solución intermedia: crear un epígrafe de "Problemas frecuentes" (o similar) al final del documento o donde lo estés explicando e incluir ahí la solución por si a alguien se le presenta la duda y no sabe cómo actuar 🤔

**Comment by jaimecarrascogarcia** [comment]
Aquí os dejo la "wiki" hecha, la he añadido en la página principal.....editar lo que veáis oportuno...

Puedo hacer otra "igual para Linux" pero primero decirme....

### https://github.com/aosucas499/minino-TDE/wiki/Creaci%C3%B3n-Live-ISO

**Comment by jasvazquez** [comment]
Sin saber qué opinará el "padre prior", yo daría por buena la documentación: entiendo que muchos compañeros (nos guste más o menos) usarán Windows y, los acostumbrados a Linux igual no lo necesitan (si se detectan casos, ya se añadirá la documentación oportuna)

Como recomendación "a futuro" trata de capturar las imágenes siempre con un tamaño similar: queda raro ver pequeñas imágenes insertadas en el texto o huecos por no coincidir con el resto. Son tonterías pero "peco" de "mijita" con estas cosas 🤣 😅 

![imagen](https://user-images.githubusercontent.com/604744/107383015-d600bd00-6af0-11eb-8640-625a46f3366f.png)

**Comment by aosucas499** [comment]
Yo si lo veis bien, por mi perfecto. Nos debemos al pueblo jajja

**Comment by jasvazquez** [comment]
Mira que "democrático" te nos estás volviendo 🤣 👍🏻 
@jaimecarrascogarcia, ¿te das el gustazo de cerrar tu mismo tu primera tarea? 😉

**Comment by jaimecarrascogarcia** [comment]
Buenas noches equipo!!!!! ¿de verdad puedo cerrar yo la tarea??? Pues nada!!!!!! ahi va....!!! jaja

PD: no me importaba hacerlo para linux...que conste...jaja

**Comment by jasvazquez** [comment]
Jaime se nos hace mayor: ya cierra tareas y todo 🤣

Enhorabuena, monstruo 👍🏻
