### ISSUE TITLE
Problema actualización fecha y hora del sistema

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#56]
Me comenta Antonio Cervantes por privado problemas con el script de actualización de la hora por NTP en Minino.

Tras descartar que se deba a falta de conexión a internet en los equipos en los que lo ha detectado me planteo si el problema pudiese deberse a la no visibilidad de acceder desde la Red Coporativa a los servidores de la hora

![image](https://user-images.githubusercontent.com/604744/106799445-8b4df380-665f-11eb-97a6-3b9b613776e6.png)

Dejo pendiente hacer comprobaciones (básicamente un ping) en el centro y recuerdo haber oído que existe el servicio en el servidor de contenidos del centro

**Comment by aosucas499** [comment]
Me pilla muy lejos, yo recuedo haberlo probado en Ubuntu y ver cómo se cambiaba la hora. Seguro que no ha cambiado el usuario a uno sin derechos root? Me ha pasado hoy que en educandOS funcionaba si lo hacía con mi usuario admin pero no con el usuario sin derechos y es el mismo script. 
Recuerdo que compañeros en el grupo de telegram dijeron que se le había solucionado el problema de los chuck norris sin pila, y yo tengo varios que miraré para ver si cargan la hora.

**Comment by aosucas499** [comment]
Este es el script:

# Establece la hora al inicio
# ---

function ntp-fix {
    sudo timedatectl set-timezone Europe/Madrid
    sudo cp ./ntp/fix-ntp /usr/bin
    sudo chmod +x /usr/bin/fix-ntp
    sudo chown root:root ./ntp/zz-fix-ntp
    sudo chmod 0440 ./ntp/zz-fix-ntp
    sudo cp ./ntp/zz-fix-ntp /etc/sudoers.d/ 
    sudo cp ./ntp/fix-ntp.desktop /etc/xdg/autostart/
	echo -e "${ROJO}Fix-ntp time instalado${NORMAL}"
}

La única diferencia en este es que pusimos la primera línea para que se estableciese la hora de aquí. El método de ejecutarlo en cada inicio es el de poner el archivo . Desktop en la ruta /etc/xdg/autostart, que ayer me daba problemas en la tablet. Investigo un poco pero ya te digo que me da que en cada inicio se ponía la hora bien hasta en aquellos con pila gastada que creían que estábamos en la época de John Lennon.

**Comment by jasvazquez** [comment]
Buen apunte el de los permisos pero creo más acertado meterlo como "demonio" o bien darle permisos para que cualquiera pueda ejecutarlo como si lo estuviese lanzando un usuario administrador y/o con permisos (el SUID bit en Linux si no recuerdo mal)

**Comment by aosucas499** [comment]
Primera imagen se ve la hora actual y cambio la hora a otra.
![IMG_20210203_223551](https://user-images.githubusercontent.com/72696244/106812927-a2e1a800-6670-11eb-8808-91b236aedc30.jpg)
Segunda imagen, ejecuto el comando que ejecuta en cada inicio minino y se ejecuta sin problema y pone la hora actual. 
![IMG_20210203_223800](https://user-images.githubusercontent.com/72696244/106813034-c73d8480-6670-11eb-8fb6-18e3812abb8e.jpg)

**Comment by aosucas499** [comment]
> Buen apunte el de los permisos pero creo más acertado meterlo como "demonio" o bien darle permisos para que cualquiera pueda ejecutarlo como si lo estuviese lanzando un usuario administrador y/o con permisos (el SUID bit en Linux si no recuerdo mal)

No sé si vale, pero en educandOS lo he solucionado para que lo pueda ejecutar cualquier usuario sin permisos root añadiendo /bin/date al archivo /etc/sudoers.d/...

**Comment by profeIAP** [comment]
Compruebo igualmente en mi centro que se puede actualizar la fecha usando los servidores de NTP indicados en Minino

![image](https://user-images.githubusercontent.com/16881846/106879693-c4c44480-66db-11eb-9b21-ea2ef7410630.png)

**Comment by jasvazquez** [comment]
Compruebo igualmente en mi centro que se puede actualizar la fecha usando los servidores de NTP indicados en Minino

![image](https://user-images.githubusercontent.com/16881846/106879693-c4c44480-66db-11eb-9b21-ea2ef7410630.png)

**Comment by aopen03** [comment]
Hola a todos, 
soy Antonio Cervantes Alarcón, profesor de Informática (FP) del IES Al-Ándalus de Almería. Decir que muchísimas gracias por vuestro trabajo, es muy emocionante!  

Ya veo que se ha solucionado el problema de la fecha. 

Saludos

**Comment by jasvazquez** [comment]
Hola Antonio

gracias por tus palabras (sobre todo viniendo de un compañero "de armas" que trabaja en un centro "hermano" al mío y al que le guardo un especial cariño: mi hermano sacó las oposiciones en vuestro centro 😉 )

Con tu comentario (y ahora que caigo en que eres quien se puso en contacto conmigo por Telegram 🤣 🙈 ) entiendo que puedo dar por cerrada la tarea 🎉 👍🏻 

Gracias por reportar tanto el problema como confirmar la solución. Con compañeros como tú esto va cada día un poco mejor 💪🏻
