### ISSUE TITLE
Incluir programas CAD en minino

### ISSUE THREAD

**Issue by FernandoRodero** [aosucas499/minino-TDE#57]
Hola, ¿Es posible incluir algún programa de dibujo técnico tipo libreCad en minino? ¿Y software para programar arduino?

**Comment by jasvazquez** [comment]
Hola Fernando, entiendo que has mirado en Synaptic, ¿no hay ningún programa que se acerque a lo que necesitáis?

**Comment by FernandoRodero** [comment]
Buenos días, ¿Qué es Synaptic?  y ¿Cómo puedo mirar ahí?
gracias

**Comment by FernandoRodero** [comment]
Perdona, ya he mirado y no veo estas aplicaciones, aunque se que están libres para linux.

**Comment by jasvazquez** [comment]
Fernando, ¿te animarías a escribir en una terminal de Minino un `sudo apt install librecad`?

**Comment by FernandoRodero** [comment]
Me dice que no su pudieron instalar algunos paquetes. ... Los siguientes paquetes tienen dependencias incumplidas:
Librecad: depende: Libmuparser2 (>= 2.1.0) pero no es instalable. ... usted ha retenido paquetes rotos.

**Comment by jasvazquez** [comment]
Anoto mirarlo este fin de semana Fernando.
Gracias por intentarlo 👍🏻

**Comment by tecnojose** [comment]
Buenas, en primer lugar agradeceros el trabajazo y la generosidad, a mí se me ha instalado bien LibreCAd.

**Comment by jasvazquez** [comment]
Gracias @tecnojose por tu aportación

He hecho la prueba y, como a ti, me funciona correctamente la instalación.
Posiblemente @FernandoRodero no tenga actualizados los repositorios pero se resuelve fácilmente lanzando

```
sudo apt update
sudo apt install librecad
```

para poder disfrutar de libreCad en Minino-TDE 💪🏻 👍🏻 

![imagen](https://user-images.githubusercontent.com/604744/107852904-85040800-6e13-11eb-9885-ae38350672cd.png)

**Comment by tecnojose** [comment]
Incluso se puede instalar el FreeCad. Que es más potente aún..

**Comment by jasvazquez** [comment]
Espectacular. Gracias, monstruo 👍🏻

**Comment by FernandoRodero** [comment]
Buenos días, efectivamente al actualizar he podido instalar LibreCad, FreeCad y Arduino. Me ha quedado pendiente S4A, pero seguramente descargando el instalador pueda hacerlo.
Muchas gracias. Un saludo.

**Comment by jasvazquez** [comment]
Genial, gracias Fernando

Si da problemas S4A avisa y le echamos un vistazo 👍🏻
