### ISSUE TITLE
Activar sonido por defecto

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#6]
Actualmente está desactivado por defecto al iniciar el sistema

**Comment by aosucas499** [comment]
![400120300910_76748](https://user-images.githubusercontent.com/72696244/101207343-c9836280-3670-11eb-8f1f-5682a8782ba0.jpg)

Mensaje del compañero que tiene el problema:

>Me sale eso silenciado y cuando lo quito se escucha ya bien.
>El problema es que cada vez que reinicio el pc se vuelve a silenciar.

> Este es un samsung verde de 2012. He probado en otro y me da el mismo problema.
> En un toshiba n200 no tengo ese problema

Probaremos en ese modelo, en virtualbox sale el volumen del "master M" silenciado pero mejor resolverlo en el dispositivo en cuestión.

**Comment by aosucas499** [comment]
![1607111275025780281480352981511](https://user-images.githubusercontent.com/72696244/101208182-0dc33280-3672-11eb-9f50-b1bf4d1a7dd6.jpg)
Modelo Samsung N100SP

**Comment by jasvazquez** [comment]
Desgraciadamente, no tengo equipos de esos en mi centro para poder hacer pruebas.

**Comment by jasvazquez** [comment]
Esta tarea empieza a "quemarme".

Para asentar un "flujo de trabajo" común, comentar que lo habitual en metodologías ágiles (de las que ya irás comprobando que soy un "adepto") es que las correcciones (etiqueta FIX en nuestro caso) deben ser acometidas antes que ninguna otra (no están permitidos los fallos wink y, si se tienen, deben corregirse a la mayor brevedad posible)

¿Cómo podemos meterle mano? ¿Quién podría hacer las pruebas que necesitamos?

**Comment by aosucas499** [comment]
Esta me ocupo yo estos días que tengo aquí un Samsung en casa.

**Comment by jasvazquez** [comment]
Genial, de todos modos igual le dedico un rato y miro si se puede hacer mediante script (y así no depende de que tengamos que acordarnos, o no, de hacerlo) 👍🏻

**Comment by jasvazquez** [comment]
Parece sencillo poder implementarlo (otra cosa es que pueden producirse fallos según el modelo de ordenador que deberíamos gestionar)

![image](https://user-images.githubusercontent.com/604744/101340274-c7dbb980-387f-11eb-9d08-2f61056a0398.png)

Para listar los controles que podemos manejar podemos hacer uso de `amixer -c 0 controls`

**NOTA:** el uso de `-c 0` es para usar el primer dispositivo (no suele hacer falta pero me he encontrado algún problema en mi equipo y he querido matizarlo)

**Comment by aosucas499** [comment]
Esto lo voy a solucionar gráficamente, pues fue en este modelo en el que lo bajé el sonido para los alumnos, es el que usan mis alumnos. Lo activo y así genero una ISO con eso solucionado que solo afecta a este netbook y con lo que hemos añadido hasta ahora. De paso genero un enlace definitivo minino-tde.iso

**Comment by aosucas499** [comment]
Tras investigar este finde con el modelo samsung en casa he descubierto que es un bug. Un bug que solo afecta a ese modelo por la tarjeta de sonido "realtek alc269vc". El sonido suena como dijo el compañero si le subes el volumen a "headphones" y esto no debería ocurrir ya que ese volumen debe mantenerse bajado e intercambiarse con el de "speaker" cuando se le conecta unos auriculares. Con auriculares funciona bien. Por ahora lo dejamos así, ya que para los estudiantes no suele hacer falta el sonido sino es con auriculares y aunque lo he solucionado para este modelo con [la primera respuesta de esta página de AskUbuntu](https://askubuntu.com/a/1235286) si lo aplicamos al proyecto, como dijiste anteriormente, seguro que estropeamos la configuración de los demás. Buscaremos una solución tranquilamente.

**Comment by jasvazquez** [comment]
Me tomo la libertad de editar el comentario que has hecho para apuntar directamente a la respuesta que mencionas 👍🏻 

¿Damos por finalizada la tarea o la cambiamos a IDEA? (algo a hacer en un futuro si se considera oportuno)

**Comment by aosucas499** [comment]
Como veas, sin duda es uno de los dispositivos en los que más se va a instalar junto al chuck norris, luego tenemos que intentar solucionarlo aunque sea un script al inicio que haga un reconocimiento de la tarjeta de sonido y si la detecta aplique el fix. Algo que hacer aunque sin prisa. TODO, IDEA, lo que veas...

**Comment by jasvazquez** [comment]
Vale, vamos hablando, quizás TODO sea más acertado (gracias por sugerirlo)

Necesitaríamos el ID de la tarjeta de sonido para echar un vistazo a dicho script (con un simple condicional y [lo que indiqué más arriba](https://github.com/aosucas499/minino-TDE/issues/6#issuecomment-739830466) debería ser más que suficiente)

Déjame que  haga algunas pruebas y vamos viendo cómo meterle mano 👍🏻

**Comment by aosucas499** [comment]
![IMG_20201208_210810](https://user-images.githubusercontent.com/72696244/101536056-ca323680-3999-11eb-83f7-0dc6e5418532.jpg)

**Comment by aosucas499** [comment]
Creo recordar un mensaje de Telegram tuyo en el que decías que te habías traído este dispositivo para las navidades. Lo has mirado, en caso contrario genero la ISO, ¿no?

**Comment by jasvazquez** [comment]
En realidad me he traído un Toshiba NB500, Andrés (de los Samsung que indicas en este hilo nunca hemos tenido ninguno físicamente en el centro)

¿Lanzamos la ISO (que entiendo que ya debería ir tocando) a pesar de #31? 🤔

**Comment by jasvazquez** [comment]
Bueno, como comenté ayer en el grupo de Telegram, he encontrado una solución al problema aunque sería interesante (por evitar fallos en otros equipos) limitarla a la tarjeta de sonido del NM10/ICH7 (que, al igual que el Samsung N100SP que indicas más arriba, es la que tiene el Toshiba NB500)

Tengo código para detectar dicha tarjeta pero no sé si sería posible aplicarlo con los famosos scripts post-install o método similar.

La idea es ejecutarlo una sola vez de modo que, si estamos ante uno de los equipos problemáticos, aplicar el parche y, en caso contrario, no hacer nada por no cargarnos cosas que funcionan y no tenemos equipos para probar 🤔

**Comment by aosucas499** [comment]
Eres un crack. Por curiosidad, ¿es esta?:
add "blacklist i82975x_edac" to /etc/modprobe.d/alsa-base-blacklist.conf
sudo modprobe -r i82975x_edac
sudo alsa force-reload

Yo veo la mejor opción esa que comentas, con el post-script. La otra opción sería actualizar kernel, pero por lo que veo no es algo que se solucione en kernels más modernos. Otra opción también es añadirlo en customize minino, pero no es tan buena o eficaz como la que propones, así que lo haremos así, pero me da que tendremos que investigar refracta installer más a fondo.
[#49](https://github.com/aosucas499/minino-TDE/issues/49#issuecomment-766347008)

**Comment by jasvazquez** [comment]
Si hay que estudiar... se estudia y, de paso aprovechamos para acometer la tarea #49.

Sólo espero que, con los distintos modos de instalar que existen, se aplique siempre el parche que propongo 😅

Por cierto, esa solución tampoco era la apropiada. En realidad he hecho un parche (de ahí mis reticencias y dudas de si afectará a otros y quiera limitar la posible "onda expansiva"): he optado por anular la configuración del analog-speaker para evitar que lo seleccione por defecto cuando se quita el auricular del puerto jack 😇

¿Que por defecto esté en "mute" el 'headphone" ha sido por un fallo en esos micros (ya te compartí código indicando cómo activarlo desde cli) o que lo desactivaste antes de generar la ISO a drede? 🤔

**Comment by aosucas499** [comment]
Tendremos que estudiar los diferente métodos de instalación de minino  (/usr/local/bin/minino-installer-selector) para saber siempre se aplica el post-install, en teoría si todos los métodos usan refracta-installer, debería de ser así. 

Si lo desactivé antes de generar la ISO fue algo totalmente incosciente. Antes si lo hacía por mis estudiantes, pero desde que tenemos la versión TDE no. Lo investigamos y cuando lo tengamos todo hacemos otra ISO bien hecha con el audio a tope!!!

**Comment by jasvazquez** [comment]
Teniendo en cuenta el grado de incertidumbre y el coste que va a tener en investigación, me estoy planteando (aunque no es la solución que prefiero) incluirlo en `customize-minino` buscando: 
1. sacar una solución relativamente "ágil" (Jaime está deseando contar con ella) 
2. permitir que otros compañer@s puedan probar (acá hacer de "conejillos" de  indias) cómo les va en sus equipos

De esta forma (con customize se puede activar/desactivar) podemos pedir que algunos prueben cómo se comporta en el resto de equipos y ganamos tiempo para investigar _Refracta_ 🤔

**Comment by jaimecarrascogarcia** [comment]
Jaime está deseando, y tanto....!!!! 
Creo que podrías introducirlo como dices en customize-minino e ir probando como funciona....me ofrezco para ser conejillo de india en todo lo que propongais....@jasvazquez @aosucas499

**Comment by aosucas499** [comment]
Pues genial idea. Probamos y sacamos tiempo para mejorar el instalador. Siempre tienes ideas funcionales y prácticas. Así de paso vemos cómo funciona antes de incluirlo y se queda listo para cuando tengamos instalador mejorado. Es genial lo de sacar tiempo mientras se prueba ya que estamos sin tiempo y con muchas ideas.

**Comment by jasvazquez** [comment]
Vaya, parece que el amigo @jaimecarrascogarcia tenía la oreja "puesta" 🤣 👍🏻  (de lo cual  me alegro)

@aosucas499 soy amante de las metodologías ágiles (este año estoy emperrado en enseñar SCRUM y Kanban a mi alumnado de bachillerato, no descartes que termine aplicándolo a Minino-TDE 🤣 😇 ) y el principio KISS (amén de, como informático, haberme llevado algún que otro palo y haber aprendido cuál es el camino más rápido o menos arriesgado 😅 ) así que se puede decir que es "filosofía de vida".

Me alegra que os resulte interesante la posibilidad...me pongo a ello (total, sólo estaba mirando cómo van los _postscripts_ de Refracta 😉

**Comment by aosucas499** [comment]
Genial, yo voy a intentar a instalar refracta snapshot, la versión que traía y no la versión nueva que puse, a ver si así funciona mejor el installer. Me da que al ponerle la versión nueva la otra vez, puede ser el motivo de los últimos fallos.

**Comment by jasvazquez** [comment]
Otra gente habla de [RemasterSys](https://mejorsoftware.info/tools/linux-respin) a la hora de generar ISOs a partir de cambios en un sistema

**Comment by aosucas499** [comment]
Quizás me falle la memoria, pero refracta estaba basado en la antigua remastersys. Yo quería probar también [pinguybuilder](https://sourceforge.net/projects/pinguy-os/files/ISO_Builder/), pero no sé si iba en debian o solo Ubuntu.
Aquí un resumen de opciones también: [tools](https://www.linuxadictos.com/crear-distribucion-linux.html)

**Comment by jasvazquez** [comment]
Creo la tarea #50 para que no olvidemos convertirlo a script de Refracta
