### ISSUE TITLE
HGR-Sigala

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/minino-TDE#60]
Es bastante interesante incluir las aplicaciones de HGR en minino. La situación que yo me planteo es utilizar educandos o ubuntu/mint en el pc del docente, instalado con[ docker](https://github.com/aosucas499/hgr-dre), ejecutando el hgr-server, que funciona perfectamente y en las tablets/ultraportátiles con minino la versión cliente de la versión .deb de guadalinex.

Para añadir algo a esta tarea, aquí están los repos que usé en el docker y que podemos probar a instalar añadiendo repos en minino:

Versión HGR antigua [guadalinex/edu](http://centros.edu.guadalinex.org/Edu/catcornerdda/pool/main/c/cga-hga/): da fallos en el docker, se dejó de usar y se ha actualizado con [esta](http://centros.edu.guadalinex.org/Edu/catcorner/pool/main/c/cga-hga/)

Versión HGR que me funcionó en el docker y que proviene de la versión [guadalinex next/slim](http://centros.edu.guadalinex.org/Edu/fenix/pool/main/c/cga-hga/).

Link al [script-guadalinex-next-slim](https://raw.githubusercontent.com/aosucas499/hgr-dre/main/hgr-minino-next) y al  [script-guadalinex-guadalinex-edu](https://raw.githubusercontent.com/aosucas499/hgr-dre/main/hgr-minino) que tenía de pruebas probando en minino y aún sin terminar.

**Comment by jasvazquez** [comment]
Me parece una buena opción ¿incluimos el cliente de serie o lo ponemos como una opción en customize-minino?

**Comment by jasvazquez** [comment]
@aosucas499 ¿Sería factible contar con HGR-server para poder hacer pruebas?

Si te parece, podemos poner esta tarea como IDEA (que ya sabes cómo me "estresa" ver tareas TODO y FIX por considerarlas de "acción inmediata") mientras que no disponemos del servidor y, tan pronto puedas tenerlo listo, acometemos la implementación de un posible cliente HGR en Minino 🤔

**Comment by aosucas499** [comment]
> Me parece una buena opción ¿incluimos el cliente de serie o lo ponemos como una opción en customize-minino?

Si lo conseguimos de serie. Se usa mucho en las clases esta aplicación.

**Comment by jasvazquez** [comment]
Sea... yo no la he usado nunca pero entiendo que en Primaria puede ser muy útil 👍🏻 
¿Acepta el pasarla a IDEA o tiene ya resuelto el problema del HGR-server?

**Comment by aosucas499** [comment]
Vale

> @aosucas499 ¿Sería factible contar con HGR-server para poder hacer pruebas?
> 
> Si te parece, podemos poner esta tarea como IDEA (que ya sabes cómo me "estresa" ver tareas TODO y FIX por considerarlas de "acción inmediata") mientras que no disponemos del servidor y, tan pronto puedas tenerlo listo, acometemos la implementación de un posible cliente HGR en Minino 🤔

Vale, cambia etiqueta, ya que es un proceso difícil. El servidor y el cliente se instalan en el mismo proceso. Si funciona uno funciona el otro. En cuanto tenga tiempo me pongo a ello.

**Comment by jasvazquez** [comment]
Descuida... las Vexia son muchísimo más importantes. 
Esto no deja de ser un "capricho" 🤣 😇

**Comment by aosucas499** [comment]
El hgr-server no me da problemas. El problema es corregir las dependencias de guadalinex al instalar en minino. No me expliqué bien jajaj

**Comment by jasvazquez** [comment]
O yo que ando espeso y no sé de qué va la película 😅  (por no haberme metido nunca en el mundillo HGR)
¿Se podría dar "por bueno" lograr instalar el paquete del cliente HGR en Minino resolviendo los problemas de dependencias? 🤔

**Comment by aosucas499** [comment]
En verdad es una aplicación hecha en python. En minino voy a instalar los paquetes deb o desde el repo de guadalinex. Cuando lo instalas, los dos programas van dentro, simplemente los lanzas diferente, con su lanzador. En docker no falla, simplemente tengo que testear una cosilla. Pero en minino que es de la "epoca" de Guadalinex, simplemente resolvemos alguna dependencia (si se puede) y lo instalamos tal cual del deb. Una vez instalado, el cliente sale siempre en la barra de tareas y si se necesita lanzar el server, que suele hacerlo el maestro/a, se busca en el menú de aplicaciones.

**Comment by aosucas499** [comment]
> O yo que ando espeso y no sé de qué va la película 😅 (por no haberme metido nunca en el mundillo HGR)
> ¿Se podría dar "por bueno" lograr instalar el paquete del cliente HGR en Minino resolviendo los problemas de dependencias? 🤔

Claro. Por bueno y por genial, es una de las apps más queridas del profesorado y que más echan en falta cuando actualizan o cambian de sistema operativo.

**Comment by jasvazquez** [comment]
Perfecto, ya tengo una visión más amplia del problema.

Miraré esas dependencias y veo qué ser podría hacer.

Igual mejor empezar con el más próximo en el tiempo a Debian Jessie. Lo iremos viendo

**Comment by jasvazquez** [comment]
Buenas tardes don @aosucas499 ¿podría estar funcionando el "cliente HGR"? 😉 

![image](https://user-images.githubusercontent.com/604744/107883050-d6cc9100-6eec-11eb-97a4-c42f53b288fd.png)

**Comment by aosucas499** [comment]
Ya te digo crack jajaa

**Comment by aosucas499** [comment]
Te han servido mis scripts a medio terminar?

**Comment by jasvazquez** [comment]
Bueno, si soy capaz de reproducir el "logro" aceptaré el cumplido porque he liado la "del tigre".

En realidad me he puesto a resolver dependencias "a lo loco" y, con el toque final de _avahi-daemon_ se ha obrado el milagro.

Voy a intentar reproducir el proceso (crucemos los dedos), en una versión previa de la máquina virtual, siguiendo las anotaciones del comando `history`

Luego te cuento 👍🏻

**Comment by aosucas499** [comment]
Genial!!! Menudo curro me has ahorrado, y así lo puedo meter en la tablet que está ya para probar

**Comment by jasvazquez** [comment]
Pelotazo... parece que el fin de semana (nuevamente) confinado va a cundir.
Como levanten el veto no me vuelves a ver el pelo de ganas que le tengo 🤣 😇

**Comment by aosucas499** [comment]
Jajajaja igual estoy yo. Como levanten nos vamos de cañas jaja

**Comment by jasvazquez** [comment]
Bueno, creo que tenemos bien merecida esa "cerveza" 😉 👍🏻 

![imagen](https://user-images.githubusercontent.com/604744/107885034-35e3d300-6ef8-11eb-8211-255011dff3de.png)

¿Al final quedamos que HGR_Sigala iba de serie en Minino-TDE o lo metemos como opción en _customize-minino_? 😏

**Comment by aosucas499** [comment]
Eres un crack. La merecemos sin duda jajaja. A mí me gustaría de serie.

**Comment by jasvazquez** [comment]
Tuyo es y "minino" no... de serie lo incluyo 👍🏻

**Comment by aosucas499** [comment]
Jajaja lo que te gustan los juegos de palabras...minino solamente no, tuyo, mío y de todos

**Comment by aosucas499** [comment]
Veo que has usado la versión de guadalinex next/slim, perfecto. Voy a probarlo en la tablet que estaba a punto de crear un clon para dárselo a Jaime y que me haga testing. Ya de paso lo pruebo tanto en servidor como cliente con otro pc y con el docker. Mil gracias compañero, me has ahorrado tela de curro.

**Comment by jasvazquez** [comment]
Me alegra saber que te he liberado tiempo para otros "menesteres" Andrés.

Quedo a la espera de esas pruebas porque me he limitado a lograr que instale y arranque... todavía me quedan dudas respecto a que todo sea correcto 😉 👍🏻

**Comment by aosucas499** [comment]
He podido probarlo y aunque abre el cliente, daba mala sensación. El server no abría. 
He mirado el código y recuerdo de mi docker que es mejor tener muchos de los paquetes del mismo guadalinex y no de minino. La suerte es que podemos añadirlos sin problema porque esta versión basada en ubuntu 16, su paquetería es más moderna que la de minino.
Por lo pronto he añadido todas las dependencias del server/paquete "ejabberd" y ya al menos abre el server, aunque no se puede crear el grupo para compartir ficheros. El fallo de crear carpeta en el sistema se ha corregido y  que abra el server. Lanzando el server desde la terminal y al crear el grupo da fallo de python, posiblemente tengamos que añadir a mano los paquetes de python e incluso webdav de guadalinex. 
Otro día otro ratico.
Por lo pronto he añadido [tu script](https://github.com/aosucas499/minino-TDE/blob/main/tools/hgr-minino-andalinux) y el[ mío](https://github.com/aosucas499/minino-TDE/blob/main/tools/hgr-minino-next) modificado del tuyo en la carpeta "tools" para trabajar con ellos hasta que lo tengamos funcional.

**Comment by aosucas499** [comment]
El error que salta justo al pulsar "crear grupo" en el hgr-server:

![VirtualBox_minino TDE_16_02_2021_20_42_34](https://user-images.githubusercontent.com/72696244/108113320-ac6b0700-7097-11eb-93c8-9438baa3d60f.png)

Me da que python, quizás se utilizaron algunas librerías más nuevas en guadalinex next.

**Comment by aosucas499** [comment]
![VirtualBox_minino TDE_16_02_2021_20_42_34](https://user-images.githubusercontent.com/72696244/108113546-f227cf80-7097-11eb-9413-9a70cf697f79.png)
 Fallo que da el hgr-server al pulsar en el icono de "crear grupo". No soy un experto pero quizás las librerías python de minino no son tan nuevas como las de guadalinex next y el programador usó alguna librería o función de la versión moderna de alguno de estos paquetes:

python-avahi python-qt4 python-qt4-dbus python-netifaces python-sleekxmpp python-webdav

**Comment by jasvazquez** [comment]
@aosucas499 ¿si utilizas el server en otro equipo (que no sea Minino) es factible conectarse a él usando el cliente que hemos logrado abrir?

La idea que persigo es la siguiente: dividir el problema en dos de modo que podamos cerrar la parte del cliente (que es la que entiendo se debe gestionar en equipos con menos recursos) y confiar (de momento y hasta que encontremos la solución definitiva) en que el profesor usará equipos algo mejor "dotados" 🤔

**Comment by aosucas499** [comment]
Era una opción que barajaba, me encanta que pensemos igual jajaja. En cuanto tenga hoy un rato lo pruebo. Voy a poner en minino el cliente y en un educandOS mi docker con el server. Te cuento crack...

**Comment by jasvazquez** [comment]
Bueno, creo que vamos cogiendo una "filosofía común" para el proyeto: te recuerdo que al principio las decisiones no eran tan "fluidas" 😉 🤣 Menos mal que hemos encontrado un punto "de equilibrio" 👍🏻 

Como punto extra sería interesante comprobar si es funcional con los servidores que vienen "de facto" en los Guadalinex anteriores (así podríamos redirigir a los compañeros tanto a tu educAndOS unofficial como a cualquier otros Guadalinex que puedan tener en el aula)

**Comment by aosucas499** [comment]
Veo que no confías en mi docker jajajaja. La función del docker es funcionar en sistemas modernos, ubuntu, mint, educaandos...vistas al futuro y para usar en un pc moderno en la pizarra. Lo probamos también con una versión de guadalinex next, hay que probar todo.

**Comment by jasvazquez** [comment]
Hombre no, tampoco es eso. Entiendo y valoro su utilidad y estoy convencido que funciona perfectamente pero quiero centrarme en lo más probable de encontrar en un centro educativo: Guadalinex 😉

**Comment by aosucas499** [comment]
Lo tengo aún en fase testing.

 Al turrón, no funciona el cliente. No aparecen en él ninguno de los servers que he abierto en una tablet con guadalinex edu (ni la versión sigala antigua, ni tras actualizar a la versión hga como la de guadalinex next), ni docker en educaandos. No funciona, mi experiencia en esta app a la que tanto tiempo le he dedicado es que hay que utilizar paquetes del mismo guadalinex next, todos los posibles, es muy maniática en las funciones python y en las versiones de los paquetes para funcionar.

**Comment by jasvazquez** [comment]
¿Y con máquinas virtuales de Guadalinex Next (una para servidor y otra para el cliente) funciona?

Lo digo porque el WebDAV (y su uso dentro del centro educativo con el servidor de contenidos) me hace desconfiar 🤔

**Comment by jasvazquez** [comment]
Sí que va a costar... sí

![imagen](https://user-images.githubusercontent.com/604744/108400753-e49b5280-721b-11eb-8bc4-7212a190c324.png)

**Comment by jasvazquez** [comment]
Oooohh... con Guadalinex Next (en máquinas virtuales) funciona perfectamente

![imagen](https://user-images.githubusercontent.com/604744/108403972-98521180-721f-11eb-9bdd-1e63ad98109b.png)

Eso sí: me obliga a arrancar el servidor con permisos de administración 😮

**Comment by jasvazquez** [comment]
Lo cual me ha dado una "pista"

![imagen](https://user-images.githubusercontent.com/604744/108404521-42319e00-7220-11eb-9179-eca81ea5a8e0.png)

Pero, fino fino, no termina de ir... (no le gusta ningún fichero que intento compartir con el "maestro" 😅 )

![imagen](https://user-images.githubusercontent.com/604744/108405115-fdf2cd80-7220-11eb-829c-92ebf4992bc1.png)

**Comment by jasvazquez** [comment]
![imagen](https://user-images.githubusercontent.com/604744/108405264-2975b800-7221-11eb-8a6c-638af5dbeff7.png)

**Comment by jasvazquez** [comment]
El "maestro" comparte sin problemas

![imagen](https://user-images.githubusercontent.com/604744/108405706-b3be1c00-7221-11eb-890a-9d0221f620fa.png)

**Comment by aosucas499** [comment]
Es el mismo problema que tenía con mi docker. Compartir del cliente al servidor arrastrando en la pestaña, no iba. Y ese método de compartir utilizaba WebDAV. Pensé, a unas malas en los pc's modernos con Ubuntu/educandOs, uso el docker que el server funciona todo y en los ultraportátiles, el cliente con minino.
Sin embargo igual que me cuentas el server comparte sin problema.
Has utilizado tu script de update-minino o le has añadido las modificaciones del paquete que introduje?
Me llama mucho la atención, que ocurra lo mismo que en el docker que tiene todos los paquetes necesarios y exactos de guadalinex next... qué opinas? Me he quedado desconcertado.

**Comment by aosucas499** [comment]
Será algo de Python relacionado con el entorno gráfico al usar el arrastrar para compartir? Yo recuerdo que si lo lanzaba en terminal y compartía, podía ver el fallo en el terminal. Pensé mucho tiempo en el dbus, pero lo solucioné y di con el comando para compartir el dbus de la máquina en docker y así funcionó la pizarra Smartboard qur era más chungo aún...me deja desconcertado, a ver si tú lo ves que le pegas a Python

**Comment by jasvazquez** [comment]
El fallo en la terminal [lo he puesto aquí](https://github.com/aosucas499/minino-TDE/issues/60#issuecomment-781554913) 

Ya deberías ir viendo que soy "tela de cabezón" o, lo que es lo mismo: sigo con el script de _update-minino_ con un leve cambio.

Quiero seguir explorando esa senda, de momento no es "angosta" y sigo viendo "camino" que recorrer. En el momento que se vuelva farragoso, investigaré la solución que gentilmente has ofrecido 😉 😅

**Comment by jasvazquez** [comment]
En realidad el problema parece de "encoding" 🤔

**Comment by aosucas499** [comment]
Lo que tu veas maestro, es que el otro día sin los cambios daba fallo incluso de crear la carpeta de compartir. Por si el pequeño cambio de instalar el paquete de gualinex te ayuda. 
Igualmente haz como hasta ahora y me tienes al tanto, que a ese programa le he dedicado mil horas, aunque en el código Python estoy pez

**Comment by aosucas499** [comment]
> En realidad el problema parece de "encoding" 🤔

Y eso?

**Comment by jasvazquez** [comment]
![imagen](https://user-images.githubusercontent.com/604744/108408967-f4b82f80-7225-11eb-8c13-7390a599b765.png)

**Comment by jasvazquez** [comment]
Algo hemos avanzado pero tanto como "correcto", no me atrevería a decir yo tanto 🤣 

![imagen](https://user-images.githubusercontent.com/604744/108411953-82494e80-7229-11eb-9062-96302d8b2836.png)

**Comment by jasvazquez** [comment]
Uuummm, creo que me he ganado la cena hoy 🤣 

![imagen](https://user-images.githubusercontent.com/604744/108412361-12879380-722a-11eb-84c9-84c73b1b1c13.png)

**Comment by aosucas499** [comment]
Qué crack eres jajajjaja, ya lo tienes!!!

**Comment by jasvazquez** [comment]
Gracias Andrés 😅

Para "nota" queda el poder ver las pantallas de las "criaturitas" (que ahora mismo no sé ni por dónde empezar 🤣 ... porque no veo errores por ningún sitio que me den alguna pista) pero con la posibilidad de compartir archivos hemos ganado una importante funcionalidad 👍🏻

**Comment by aosucas499** [comment]
Lo de las pantallas yo creo que ni iba en su entorno natural...yo creo que es una opción que funcionaba en sigala y aquí ni con Guadalinex funcionaba. Vamos a mí lo que me demandan es el envíar archivos, que el profe pueda recoger el trabajo diario en su pc, con eso yo veo el proyecto terminado.

**Comment by jasvazquez** [comment]
Creo que sí iba (y que se te ha escapado el [detalle en esta foto](https://github.com/aosucas499/minino-TDE/issues/60#issuecomment-781548758) 😉)

**Comment by aosucas499** [comment]
La he visto, he mirado todo lo que has puesto con ojos de lince. Es que me queda en la memoria residual que me decían los profes que no se podía en Guadalinex next...pero vamos no me hagas mucho caso. Pues supongo que tiene que ver con el vlc que instala, y sobretodo con el xvncserver no? Estoy deseando que subas el fix para probar a compartir, me daba úlcera cada vez que decía que no se podía compartir el fichero.

**Comment by jasvazquez** [comment]
Tengo (por hoy) "orden de alejamiento" del ordenador 😅

Mañana sin falta lo subo, descuida 👍🏻

**Comment by aosucas499** [comment]
Haces bien...yo hoy me comprometí a no encenderlo y por eso te contesto con el móvil. Eres un crack compañero, lo has solucionado en un rato jajakka

**Comment by aosucas499** [comment]
También he estado pensando y quería saber tu opinión sobre si pasar esta app a optativa (customize-minino). Para mi centro el uso va a ser seguro, pero dudaba en si esta app que tiene que ralentizar seguramente el sistema un poquito, al usar el server ejabber siempre al inicio, si deberíamos replantearnos el pasarla a opción. Pensaba en si habrá centros donde esto no lo usen, etc... Si preguntar a los compañeros, o si tienes una de tus clarificadoras razones para esta duda. 

Con respecto a uno de los comentarios que has hecho de que el server te pedía derechos admin, creo recordar que el mismo deb de cga-hga instalaba los permisos en /etc/sudoers  o fichero en carpeta /etc/sudoers.d/ para que el usuario ejecutara este y otros programas relacionados con sudo sin tener derechos (compartición de pantallas, etc...) No sé si te ayuda pero te lo digo por no olvidarlo.

Otra idea que me ha venido al ver que decidíamos incluir esta app en minino y por eso he parado el lanzamiento de minino en las tablet-vexia es el hacer el customize-minino autoactualizable, solo en la vexia, (ya que lo vistes complicado para este proyecto) y así tenerlo de pruebas, ya que veo un dispositivo muy dificultoso (la tablet) para andar volviendo a instalar cuando haya otra idea como la de esta app, ¿Cómo lo ves? Un saludoo y merecido descanso

**Comment by jasvazquez** [comment]
Juego con ventaja: soy un crackER "old school" (y no es broma 😉)

**Comment by aosucas499** [comment]
Eres de los que hacía los crack .exe para los juegos? Jajaja

**Comment by jasvazquez** [comment]
Para juegos no, pero sí que desensamblaba código para saltarme protecciones en algunos programas en mis tiempos de mozalbete imberbe 😅 😉

**Comment by jasvazquez** [comment]
Ya en su momento me planteé ponerlo como opcional: sin ir más lejos no lo he usado en la vida "Hulio" pero igual (ahora que está moribundo, me da por hacerlo... cualquier cosa con tal de ir contra corriente 🤣 )

Sí que arranca servicios que pueden afectar al rendimiento (habría que hacer algunas pruebas en hardware real para valorar su impacto) pero entiendo que sería de ayuda para aquellos que lo necesiten, no tener que estar instalándolo en todos los equipos de su alumnado (otra cosa es enseñar a éstos a hacerlo 😉 )

Respecto a la actualización automática de _customize_minino_ mejor seguir la conversación en #32 👍🏻

**Comment by aosucas499** [comment]
Jajajajja vale "Hulio", mañana con más neuronas y en el finde lo pensamos todo

**Comment by jasvazquez** [comment]
Habría que eliminar la opción del servidor del menú pero de momento se deja así hasta que pruebes si te funciona 😉 

![image](https://user-images.githubusercontent.com/604744/108548905-bdf91c80-72ec-11eb-8542-9bd273f3ac3d.png)

**Comment by aosucas499** [comment]
Me pongo a ello, que estoy deseando, en cuanto tenga un ratillo entre la tablet de cargador blanco (siendo igual estéticamente que la de cargador negro y el por saco que me va a dar), corregir exámenes y tomarme hoy unas cervezas que me han abierto el pueblo jajaa

**Comment by jasvazquez** [comment]
Take it easy, bro 👍🏻

**Comment by aosucas499** [comment]
You too dude😉

**Comment by aosucas499** [comment]
> Habría que eliminar la opción del servidor del menú pero de momento se deja así hasta que pruebes si te funciona 
> 
> ![image](https://user-images.githubusercontent.com/604744/108548905-bdf91c80-72ec-11eb-8542-9bd273f3ac3d.png)


![VirtualBox_minino TDE_20_02_2021_19_27_15](https://user-images.githubusercontent.com/72696244/108605027-b2235e00-73b1-11eb-928f-65c81eac517c.png)

[Commit](https://github.com/aosucas499/minino-TDE/commit/a02f577681120f3f99815fd461edfd1aedc3cb1f)

**Comment by jasvazquez** [comment]
Me ha gustado que dejes el fichero de la opción de menú como `.save` 
Así no se nos "pierde" 🤣 👍🏻

**Comment by aosucas499** [comment]
Sabía que te gustaría 😄😄.

**Comment by aosucas499** [comment]
El fallo que te comenté que se producía cuando conectaba el cliente de minino al servidor de mi docker, también se produce con otras versiones originales de guadalinex, en este caso, con Guadalinex edu, instalado en una tablet vexia.

![IMG_20210310_233924](https://user-images.githubusercontent.com/72696244/110709831-273dc280-81fd-11eb-8af5-0bbbb123f574.jpg)

Al pulsar en descargar se produce el fallo.
![IMG_20210310_234009](https://user-images.githubusercontent.com/72696244/110709542-a2eb3f80-81fc-11eb-8885-ac093d9041f8.jpg)

Se soluciona usando el paquete ejabber de guadalinex como te comento [aquí](https://github.com/aosucas499/minino-TDE/issues/64#issuecomment-796260187) y cargando tanto el server como el cliente con sudo, por lo que habrá que modificar los lanzadores o quizás sea del ejabberd. En cuanto puedo lo modifico y probamos.

**Comment by aosucas499** [comment]
Te paso el script/función para que funcione el server en minino y el cliente sea compatible con la descarga desde el server en Guadalinex edu y docker hgr. Como sé que tu tiempo vale oro te paso los comandos para que lo pruebes rápidamente en guadalinex next que tienes instalado. Lo he alojado en el proyecto del docker para no ponerlo aún en el oficial customize hasta ver qué tal funciona.

`wget https://raw.githubusercontent.com/aosucas499/hgr-dre/main/testing/hgr-minino-aosucas499`

`chmod +x hgr-minino-aosucas499`

`./hgr-minino-aosucas499`

**Comment by profeIAP** [comment]
Tampoco es para tanto que parece que soy importante y todo 🤣 
Funciona perfectamente en Guadalinex Next 👍🏻 
Buen trabajo Andrés

**Comment by aosucas499** [comment]
Multiples cuentas de github?

**Comment by jasvazquez** [comment]
🙈 Voy a borrar el comentario (sorry): no me gusta "mezclar" perfiles

**Comment by jasvazquez** [comment]
Tampoco es para tanto que parece que soy importante y todo rofl
Funciona perfectamente en Guadalinex Next 👍🏻
Buen trabajo Andrés

**Comment by aosucas499** [comment]
[Closed](https://github.com/aosucas499/minino-TDE/commit/8c5c99b6bd54fe03fd97543d227de6ea79b43aba)
