### ISSUE TITLE
Autoactualizar customize-minino.sh

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#63]
En base a la idea propuesta en #32 y, como prueba de concepto, se opta por implementar la actualización automática de `customize-minino.sh` pues, al tener implementadas las comprobaciones de las opciones ya utilizadas por el usuario (para poder marcarlas en la lista de opciones como "instaladas")

![imagen](https://user-images.githubusercontent.com/604744/108603656-7edcd100-73a9-11eb-8598-4263cda89a09.png)

resultará algo más sencillo de llevar a cabo y nos puede abrir las puertas a la actualización global del sistema.

**Comment by aosucas499** [comment]
Hoy me he dado cuenta de un fallo. 

Si instalas un pc y abres customize-minino sin tener conexión a internet, te muestra que hay una nueva versión pero se rompe el script y no puedes volver a abrirlo aunque posteriormente tengas conexión a Internet. Por lo tanto, tienes que descargar el proyecto y volver a copiar customize-minino en /usr/bin.

Quizás la posible solución pase por anteriormente a la comprobación de versión, compruebe si hay conexión a Internet, cerrando si no existe y continuando en caso contrario. No sé si incluso este fallo podría afectar también a la automatización del update-minino.

**Comment by profeIAP** [comment]
Me alegra que hayas sido tú quien lo ha detectado 😉

Como bien intuyes, el fallo es común pues ambos comparten código.

Anoto mirarlo, es poca cosa 👍🏻

**Comment by aosucas499** [comment]
Genial ProfeIAP!!! En cuánto esté resuelto, a ver si saco tiempo para el dichoso control de presencia, es poca cosa pero el otro día no daba con la manera de poner una página web en firefox como principal desde la consola de comandos...y entonces yo creo que es cuestión de generar la iso y mandarla como definitiva

**Comment by profeIAP** [comment]
🙈🤣

**Comment by jasvazquez** [comment]
Se acabó "chimpón" (o eso espero 😅 )

![imagen](https://user-images.githubusercontent.com/604744/115150370-4d5e4a00-a068-11eb-9832-7085ad48c939.png)
