### ISSUE TITLE
Activar server de HGR-Sigala en Minino

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#64]
Tras lograr hacer funcionar el cliente de Sigala en #60 y, [habiendo desactivado temporalmente la opción del servidor](https://github.com/aosucas499/minino-TDE/issues/60#issuecomment-782728585), sería interesante seguir investigando para hacerlo operativo.

A día de hoy no se considera prioritario (de ahí que se etiquete como IDEA) puesto que:

1. Minino-TDE va enfocado a equipos de bajos recursos (donde un server aunque debería funcionar, no tiene su "entorno ideal")
2. Es totalmente compatible tanto con el educAndOS unofficial de @aosucas499 como con los Guadalinex Next/Slim actuales

**Comment by aosucas499** [comment]
![IMG_20210310_231633](https://user-images.githubusercontent.com/72696244/110708064-78988280-81fa-11eb-9c3f-7600831751e7.jpg)

He conseguido que funcione, para ello como te comenté, algunos paquetes son importantes que sean el mismo o casi misma versión. En este caso el paquete involucrado es el servidor ejabberd.

El método seguido para que funcione es previamente a tu script de instalación de hgr-sigala, cambiar los repositorios de debian jessie (minino) a debian stretch (contiene paquetes en la misma versión o casi que Guadalinex next) , instalar ejabberd v.16 en lugar de v.14 y posteriormente pasar tu script de instalación. De esta manera se consigue que arranque el server. En cuanto pueda modifico el script en customize minino, solo necesito pegarlos.

**Comment by aosucas499** [comment]
Closed [#60](https://github.com/aosucas499/minino-TDE/issues/60?_pjax=%23js-repo-pjax-container#issuecomment-797691628)

**Comment by aosucas499** [comment]
[Closed](https://github.com/aosucas499/minino-TDE/commit/8c5c99b6bd54fe03fd97543d227de6ea79b43aba)
