### ISSUE TITLE
Pasar HGR-Sigala a customize-minino.sh

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#65]
Tras implementar la tarea #60 decidimos que para [evitar arrancar servicios innecesariamente en equipos con bajos recursos](https://github.com/aosucas499/minino-TDE/issues/60#issuecomment-781626683), sería más  apropiado pasar a `customize-minino.sh` el poder elegir si se quiere contar (o no) con el cliente de HGR-Sigala

**Comment by jasvazquez** [comment]
¿ @aosucas499 cambiarías el texto descriptivo ?

![imagen](https://user-images.githubusercontent.com/604744/108606646-71c8dd80-73bb-11eb-9713-cd394e6b61f2.png)

**Comment by aosucas499** [comment]
Para nada. Creo que se llamó sigala, después hga y al final hgr. Pero todo el mundo la conoce como sigala.

**Comment by jasvazquez** [comment]
Tarea implementada tras el commit 1c38b77
