### ISSUE TITLE
Documentar el uso de Synaptic

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#66]
Han sido varios los compañeros/as que han preguntado por software que se encuentra en los repositorios.

Igual sería de interés incluir en la wiki información sobre cómo instalar programas usando Synaptic (indicando dónde se encuentra en el menú de aplicaciones) y haciendo mención a la actualización de los repositorios (no sea que no estén actualizados las listas de paquetes disponibles y no encuentren cosas que sí están)

**Comment by jasvazquez** [comment]
Básicamente debemos explicar:
1. Cómo se llega a Synaptic 
![imagen](https://user-images.githubusercontent.com/604744/108745342-3ead5800-753b-11eb-972c-2503df39490d.png)

2. La necesidad de actualizar la lista de paquetes 
![imagen](https://user-images.githubusercontent.com/604744/108745060-f4c47200-753a-11eb-9c21-61d9e62b1d4a.png)

3. Cómo se busca (p.e. Gimp que es uno de los más solicitados y que optamos por no incluirlo de serie como se aprecia en #20)
4. Marcan los paquetes a instalar y, finalmente, se aplican los cambios

**Comment by jaimecarrascogarcia** [comment]
Voy a ello, perdonad pero he tenido unos días moviditos!!!  Lo hago en una wiki

**Comment by jaimecarrascogarcia** [comment]
https://github.com/aosucas499/minino-TDE/wiki/Uso-de-Synaptics


¿Algo asi? He usado tus imágenes, alguna otra?

**Comment by jasvazquez** [comment]
Francamente bien, Jaime

Yo echo de menos alguna captura del final en el que se vea cómo marcar la paquetes y aceptar cambio

**Comment by aosucas499** [comment]
> https://github.com/aosucas499/minino-TDE/wiki/Uso-de-Synaptics
> 
> ¿Algo asi? He usado tus imágenes, alguna otra?

Eres un crack. Esperamos que vayan mejor esos días moviditos.

**Comment by jaimecarrascogarcia** [comment]
Ahi vamos Andrés un poco liado pero mejorando, muchas gracias crack. Compañero @jasvazquez si me haces una captura de la imagen que quieres que ponga la añado a la wiki, te lo agradecería si puedes, no tengo ningún dispositivo con Minino por aquí....!!!

Por cierto @aosucas499 como va la tablet de 5v?? ya hasta se me ha olvidado.... un abrazo a todos compis

**Comment by aosucas499** [comment]
Me alegro que mejora la cosa. Pues tienes en telegram el enlace para ambaa tablets, la de cargador negro como el que te pasé pero con sigala añadido y la blanca trae varios kernel, espero que la gente con toda la documentación que he puesto ayude a mejorarla, falta audio y táctil como cosa más reseñable.

**Comment by aosucas499** [comment]
Closed [updated wiki](https://github.com/aosucas499/minino-TDE/wiki/Uso-de-Synaptics)

**Comment by jasvazquez** [comment]
El paso "se marcan los paquetes a instalar" me da la sensación de dejar muchas cosas "a la imaginación" 🤔

**Comment by aosucas499** [comment]
Sírvete jajaja

**Comment by aosucas499** [comment]
Yo es que pienso que no era necesario esto, es decir, la gente ya no sabe buscar en google "tutorial uso synaptic"? Como sigamos así nos ponen un teléfono fijo y una oficina en el CAU

**Comment by jasvazquez** [comment]
Servido... 👍🏻
