### ISSUE TITLE
Recuperara panel inferior

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#67]
Javier comenta en el [grupo TDE de Telegram](https://t.me/c/1191811099/58033) que ha perdido el panel inferior y no sabe cómo recuperarlo.

Sería interesante documentar (o incluso incluir opción al menú contextual que aparece al pulsar el botón secundario sobre el escritorio) dicha posibilidad

**Comment by jasvazquez** [comment]
Poco después comenta que con CTRL+ESC logra abrir el "menú"... habrá que mirarlo

**Comment by chipygr** [comment]
No se hace con la opcion de restaurar minino?

**Comment by jasvazquez** [comment]
Ni idea compañero: no uso habitualmente Minino y hasta que no pueda sentarme en mi equipo (con la máquina virtual) no voy a poder hacer pruebas (por éso lo he etiquetado como DUDA 😅 )

Si es fácil recuperarlo, al final pasamos la tarea como DOC para dejar constancia porque seguro que alguno que otro tiene el mismo problema y no estará de más tenerlo "por escrito" 😉

**Comment by jasvazquez** [comment]
Bueno, acabo de echar un vistazo al tema y se puede recuperar relativamente fácil con la opción "Restaurar Minino" que comenta @chipygr 👍🏻 

Sólo habría que abrir la terminal (CTRL+ALT+F2) y lanzar el comando correspondiente

![minino-restore](https://user-images.githubusercontent.com/604744/109041935-e0fe4480-76cf-11eb-8b80-e0870cad3d3c.png)

Para que funcione, se hace necesario cerrar la sesión y volver a entrar

![lxde-logout](https://user-images.githubusercontent.com/604744/109042085-1145e300-76d0-11eb-92a2-16a344b86145.png)

**Comment by jasvazquez** [comment]
Doy por cerrada la tarea tras incluir [explicación en la wiki](https://github.com/aosucas499/minino-TDE/wiki/FAQs) de cómo resolver el problema.

Si vemos que a los compañer@s les cuesta seguir el "truco", nos podríamos plantear modificar el script `minino-restore-defaults` para que ejecute el `lxde-logout` pero, a día de hoy, creo que es más que suficiente ¿Se acepta la "moción"? 😉
