### ISSUE TITLE
Falla wifi Acer Aspire One

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#68]
Comentado por [Samuel Cárdenas en el grupo de Telegram](https://t.me/c/1191811099/58179)

Se pide modelo de tarjeta wifi e indica tratarse de la Qualcomm atheros AR9285

**Comment by jasvazquez** [comment]
Como dudas, me quedan saber si es un problema para detectar wifis o si la tarjeta de red está sin drivers y ni está funcionando.

En foros encuentro que el [driver asociado es el ath9k](https://wiki.debian.org/ath9k#Supported_Devices)

![imagen](https://user-images.githubusercontent.com/604744/109136700-aee4f500-7758-11eb-891b-51ea567136c7.png)

y en Minino hay alguna referencia pero no el paquete concreto 

![imagen](https://user-images.githubusercontent.com/604744/109136917-eb185580-7758-11eb-8ff8-638c0fb3197f.png)

**Comment by jasvazquez** [comment]
Ok, los drivers de _ath9k_ han sido [incluidos en el kernel](https://wireless.wiki.kernel.org/en/users/Drivers/ath9k#get_the_latest_ath9k_driver)

**Comment by jasvazquez** [comment]
Quedo pendiente de que Samuel 

1. lance un `sudo iwlist scan` (para ver si puede detectar wifis)
2. adjunte captura de pantalla

**Comment by Samcarfe** [comment]
Hola: 
He ejecutado el comando y adjunto la captura de de pantalla.
[minino.pdf](https://github.com/aosucas499/minino-TDE/files/6227232/minino.pdf)

**Comment by jasvazquez** [comment]
Gracias Samuel

Pues según se observa en la "captura", parece que sí detecta las wifis disponibles.

¿No te aparecen en el applet del escritorio? 🤔

**Comment by Samcarfe** [comment]
No, no me aparecen las redes disponibles... o algo no estoy haciendo bien

**Comment by jasvazquez** [comment]
Perdón por ser tan "pesado" Samuel... ¿no aparecen en el siguiente applet del panel inferior?

![imagen](https://user-images.githubusercontent.com/604744/113157243-046e5f00-923b-11eb-965b-b738df31545f.png)

**Comment by Samcarfe** [comment]
Hola:
Gracias por tu inestimable ayuda, pero lamentablemente, no me parece el icono de redes, solo el de redes cableadas, me dice que "el dispositivo no está gestionado"
![MININO](https://user-images.githubusercontent.com/79637829/113543870-8b2e8d80-95e7-11eb-9df8-7d0f61972c23.jpeg)

**Comment by jasvazquez** [comment]
Es raro porque como mostrabas el otro día, las wifis las detecta
Igual no usan la misma "nomenclatura" para las tarjetas de red ¿Podrías enviar captura de lanzar un `ip addr`? 🤔

**Comment by Samcarfe** [comment]
Hola José Antonio:
Encontré [la solución](https://www.wifi-libre.com/topic-25-configurar-network-manager-para-que-gestione-la-interfaz-ethernet.html) de rebote en este artículo.
Ya funciona perfectamente. 
Muchísimas gracias por tu tiempo y esfuerzo.

**Comment by jasvazquez** [comment]
Al contrario: gracias a ti Samuel.
El artículo con la solución seguro que le es de utilidad a algún que otro compañero 👍🏻
