### ISSUE TITLE
Control de presencia de Séneca en customize minino

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/minino-TDE#69]
Tras comentario de @jasvazquez en telegram y visto que mucha gente está instalando minino en PC's antiguos como dispositivos para el control de presencia de Séneca en los  coles, sería una buena idea incluir una opción instalable para incluir toda la configuración de modo opcional (A.K.A customize-minino) 

Debe incluir al menos:

1. Configuración de página principal en Firefox v.83 del [control de presencia](https://seneca.juntadeandalucia.es/controldepresencia/) de Séneca.

2. Lanzar Firefox al inicio y dado el [issue](https://github.com/aosucas499/lamentablet-vexia/issues/2) en la tablet vexia que redactó un compañero, hacer que firefox se retrase unos segundos antes de lanzarlo, ya que si se hace antes de que se establezca la hora, que con Andared en minino lo tenemos solucionado con [fix-ntp](https://github.com/aosucas499/minino-TDE/blob/main/ntp/fix-ntp), la página no carga.

Por ahora parece solucionado con el código que se muestra a continuación, aunque quizás haya que retrasar más segundos ya que actualmente está en 40 segundos y quizás el fix de hora, que tiene un sleep de 30, tarde más de 10 segundos en establecer la hora, pero no me han dado feedback y quizás tendríamos que retrasar el[ sleep](https://github.com/aosucas499/minino-TDE/commit/c7c75334a9e9b0e849778758eb8f041be60537b8) del lanzador a un minuto.

`wget https://raw.githubusercontent.com/aosucas499/minino-TDE/main/tools/Firefox-latest-sleep30`

`sudo cp Firefox-latest-sleep30 /etc/xdg/autostart/Firefox-latest-sleep30.desktop`

El código descarga un acceso directo a Firefox modificado con sleep y lo copia en la carpeta de autoboot al inicio de minino con su nombre apropiado ".desktop".

3. Incluir en la función, el código presente en customize-minino de "Inicio de sesión automático" para que no te pida usuario y contraseña al inicio del sistema.

4. Configurar las opciones de Ahorro de energía para que no se apague la pantalla, está en el menú de inicio, utilidades de minino y "apagado de pantalla". (Esta opción no sé si es necesaria).

**Comment by jasvazquez** [comment]
Actualizo etiquetas considerando 

+ que no es SOFTWARE al tener ya instalado todo lo que necesitamos pero lo que buscamos es una FUNCIONALIDAD concreta en Minino
+ IDEA pues todavía no ha sido asignado (aunque ya me haya "invitado" a hacerlo públicamente) ni va a ser acometido hasta (mínimo la próxima semana 🙈 )

**Comment by aosucas499** [comment]
😄😄😄😄 genial todo

**Comment by aosucas499** [comment]
Aquí te pongo la función del [control de presencia de Séneca](https://github.com/aosucas499/minino-TDE/blob/main/customize/controldepresencia.sh). Funciona la instalación, la comprobación y la desinstalación.  La he intentado incluir en customize-minino pero no ejecuta la llamada a la función "activarAutoLogin" que es necesaria para esta nueva función. He probado a llamarla, a simplemente colocar el código directamente del autologin en la función de presencia pero nada funciona. Creo que algunas comprobaciones de tu código hace que al final use el "activarAutoLoginUndo" aunque no sé porqué lo hace. Quizás sean las horas...

**Comment by aosucas499** [comment]
He añadido la función satisfactoriamente, aunque cabe destacar la duda de si en el futuro esta función debe activar/instalar la función 'activarautologin' automáticamente o dejarlo a opción del usuario.

e8f74e776e2924c75172cab410c99bcf04310cae

[Release 1.2.6](https://github.com/aosucas499/minino-TDE/releases/tag/1.2.6)

También queda pendiente y relacionada con esta tarea, añadir la instalación de qshutdown para que se apague el sistema automáticamente a una hora concreta.

![VirtualBox_minino TDE_29_04_2021_19_14_33](https://user-images.githubusercontent.com/72696244/116592783-acea0e80-a920-11eb-92f4-f0c17c1c270a.png)

**Comment by aosucas499** [comment]
añadido apagado automático en customize-minino en tarea #79 -  03ea6e9d63e64a8d4fda81378ef07939a7172b9b -  [release 1.2.7](https://github.com/aosucas499/minino-TDE/releases/tag/1.2.7)

![VirtualBox_minino TDE_29_04_2021_19_14_34](https://user-images.githubusercontent.com/72696244/116593674-a14b1780-a921-11eb-81ef-40998af9151a.png)

**Comment by aosucas499** [comment]
![customize-minino](https://user-images.githubusercontent.com/72696244/120541114-c253cc00-c3e9-11eb-932f-02dc697c117c.png)
añadida imagen para usar en readme

**Comment by ana585** [comment]
open windows
##- [x] #- - [ ] traductor @aosucas499 [_![image](https://user-images.githubusercontent.com/74079709/175192527-c4f1f753-fd21-40b4-9f99-724d2999b72a.jpeg)_]()[_![image](https://user-images.githubusercontent.com/74079709/175192584-7dce01d2-4664-44de-a21f-cdee977b2fb9.jpeg)_]()@🗝🛌🪟🎏🪞📪📪✉️📯📫📩🎎🏮🎐📧📭📄📉🗒📑💌🧧📯🗞🗞📅📕❤️🔓☯️✝️🆘🅰️🅱️🆎⚠️🚸❗️❔❎✅🛗🏧🌐📶⬆️↙️➡️⏬◀️🔼🔽⏪↔️🔀🔃🔄🔂🔁*️⃣#️⃣🔢9️⃣9️⃣4️⃣6️⃣7️⃣8️⃣3️⃣2️⃣1️⃣0️⃣🆓🆖🆗🆙2️⃣🆕🔠🔡🔤ℹ️🔣👁‍🗨🟠🔸🔘🔘🟤☑️🟡⚪️🔶🔲🔻🟣🔸◾️▪️🟫🔊🔈🔈◻️🟥⬜️▫️◽️🟩🔔🔊📢📣📣💭💬🔕🗯🗯♣️♦️🃏🀄️🕑🇨🇴🇧🇫🇧🇿🇧🇫🇰🇲🏴🏴‍☠️🚩🚩🇦🇶🇦🇫🏳️‍⚧️🏳️‍🌈🇩🇪🇦🇴🇦🇮🇦🇶💓🔎🔍🕧♦️♠️♣️💬💭📢🕥🕚🕕🕑🕐🕒🕓🃏🎴🕧🕦🕜🕥🇦🇷🇧🇪🇦🇹🇧🇴🇧🇭🇧🇭🇧🇷🇧🇧🇦🇺🇮🇴🇦🇶🇦🇱🇦🇮🇦🇫🇦🇴🇺🇳🇦🇩🏳️‍⚧️🇩🇪🏳️‍🌈🇦🇬🇮🇴🇩🇿🇦🇷🇦🇲🇦🇺🇦🇹🇦🇿🇧🇸🇧🇧🇧🇭🇧🇪🇧🇿🇧🇯🇧🇷🇧🇴🇧🇦🇧🇷🇧🇳🇰🇭🇧🇬🇧🇫🇧🇮🇨🇻🇰🇭🇰🇭🇨🇲🇧🇶🇶🇦🇹🇩🇨🇿🇨🇳🇨🇾🇨🇷🇻🇦🇨🇮🇰🇵🇰🇲🇰🇷🇨🇷🇨🇮🇭🇷🇨🇺🇨🇼🇩🇰🇩🇲🇪🇨🇪🇬🇸🇻🇦🇪🇪🇷🇸🇰🇸🇮🇵🇭🇺🇸🇺🇸🇫🇯🇸🇿🇪🇪🇪🇹🇵🇭🇫🇮🇫🇯🇬🇦🇫🇷🇬🇲🇬🇪🇬🇭🇬🇮🇬🇩🇬🇷🇬🇱🇬🇳🇬🇺🇬🇵🇬🇹🇬🇫🇬🇬🇬🇳🇬🇶🇬🇼🇬🇾🇭🇹🇭🇳🇭🇰🇭🇺🇮🇳🇮🇩🇮🇶🇮🇷🇮🇪🇰🇾🇨🇽🇳🇫🇮🇸🇦🇽🇰🇾🇮🇨🇨🇨🇨🇰🇫🇴🇬🇸🇫🇰🇲🇵🇲🇭🇵🇳🇸🇧🇹🇨🇻🇬🇻🇮🇮🇱🇮🇹🇯🇲🇯🇵🎌🇯🇪🇯🇴🇰🇿🇯🇲🇰🇪🇰🇮🇱🇻🇰🇬🇽🇰🇰🇼🇱🇦🇱🇸🇱🇻🇱🇧🇱🇷🇱🇾🇱🇮🇲🇾🇱🇹🇱🇺🇲🇴🇲🇰🇲🇬🇲🇾🇲🇼🇲🇻🇲🇱🇲🇹🇲🇦🇲🇶🇲🇺🇲🇨🇾🇹🇲🇽🇲🇸🇲🇩🇲🇨🇲🇳🇲🇪🇲🇸🇲🇿🇲🇩🇲🇺🇳🇪🇲🇲🇳🇦🇳🇷🇳🇵🇳🇮🇲🇸🇲🇿🇳🇮🇳🇨🇳🇴🇳🇺🇳🇬🇳🇪🇳🇿🇴🇲🇳🇱🇵🇰🇵🇼🇵🇦🇵🇬🇵🇾🇵🇪🇵🇫🏴󠁧󠁢󠁥󠁮󠁧󠁿🇬🇧🇵🇹🏴󠁧󠁢󠁳󠁣󠁴󠁿🇵🇱🏴󠁧󠁢󠁳󠁣󠁴󠁿🏴󠁧󠁢󠁷󠁬󠁳󠁿🇨🇫🇨🇬🇨🇩🇩🇴🇪🇭🇷🇪🇼🇸🇷🇼🇻🇨🇷🇴🇷🇼🇦🇸🇷🇴🇧🇱🇷🇺🇰🇳🇸🇲🇵🇲🇻🇨🇸🇭🇱🇨🇸🇹🇸🇳🇷🇸🇸🇨🇸🇱🇸🇬🇸🇽🇸🇾🇸🇴🇱🇰🇿🇦🇸🇩🇸🇸🇸🇪🇨🇭🇸🇷🇹🇭🇹🇼🇹🇿🇹🇯🇹🇫🇵🇸🇹🇱🇹🇬🇹🇷🇹🇰🇹🇴🇹🇹🇹🇳🇹🇲🇹🇷🇹🇻🇺🇦🇺🇬🇪🇺🇼🇫🇺🇾🇺🇿🇻🇺🇻🇪🇻🇳🇼🇫🇾🇪🇩🇯🇿🇲🇿🇼💡🔦🔌🔦🕯🪔🔋📡⏳⌛️🕰🎛🧭⏱⏲⏰🎚🎙📻📺📠📽🎞📞☎️📟🎥📹📸📷📼🗜💽💾💿📀🕹🖲🖱🖨⌚️📱📲💻⌨️🌌🌉🌁🎆🌇🌆🏙🌃🎇🌠🌄🌅🏞⛩🛤🛣🗾🎑🕋🛕🕍🕌⛪️🏪🏣🏚⛺️🛖🏗🏤🏫🕌🏠🏭🏥🏩🕍🏡🏢🏦💒🏘🏬🏛🕋🏛⛺️🛖🏠🏡🏘🏕🗻🏔⛰🌋⛲️⛱🏖🏝🏜🎠🎢🎡🏟🏯🗺🗿🗽🗼🏰⛽️🚧🚦🚥🚏🪝⚓️🚢⛴🛳🚁🛶⛵️🚤🛥🛸🚀🛰💺🚊🚉✈️🛫🛬🚇🚆🚂🚈🚅🚃🚋🚞🚝🚄🚟🚠🚡🚖🚘🏍🛺🏍🚨🚔🚍🛵🚲🛴🦼🦽🛻🚚🚛🚜🦯🚐🚒🚑🚓🏎🚎🚌🚙🚕🚗🎰🧩🎲♟🎯🎳🎮🎻🪕🎸🪗🎺🎼🎹🥁🪘🎷🎧🎤🎬🎨🩰🎪🤹🏻‍♀️🤹🏻🤹🏻‍♂️🎭🎟🎫🎗🏵🏆🥇🥈🥉🏅🎷🎤🎨🎬🩰🎼🥁🥁🎷🚴🏼‍♂️🚴🏼🚴🏼‍♀️🚵🏼‍♂️🚵🏼🚣🏻‍♂️🧗🏻‍♀️🧗🏻🧗🏻‍♂️🚵🏻‍♀️🚣🏻🤽🏻‍♂️🚣🏻‍♀️🤽🏻🤽🏻‍♀️🏊‍♂️🏊🏊‍♀️🏄‍♂️🏄🏄🏼‍♀️🧘🏼‍♂️🧘🏼🧘🏼‍♀️🏇🏼🤾🏻🤾🏻‍♂️🏌🏻‍♀️🤾🏻‍♂️🏌🏻🏌🏻‍♂️🤾🏻‍♀️🤺⛹🏻‍♂️⛹🏻⛹🏻‍♀️🤸‍♂️🤸🤸‍♀️🤼‍♂️🤼‍♂️⛹🏻🤼‍♂️⛹🏻‍♀️🤼🤼‍♀️🏋🏻‍♂️🏋🏻🏋🏻‍♀️🪂⛸🥌🎿⛷🛷🛼🛹🎽🥋🥊🤿🎣🏹🪁🥍🏏🪃🥅⛳️🏑🏒🏸🏓🪀🎾🏐🏉🥏🎱🥎⚾️🏈🏀⚽️🥡🥢🧂🥣🍽🍴🥄🧊🍾🧉🍹🍸🥃🍶🍺🍻🥂🍷🧋🥤🧃🍵☕️🫖🍼🥛🍯🥜🍫🍿🍩🍪🌰🍬🍭🍮🎂🍰🧁🥧🍨🍦🍧🍨🍥🥠🥮🍢🍡🍘🍚🍙🍤🦪🥟🍱🍣🍛🍲🥘🫕🥫🍝🍜🥗🫔🌯🌮🧆🥙🥪🫓🍕🍟🍗🍖🦴🌭🍔🥩🥓🧇🥞🧈🍳🥚🧀🥨🥖🥔🍠🥐🥯🍞🧅🧄🫒🥕🌽🫑🌶🥒🥬🥦🥥🥝🍅🍆🥑🍍🥭🍑🍒🍈🫐🍓🍇🍉🍌🍏🍎🍐🍊🌫🌊☂️💦💧💨🌬⛄️⛈🌩🌨❄️😀😅😊😌😃😂😇😍😄🤣🙂🥰😁🥲🙃😘😆☺️😉😗😙😜😎😒🙁😩😠😍😍😇😚🤪😞🥸☹️🥺😞😡🙂🥰🤨😋🤩😣😔😢🤬🙃🥲😘😛🥳🧐😟😖😭🥳🤯😳😤😫😕😏🤓😝😗😉😉☺️😆😳😨😱😶‍🌫️🥶🥵😡🤬🤯😠😰😥😓🤗🤔😓🤭🤥🤗😶😐🤔😑😧🤫😬🤥🙄😶😯😐😐😦😧🤤😮😪😲😮‍💨🙄😯🥱😵😦😴😵‍💫🤤🤐😪🥴😮‍💨🤢😵🤮🤧😷🤒🤕😸😈💩👾👿👻🤖👹💀🎃👺☠️😽🤡👽😸🤠🤑😹😿👾😻🤖😾😻😽😼👐🏿👐🏿🤲🏿🧲⛓🪚🔧💎⚖️🕰🔌⌛️💡⏳🔦📡🕯🔋🪔🧯💶🛢💷💸🪙💵💰💴💳💎💶💷⚖️🪙🪜💰🧰💳🪛🔧🪚🔨🔩⚒⚙️🛠🪤⛏🧱🪛🧰⚖️⚖️💎⛓🔩⚙️🪤🧱⛏🛠⚒🔨🔧⛓🪓🧲🔪🔫🗡💣⚔️🧨🛡🧱🪤🪓🚬⛓🧲🔪⚰️🔫🗡🪦💣⚔️⚱️🧨🏺🏺🚬⚰️🪦⚱️🏺🔮🔭📿💉🧿🩸🕳💈🩹🔬💊💉⚗️🩹⚱️⚗️💈🩺🩹🦠🧬🩸💉💊🧫🧺🧪🧻🌡🚽🧹🚰🪠🚿🛁🧽🛀🏿🧼🪥🪒🚰🚿🧽🪣🧴🛎🔑🪒🪥🧼🗝🛌🧽🪣🧴🛎🔑🗝🚪🪑🛋🛏🛌🧸🪆🖼🪞🪟🛍🛒🎁🎈🎏🎀🪄🛒🪅🎊🎉🏮🏮🎎🎐🧧✉️📩📨📧📥📤📦🏷🪧📪📫📬📭📮📯📜📃📄📑🧾📊📈📉🗒📑🗓📆📅🗑📇🗃🗳🗄📰📁📂🗂📰📰🛅🚹🚺🚼⚧🛄🛃🛂🈂️🈳🏧🚾♿️🅿️🛗💤🌀Ⓜ️💠🌐🚻🔣🆖🆓🔣🆓🚹🚮ℹ️🆗0️⃣🎦🔤🆙📶🔡🆒2️⃣🈁🔠🆕3️⃣🔅🔱🔆⚜️〽️🔰⚠️♻️🚸✅🈯️❇️💹✳️♻️🔰🛷🐶🦊🐯🐸🐒🐣🦇🐝🐞🐱🐻🦁🐵🐔🐥🐺🪱🐜🪱🦟🐢🐡🐋🐆🐘🦒🐄🦙🐓🦮🐓🐓🦢🐁🦨🐁🐉🌳☘️🍃🪨🥀🌞🥀🌞🌕🌒🌍🌝🌝🌖🌓🌏🌛🌗🌔🪐🌼🌘🌜🌙💫🌚🌑🌎⭐️🌻🌼🌸🥀🥀🌻💐🌾🪨🐚🍄💐🪨🍁🍄🎋🎍🎍☘️☘️🌿🪵🪵🌳☘️🌿🌵🌴🌳🌲🎄🐲🐉🐾🦔🐿🐀🐁🦥🦦🦫🦨🦝🕊🦩🦢🐇🦜🦚🦃🐓🦜🪶🐈‍⬛🐈🐕‍🦺🦮🐩🐕🦌🐐🦙🐑🐏🐎🐄🐩🦌🦙🐂🐃🦘🦒🦒🦬🐫🐪🦏🐘🐘🐫🐪🦏🦛🐘🦣🦧🦓🐆🐅🐊🦭🦈🐋🐳🐬🐟🐡🐡🦀🦞🦑🐙🐙🦕🦖🦎🐍🐢🦂🕸🦗🦟🦟🪳🪲🪰🐞🐌🦋🐛🐝🐌🐛🪱🐝🦄🐴🐗🐺🦇🦄🦉🦅🦆🦆🐥🐣🐤🐦🐧🐔🐒🙊🙉🐵🐵🐸🐷🐷🐮🦁🐯🐯🐽🐨🐻‍❄️🐼🐻🦊🐽🐷🦁🐯🐯🐰🐰🐱🐱🐶🐹🐭🐱🐶🐨🐻‍❄️🐼🐻🦊🐽🐷🐮🦁🐯🐑🐏🐖🐄🐄🐚🍄🍁🍂🍃⭐️🌎💫🪐🌙🪐🌔🌏🌓🌍🌍🌒🌒🌓🌍🌟✨⚡️⚡️☄️💥💥⭐️💫🪐🌏🌑🌤☀️🌈🌈🔥🔥💥☄️⚡️🌟🔥⛅️⛈🌥🌩🌪☁️🌨🌦❄️🌧☃️💦💧💨🌬⛄️🌫🌊☂️☔️🍳🥚🧀🧈🥖🧀🥔🥐🥯🍞🧅🧄🫒🥕🌽🌽🍔🌭🌭🥓🦴🦴🥞🍟🍟🫔🥙🫓🫑🥑🍍🫐🍓🍓🌶🥭🍆🍇🍑🍇🍉🥝🍉🍌🍈🥦🍏🍎🍐🍐🍊🍋🍘🍜🍚🍣🍛🥫🌮🧆🌮🌯🥗🥘🍲🦪🍧🎂🥮🥠🥠🍙🍢🧁🍮🍭🍬🍬🥧🍮🍰🍿🍪🍫🥛🌰🥜🥛🫖🍯🥜🥛🍼🫖🍿🍫🍩🌰🌰🍭🎂🍰☕️🧃🥤🚋🚟🚡🚘👽🙌🏼👊🏻👊🏻👎🏼👍🤝👏🏼✊🏽🤛🏽🤜🏽🤞🏽✌🏽🤟🏾🤘🏾👌🏾🤌🏾🤏🏾👈🏿👉🏿👆🏿👇🏿☝🏿✋🏿🤚🏿🖐🏿🖖🏿👋🏿🤙🏿💪🏿🦾🖕🏿✍🏿🙏🏻👄🦶🏿🦵🏿🦿💄💋👄🦷👅👂🏿🦻🏿👃🏿👣👁👀🫀🫁🧠🗣👤👥🫂👶🏿👧🏿🧒🏿👦🏿👩🏿🧑🏿👨🏿👩🏿‍🦱🧑🏿‍🦱👨🏿‍🦱👩🏿‍🦰🧑🏿‍🦰👩🏿‍🦰👨🏿‍🦰👱🏿‍♀️👱🏿👱🏿‍♂️👩🏿‍🦳🧑🏿‍🦳👩🏿‍🦲🧑🏿‍🦲👨🏿‍🦲🧔🏿‍♀️🧔🏿🧔🏿‍♂️👵🏿🧓🏿👴🏿👲🏿👳🏿‍♀️👳🏿👳🏿‍♂️🧕🏿👮🏿‍♀️👮🏿👷🏿‍♀️👮🏿‍♂️👷🏿👷🏿‍♂️💂🏿‍♀️💂🏿💂🏿‍♂️🕵🏿‍♀️🕵🏿🕵🏿‍♂️👩🏿‍⚕️🧑🏿‍⚕️👨🏿‍⚕️👩🏿‍🌾🧑🏿‍🌾👨🏿‍🌾👩🏿‍🍳🧑🏿‍🍳👨🏿‍🍳👩🏿‍🎓🧑🏿‍🎓👨🏿‍🎓👩🏿‍🎤🧑🏿‍🎤👩🏿‍🏫👨🏿‍🎤🧑🏿‍🏫👨🏿‍🏫👩🏿‍🏭👩🏿‍💼🧑🏿‍🏭👨🏿‍🏭👩🏿‍💻🧑🏿‍💻👩🏿‍🔧👨🏿‍💼🧑🏿‍💼👨🏿‍💻🧑🏿‍🔧👨🏿‍🔧👩🏿‍🔬🧑🏿‍🔬👨🏿‍🔬👩🏿‍🎨🧑🏿‍🎨👨🏿‍🎨👩🏿‍🚒🧑🏿‍🚒👩🏿‍🚀👨🏿‍✈️🧑🏿‍✈️👩🏿‍✈️👨🏿‍🚒🧑🏿‍🚀👨🏿‍🚀👩🏿‍⚖️🧑🏿‍⚖️👨🏿‍⚖️🤵🏿🤵🏿‍♀️👰🏿‍♂️👰🏿👰🏿‍♀️🤵🏿‍♂️👸🏿🤴🏿🥷🏿🦸🏿‍♀️🦸🏿🦸🏿‍♂️🦹🏿‍♀️🦹🏿🦹🏿‍♂️🤶🏿🧑🏿‍🎄🎅🏿🧙🏿🧙🏿🧙🏿‍♀️🧛🏿‍♀️🧝🏿‍♂️🧝🏿🧝🏿‍♀️🧙🏿‍♂️🧛🏿🧛🏿‍♂️🧟‍♀️🧟🧟‍♂️🧞‍♀️🧞🧞‍♂️🧜🏿‍♀️🧜🏿🧞‍♂️🧜🏿‍♂️🧚🏿‍♀️🧚🏿🧚🏿‍♂️👨🏾‍🍼👼🏿🤰🏿👩🏿‍🍼🤱🏿🧑🏿‍🍼👨🏾‍🍼🙇🏿‍♀️🙇🏿🙇🏿‍♂️💁🏿‍♀️💁🏿💁🏿‍♂️🙅🏿‍♀️🙅🏿🙅🏿‍♂️🙆🏿‍♀️🙆🏿🙋🏿‍♀️🙋🏿‍♀️🙆🏿‍♂️🙋🏿🙋🏿‍♂️🧏🏿‍♀️🧏🏿‍♂️🧏🏿🇼🇫🇼🇫🇼🇫🇼🇫🇼🇫🇼🇫🤦🏿🙎🏿‍♀️🙎🏿‍♀️🤷🏾‍♂️🤷🏾🤷🏾‍♀️🤦🏾‍♂️🙎🏿🙎🏿‍♂️🙍🏿‍♀️🙍🏿🙍🏿‍♂️💆🏿💆🏿‍♀️💇🏿‍♂️💇🏿💇🏿‍♀️💆🏿‍♂️🧖🏿‍♀️🧖🏿🧖🏿‍♂️💅🏿🤳🏿💃🏿🕺🏿👯‍♀️👯👯‍♂️👩🏿‍🦽👩🏿‍🦽🧑🏿‍🦽👨🏿‍🦽👩🏿‍🦼🧑🏿‍🦼👨🏿‍🦼🚶🏿‍♀️🚶🏿🚶🏿‍♂️👩🏿‍🦯🧑🏿‍🦯👨🏿‍🦯🧎🏿‍♀️🏃🏿‍♂️🏃🏿🏃🏿‍♀️🧎🏿‍♂️🧎🏿🧍🏿‍♀️🧍🏿🧍🏿‍♂️👫👭🏾👫👭🏾🧍🏿🧍🏿‍♂️👬🏾👩🏾‍❤️‍👨🏾👩🏾‍❤️‍👩🏾🧑🏾‍❤️‍🧑🏾👨🏾‍❤️‍👨🏾👩🏾‍❤️‍💋‍👨🏾💏👨‍👩‍👦‍👦👨🏾‍❤️‍💋‍👨🏾👨‍👩‍👧👩‍👩‍👧👨‍👨‍👧👩‍👧👨‍👩‍👧‍👦👩‍👩‍👧‍👦👨‍👨‍👧‍👦👩‍👧‍👦👨‍👩‍👦‍👦👩‍👩‍👦‍👦👨‍👨‍👦‍👦👩‍👦‍👦👨‍👩‍👧‍👧👩‍👩‍👧‍👧👨‍👨‍👧‍👧👨‍👧‍👧👩‍👩‍👦👨‍👩‍👦👨‍👨‍👦👩‍👦👨‍👦👨‍👨‍👦🪢👨‍👧‍👧👨‍👦‍👦👨‍👧‍👦👨‍👧👩‍👧👩‍👧‍👦👩‍👧‍👧👩‍👧‍👧👨‍👦👨🏾‍❤️‍💋‍👨🏾💏👩‍❤️‍💋‍👩🥼🧥🪡🧵🦺🩳👚👔👕👗👖👙🩲🩱👠🥿🩴🥻👘👡🧦👢🧤👞🧣👟🎩🥾🧢🥿🩴🥻👒💍🧦🧤🎓👝🧣⛑👛🎩🪖👜🧢👑💼🎒👓🕶🥽💼👜👛👝💍🌂❤️💜❤️‍🔥💓🧡🖤💗💗🖤❤️‍🩹💛🤍❣️💖💚🤎💕💘💙💔💞💝💟☸️☦️♊️♏️🆔☮️✡️🛐♋️♐️⚛️✝️🔯⛎♌️♑️🉑☪️🕎♈️♍️♒️☢️💝🕉♉️☯️♎️♓️☣️♉️📴🈺📳🈷️🆔⚛️🉑☢️☣️🈚️🆚🈶✴️🈸🈸💮🈚️🆚🉐🆑🈹🉐㊙️🈲🅾️㊗️🅰️🆘🈴🅱️❌🈵🆎⭕️🛑💢🚱⛔️♨️🔞📛🚷📵🚫🚯🚭💯🚳❗️🚱❕🔞❓📵❔🚭🚭‼️⁉️❗️🔅🔱🔆⚜️〽️🔰⚠️♻️🚸✅❎✳️❇️🈯️🈯️✅♻️⁉️❔📵🔞🈳🏧🛅🚻🔣🆖🆓9️⃣9️⃣4️⃣⏏️🚮🔤ℹ️🆗0️⃣5️⃣🔟🎦🔤🆙1️⃣6️⃣⏸📶🆒2️⃣#️⃣⏏️⏺➡️⏫↘️▶️⏭⏬⬅️↙️↙️⏯⏸⏮◀️⬆️↖️⏯⏩🔼↕️↕️⬇️⏹⏪🔽↗️↔️↘️↪️🔁↙️↩️🔂➡️⬅️⬆️⬇️↗️↖️⤴️🔄🔄↕️⤵️🔃↔️🔀🔀↗️☑️🔘🔴🟠🟡🟢🔵🟣⚫️⚪️🟤🔺🔻🔸🔹🔶🔷🔳🔲▪️▫️◾️◽️◼️🔳◼️🔲◻️🟦🟥⬛️🟧⬛️🟨⬜️🟩🟫◼️🔔🔊🔉🔈🔈🔕📣💬💭🃏🎴🀄️🕑🕑♥️💬🔔💬🔔[_![image](https://user-images.githubusercontent.com/74079709/175195622-9e781f3b-01d9-424b-9d67-8683752b581a.jpeg)_]()**_[![image](https://user-images.githubusercontent.com/74079709/175195650-5bcb3aab-8d75-4413-8649-6286f77640e0.jpeg)]()_**
