### ISSUE TITLE
Enlazar proyecto y recursos en punto de encuentro TDE

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#7]
Desde el grupo Telegram [se sugiere](https://t.me/c/1191811099/50223) la idoneidad de publicitar el proyecto y los recursos elaborados por este proyecto en la moodle del Punto de Encuentro TDE como medio de darle publicidad y generar nuevas ideas y sinergias

**Comment by jasvazquez** [comment]
Agradecería correcciones "de estilo" @aosucas499 😅 

![image](https://user-images.githubusercontent.com/604744/101513685-c0e6a100-397c-11eb-893a-992ec64d9221.png)

**Comment by aosucas499** [comment]
Yo creo que tiene mucho estilo y buena redacción. Por poner algo les enlazaría con el github, aunque en otro comentario, quiero generar pronto una iso y así se comenta con las mejoras.

**Comment by jasvazquez** [comment]
Quizás demasiado serio para un hilo de un foro, de ahí que preguntase tu opinión al respecto Andrés 😅 

He puesto enlace a github (oculto justo antes del emoji del biceps) pero ya habrá tiempo (cuando publiques la nueva _release_ de Minino-TDE) de hacer hincapié y, si se deja, de cambiar el texto para recoger los enlaces "esenciales" del proyecto (ISO, GitHub, ...) 👍🏻

**Comment by aosucas499** [comment]
Perfect crack.

**Comment by jasvazquez** [comment]
Pues entonces la damos por terminada 😉👍

**Comment by aosucas499** [comment]
> estilo

¿Te puedes creer que he entrado en el aulavirtual y en el tde y soy incapaz de encontrar tu hilo?

**Comment by jasvazquez** [comment]
No, Andrés, no me extraña que no la veas: la he pasado y estoy esperando que le den el visto bueno 🤷 
Cuando esté te aviso 👍

**Comment by aosucas499** [comment]
¿Tienen filtro de post?🙄

**Comment by jasvazquez** [comment]
Realmente no, pero va a aparecer en una categoría nueva que todavía no ha sido publicada en el punto de encuentro TDE 😉

**Comment by aosucas499** [comment]
Wow!😆

**Comment by jasvazquez** [comment]
Creo que ya deberías poder acceder a ella 😉
