### ISSUE TITLE
Instalación dual Minino y Windows

### ISSUE THREAD

**Issue by tecnojose** [aosucas499/minino-TDE#70]

**Comment by tecnojose** [comment]
Buenas, quisiera instalar en un Pc Minino y Windows. 
Lo que he hecho ha sido lo siguiente:
- Instalo Windows.
-  Hago particiones.
-  Instalo Minino en la partición que había creado antes.
Al arrancar el PC solo arranca en Minino, no me deja seleccionar Windows y Minino. La partición de Windows está aún, ya que abro el terminal y ejecuto sudo update-grub2 y pone Encontrado Windows 10 (loader) en dev/sda1

![image](https://user-images.githubusercontent.com/79006169/111886391-750cb480-89cd-11eb-95aa-34475889ec19.png)

**Comment by jasvazquez** [comment]
Hola Jose ¿has probado a pulsar ESC en el arranque de Minino?

![imagen](https://user-images.githubusercontent.com/604744/111905782-b17ff500-8a4d-11eb-8de1-3f72f9768b5f.png)

Te lo comento porque observo que, por defecto, no muestra GRUB y arranca con el sistema por defecto (Minino)

Si tras intentar acceder a Grub (pulsando ESC en el arranque) te resulta imposible, agradecería que nos porporcionases copia del fichero `/bot/grub/grub.cfg` para intentar averiguar qué puede estar ocurriendo

Gracias por avisar 👍🏻

**Comment by aosucas499** [comment]
Aquí principalmente el problema es que estamos mezclando un sistema que arranca en modo UEFI (windows 10) y una instalación de minino que no tiene soporte para uefi, por lo que la instalación de minino ha machacado el arranque de windows pero no puede encontrarlo porque windows 10 no arranca en modo legacy (si fuese windows 7 creo recordar es diferente).

Aquí la única manera que se me ocurre y que conozco la uśé en las tablets, que solo tienen arranque UEFI. Consiste en arrancar con un sistema live de 64bits, hacer chroot en la partición de minino, una vez instalado. Instalar paquetes como grub-efi-amd64 y entonces hacer un "update-grub2". También habŕía que generar una partición uefi antes de instalar minino, etc...

Hay que recordar el sistema minino no está hecho para ordenadores modernos y potentes. Por lo pronto no tenemos ni interesa tener particiones y arranque UEFI porque es un sistema 32bits.
