### ISSUE TITLE
Incluir update-minino en listado sudoers

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#75]
Tras "pelear" en la tarea #32 con los permisos y tener que estar introduciendo contraseñas para poder actualizar minino cada vez que aparezca una nueva _release_, nos planteamos la posibilidad de incluir el script `/usr/bin/update-minino` dentro del fichero _sudoers_ para evitar al usuario tener que hacerlo.

**Comment by aosucas499** [comment]
Archivo añadir sudoers: [commit 3609990](https://github.com/aosucas499/minino-TDE/commit/360999011b6fad78eeddfcf80aeae72ea403dd66)

function sudoersUpdate: [commit c239ba](https://github.com/aosucas499/minino-TDE/commit/c239ba897d7f314d0a721c7e27ef53581fcb5214)

añadido sudo a updateMinino.desktop: [commit 71b008c](https://github.com/aosucas499/minino-TDE/commit/71b008caadbd3844a3440f03e8bd6ec1af8a77b2)

**Comment by aosucas499** [comment]
He añadido /usr/bin/update-minino a sudoers creando una función para que lo añada en update-minino. He modificado también tu código que creaba el archivo update-minino.desktop de autoinicio, simplemente añadiendo sudo, ya que sin él seguiría pidiendo contraseña en cada inicio. Con esto resolvemos el problema.

Por ahora en cada inicio siempre ejecuta todo el update-minino, supongo que tendré que crear una release para que compruebe que es la actual y no ejecute en cada inicio hasta que sea diferente.

**Comment by aosucas499** [comment]
Creo que con esto tenemos solucionado el problema. 

Cada destacar que update-minino se ejecuta en cada inicio. No lo veo un gran problema sino fuese porque sale la ventana de xterm siempre.

Una fotografía de la primera vez que detecta una release nueva:

![VirtualBox_minino TDE_27_04_2021_21_37_22](https://user-images.githubusercontent.com/72696244/116304468-e563de00-a7a2-11eb-808a-68654eae34f5.png)

Y esta otra de cada reinicio aunque no haya release nueva:

![VirtualBox_minino TDE_27_04_2021_21_38_55](https://user-images.githubusercontent.com/72696244/116304541-f7458100-a7a2-11eb-9add-055f03c255e0.png)

**Comment by aosucas499** [comment]
Solucionado el problema anterior con la release [1.2.4](https://github.com/aosucas499/minino-TDE/releases/tag/1.2.4) modificando otra vez el .desktop de autoinicio y eliminando xterm, que supongo pusiste como una manera de visualizar su ejecución. Muy inteligente!

Hay que destacar que la función [autostartupdateminino](https://github.com/aosucas499/minino-TDE/blob/49ec7da4a49104bc56ebc188869fcc352666be6c/update-minino.sh#L95) no detecta el ambio en el archivo .desktop, por lo que lo he borrado manualmente para que se actualizara con update-minino e incluyese los cambios de borrar el comando xterm -e y el añadido de sudo a update-minino.

**Comment by jasvazquez** [comment]
Parece que te estorba _xterm_ pero no me gusta la idea de que el sistema esté haciendo cosas por detrás y no sepamos qué ocurre ni (de momento) tengamos forma de notificar al usuario el resultado del proceso.

Había optado por usar _xterm_ precisamente para poder interactuar con el script y, aunque esté en la lista de _sudoers_ (buen trabajo) creo que debería seguir visible mientras no tengamos una alternativa 🤔

Abro tarea temporalmente hasta resolver la duda y/o tomar una decisión 👍

**Comment by aosucas499** [comment]
Update-minino está agregado a sudoers con éxito. Se ejecuta en cada inicio y no pide clave. Si te gusta por ahora que lo tengamos un tiempo mostrando la terminal lo vuelvo añadir. 
5929b096bb8af8cdebe520ceef3a41f29367ee74

**Comment by jasvazquez** [comment]
Preferiría (mientras no tengamos otra forma) dejarlo así: sale "barato" y nos ahorramos "sustos" 😉

**Comment by aosucas499** [comment]
Cierro tras comprobar que funciona perfectamente en release [1.2.5](https://github.com/aosucas499/minino-TDE/releases/tag/1.2.5). Se ejecuta en cada inicio sin pedir contraseña y se ve gráficamente con xterm.

**Comment by jasvazquez** [comment]
Buen trabajo, compi 👍🏻
