### ISSUE TITLE
reinstalar SO Vexia

### ISSUE THREAD

**Issue by MMONTAVEZ** [aosucas499/minino-TDE#76]
Hola, trabajo en un centro educativo de primaria de Sevilla, alfonso de Orleans. Varias vexia me dan problemas y quiero reinstalar el SO. He seguido las instrucciones que aparecen en el Github, pero nada. Me aparece la pantalla en negro y el número 92 en pequeño.
Gracias.

**Comment by MMONTAVEZ** [comment]
TE mando una captura del correo con José, quien me dijo que contactara con usted. Lo de lo grupos Telegram no lo he visto. Soy también el coordinador TDE en mi colegio
![correo_aosucas](https://user-images.githubusercontent.com/83212471/116060067-cde10400-a681-11eb-89e5-7c9bae0806e0.png)

**Comment by jasvazquez** [comment]
Hola compi, desgraciadamente (y aunque me líe hasta yo 😅 ) este no es el repositorio del proyecto de las Vexia.
Mejor dirígete a @aosucas499 a través d[el siguiente enlace](https://github.com/aosucas499/lamentablet-vexia)
Suerte y un saludo
