### ISSUE TITLE
customize-minino suplantado por update-minino

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/minino-TDE#78]
Tras la creación de la release [1.2.3](https://github.com/aosucas499/minino-TDE/releases/tag/1.2.3)  y [1.2.4](https://github.com/aosucas499/minino-TDE/releases/tag/1.2.4) si ejecutamos customize-minino detecta una nueva versión. Si actualizamos update-minino suplanta el código de customize-minino. Si cancelamos todo marcha bien. Todo esto partiendo de la versión original "fix-centros"

No sé si he hecho algo hoy con las últimas releases pero no toqué el código de [customize-minino](https://github.com/aosucas499/minino-TDE/commits/main/customize/customize-minino.sh). 

¿Es posible que update-minino comparta nombre de archivo al descargar (new.sh) con customize minino? https://github.com/aosucas499/minino-TDE/blob/49ec7da4a49104bc56ebc188869fcc352666be6c/customize/customize-minino.sh#L513

Imagen de customize-minino al lanzarlo
![VirtualBox_minino TDE_27_04_2021_22_51_01](https://user-images.githubusercontent.com/72696244/116313457-109ffa80-a7ae-11eb-8b45-c2fe3e51b41d.png)

¿O será que no he vuelto bien al anterior commit [aquí](https://github.com/aosucas499/minino-TDE/commit/4e1595a958328bd8f53d1881f61b9a06588fb1e6#diff-627031a172ff6bde550e5f8fac54716d04c1c884d3343c793b96fbb37e557b36) de update minino?

Siento si la he liado pero las horas ya no me dan para más. Échale un vistazo cuando tengas tiempo.

**Comment by aosucas499** [comment]
Por último observo que si parto de una máquina virtual con el proyecto actualizado a fecha de 22 abril, compruebo que customize-minino está actualizada y se lanza bien, posteriormente descargo la release de hoy 1.2.4 y reinicio, customize-minino no detecta problemas, supongo que porque no detecta cambio de versión.

**Comment by jasvazquez** [comment]
Sí que comparten (como que está copiado y pegado el código entre los dos scripts)
Pensé que lo borraba al terminar pero optaré por generar nombres únicos y evitar problemas, descuida

**Comment by aosucas499** [comment]
Igualmente voy a probar a mirar tu código y darle un nombre diferente a cada uno y probar, si se soluciona lo subo y sino te lo dejo. A ver si esta semana que tengo más tiempo libre puedo quitarte algo de trabajo en esto y que mejores.

**Comment by aosucas499** [comment]
Creo que con esto vale temporalmente, si posteriormente quieres cambiar nombre o algo usted mismo. La metida de pata haría que algunos pc's que tengo en el aula TIC con autoupdate de customize se me rompiesen y tenía que buscarle una solución temporal.

b630a0ba7bc73ab1a931a69cd046c166034ec722
3cdaab4fce3e39c156b09f254e2e5b9918a19b7d
71b008caadbd3844a3440f03e8bd6ec1af8a77b2

Tan solo he cambiado las entradas new.sh por new2.sh para que no coincidad con update-minino. He necesitado 3 commits porque tengo hoy la cabeza para arrancármela jajaj

**Comment by aosucas499** [comment]
Problema solucionado en la [release 1.2.5](https://github.com/aosucas499/minino-TDE/tree/1.2.5).

Para resumir, tenemos update-minino que se ejecuta en cada inicio #32 sin pedir clave #75, mostrando salida en xterm (5929b096bb8af8cdebe520ceef3a41f29367ee74) y customize-minino que vuelve a funcionar #78. Todo probado desde la versión "fix-centros".

![VirtualBox_minino TDE_28_04_2021_20_52_17](https://user-images.githubusercontent.com/72696244/116458345-d5acce00-a864-11eb-95f3-6192bf85a615.png)

Me quedo muy tranquilo así...
