### ISSUE TITLE
apagado automático 

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/minino-TDE#79]
Era necesario añadir a customize-minino la opción de instalar una aplicación que apague el equipo automáticamente a una hora determinada y definida por las necesidades de cada usuario.

Viene muy bien para el control de presencia de Séneca y que el dispositivo se apague automáticamente al acabar la jornada laboral o en cualquier equipo usado en el centro para que igualmente no necesite la intervención del usuario por el cambio de profesorado en una misma aula y que no se quede encendido.

La instalación instala la aplicación qshutdown y muestra un cuadro de diálogo para que el usuario introduzca la hora a la que quiere que se apague el dispositivo modificando el archivo de configuración. También debe de iniciarse en cada inicio y que se oculte en la barra de tareas.

**Comment by aosucas499** [comment]
añadido apagado automático en customize-minino   03ea6e9d63e64a8d4fda81378ef07939a7172b9b -  [release 1.2.7](https://github.com/aosucas499/minino-TDE/releases/tag/1.2.7)

![VirtualBox_minino TDE_29_04_2021_19_14_32](https://user-images.githubusercontent.com/72696244/116592110-e8d0a400-a91f-11eb-8b82-54e46d0e5a25.png)

![VirtualBox_minino TDE_29_04_2021_19_14_58](https://user-images.githubusercontent.com/72696244/116592128-ec642b00-a91f-11eb-9079-9b562bcd48ed.png)

**Comment by jasvazquez** [comment]
¿No estamos ante un caso similar a Gimp?
O, lo que es lo mismo... ¿no serviría con explicar cómo se instala o qué  programas hay para hacerlo? 🤔 
Prefiero no cargar _customize-minino_ con cosas que podría hacer cualquiera fácilemente 😅

**Comment by aosucas499** [comment]
Pues creo que viene muy bien, es algo que instalo en todos los PC's del centro y que aunque mucha gente instala no sabe como modificar para la hora (experiencias de cosas que me pidieron en educaandos plus)

**Comment by aosucas499** [comment]
> ¿No estamos ante un caso similar a Gimp?
> O, lo que es lo mismo... ¿no serviría con explicar cómo se instala o qué programas hay para hacerlo? 
> Prefiero no cargar _customize-minino_ con cosas que podría hacer cualquiera fácilemente

Otra cosa es si lo ves bien que incluyamos el control de presencia y el apagado automático en la misma función.

**Comment by aosucas499** [comment]
¿Lo ponemos en una? Control de presencia que incluya el apagado automático...de todas maneras es algo que solicitan y tiene sentido, un dispositivo que va a estar usándose para fichar lo suyo es que se apague solo.

**Comment by profeIAP** [comment]
Lo hagamos como lo hagamos, el problema persistirá.

Habría que buscar algún "truqui" lo suficientemente "transparente" e inocuo como para saber cuándo desinstalar el programa sin fastidiar a nadie

**Comment by aosucas499** [comment]
No entiendo tu punto de punto de vista, imagino que te refieres a que desinstalar el control de presencia implicaría desinstalar el apagado automático. No se me ocurre una situación en la que en un dispositivo se necesite desinstalar el apagado automático y no el control de presencia o viceversa. 

En todo caso se me ocurre que la desinstalación del control de presencia preguntara al usuario si quiere deinstalar el apagado automático o no...

**Comment by jasvazquez** [comment]
No soy de molestar "innecesariamente" al usuario: cuanto menos se pregunte, más contento estará 😉 

Estoy pensando en los amigos que usan Minino para montar un hilo musical en el centro o aquellos coles que no tengan servidor de contenidos y quisieran que los equipos, al terminar la jornada se apagasen automáticamente sin tener que revisarlos.

En mi centro, hay **demasiados/as** que pasan de apagar equipos, de lámparas de proyectores y de luces cuando hay solazo... 🙈

**Comment by aosucas499** [comment]
Entiendo entonces que dejamos la función tal cual está añadida en customize-minino

**Comment by jasvazquez** [comment]
No sé, déjame pensarlo: en _customize-minino_ (salvo que me digas lo contrario) y pudiendo instalarse como cualquier otro programa, no termino de verlo necesario (no me gustaría llenarlo de opciones innecesariamente)
