### ISSUE TITLE
Contactar con autores de Minino

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#8]
Sería interesante [contactar con los creadores del proyecto](https://minino.galpon.org/es/%C2%BFqui%C3%A9nes-somos) e intercambiar experiencias para ver cómo podríamos mejorar/actualizar la versión actual de su distribución

![image](https://user-images.githubusercontent.com/604744/101200950-46114380-3667-11eb-90f8-92b80dedb721.png)

**Comment by aosucas499** [comment]
![minino@galpon org](https://user-images.githubusercontent.com/72696244/101205406-dfdbef00-366d-11eb-8dcd-a908d3ad7ca3.png) (Imagen modificada borrando nombre e email personal de la respuesta)

Contacté ayer por la tarde. He intercambiado algún email con ellos hoy. 
minino@galpon.org
Cualquier duda se puede contactar en ese correo haciendo referencia a nuestro proyecto.
