### ISSUE TITLE
Generar ISO autoactualizable

### ISSUE THREAD

**Issue by aosucas499** [aosucas499/minino-TDE#80]
Pues eso, basándonos en la última release, habiendo probado la increíble función de autoupdate, creo que podemos generar la que posiblemente sea la última ISO. ¿Cómo lo ves?

**Comment by profeIAP** [comment]
Justo y... necesario 😅👍🏻

**Comment by aosucas499** [comment]
Cerrando las tareas #86 y #85. ¿Cómo vemos lanzar la ISO?

[ISO link](https://bit.ly/3bjdD8R)

**Comment by chipygr** [comment]
Descargando y testando

**Comment by aosucas499** [comment]
Funcional
