### ISSUE TITLE
Falla activación modo incógnito

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#81]
Haciendo pruebas con minino-fixCentros, detecto que no existe en el escritorio del usuario el icono de la última versión de Firefox

![imagen](https://user-images.githubusercontent.com/604744/117577919-2eddf280-b0ec-11eb-9394-bbefcc7c799d.png)

Resulta curioso cuando [`update-minino` se encarga de crearlo](https://github.com/aosucas499/minino-TDE/blob/6e61bdbef0c9e0d6b1a70ffe16c7b30ce6b49c76/update-minino.sh#L330)

Es posible que la comprobación (método `xxxCheck(..)`) de un falso positivo y no proceda a instalar la versión de Firefox

**Comment by aosucas499** [comment]
Mi versón de fix-centros si tiene el icono de la última versión. El problema es que en ese momento teníamos la instalación en la carpeta /home/usuario/firefox. Después propusimos incluirla como aplicación del sistema y eso hacía update-minino, borrarlo de la carpeta de usuario, el icono, etc... y lo vuelve hacer el proceso pero como app del sistema.

[enlace al código de la función](https://github.com/aosucas499/minino-TDE/blob/6e61bdbef0c9e0d6b1a70ffe16c7b30ce6b49c76/update-minino.sh#L310)

**Comment by jasvazquez** [comment]
Qué liá tengo con las ISOs de Minino, @aosucas499 🙈 

En su día descargué la última ISO que tenemos en el README.md al entender que era la "fixCentros" y los iconos que tiene en el escritorio son los que puedes ver en la siguiente captura

![imagen](https://user-images.githubusercontent.com/604744/117579298-867f5c80-b0f2-11eb-97f9-ae5ccabc7851.png)

**NOTA:** conste que lo que estás viendo es posterior a lanzar `update-minino` sobre la fixCentros recién instalada, ¿Qué se me está escapando? 🤔

**Comment by aosucas499** [comment]
jajajaj mira la foto. La versión fix-centros es la primera que teníamos. Es de noviembre del 2020.

![Captura de pantalla de 2021-05-09 18-25-26](https://user-images.githubusercontent.com/72696244/117579683-4d47ec00-b0f4-11eb-9b13-219de3a1c367.png)

Esta foto es de la fix-centros recién cargada en máquina virtual, el instalador.

![VirtualBox_test_09_05_2021_18_28_58](https://user-images.githubusercontent.com/72696244/117579730-79636d00-b0f4-11eb-8401-ff33028973ad.png)

Como puedes observar tiene el icono, pero corresponde a firefox-latest instalado en la carpeta usuario y no en el sistema.

La que tenemos en el enlace del proyecto es porterior, es de enero de 2021.

Si quieres podemos partir de esta de enero para el script.

**Comment by jasvazquez** [comment]
Creo recordar que hablamos en su día (porque yo pregunté que por qué no partíamos de la GALPon original) que preferías la de noviembre porque habías hecho una serie de cambios que ya ni recordabas (si lo hicieses me preocuparía mi agostada memoria 🤣 )

Yo creo que lo suyo sería usar la más "original" posible y así tener todo completamente automatizado y gestionado por el script ¿no?

**Comment by aosucas499** [comment]
Si sí, yo era por si te daba problemas y preferías la de enero. Seguimos partiendo como siempre de fix-centros. De hecho, siempre la genero así, arranco fix-centros, aplico update-minino y genero iso.

**Comment by jasvazquez** [comment]
Creo que ya sé qué está pasando... ¿técnicamente debería quedar así?

![imagen](https://user-images.githubusercontent.com/604744/117580708-8a62ad00-b0f9-11eb-89ed-f2f52ea8f2d2.png)

**TRADUCCIÓN:** que desaparezca el _firefox-83_ y que en su lugar aparezca el _firefox-latest_

**Comment by aosucas499** [comment]
Seguramente firefox83 es el icono de firefox instalado en la carpeta usuario y -latest una vez instalado en /usr/lib

**Comment by jasvazquez** [comment]
Aunque sospecho que el problema que me estaba dando era por usar `update-minino.sh` con _sudo_ desde el código clonado por _git_, opto por usar $USER a la hora de copiar el icono y descargo los ficheros en `/tmp` mediante el commit 145a5da para que no exista la posibilidad de dejar basura en `/usr/bin`
