### ISSUE TITLE
Permitir "pre Releases"

### ISSUE THREAD

**Issue by jasvazquez** [aosucas499/minino-TDE#83]
Sería interesante poder marcar algunas _releases_ como versiones previas

![imagen](https://user-images.githubusercontent.com/604744/117579660-373a2b80-b0f4-11eb-99c5-b500d4246c88.png)

de modo que podamos hacer desarrollos/pruebas que no le salten a los usuarios finales.

Hasta ahora vengo usando _forks_ y _pull requests_ pero sería bastante más cómodo hacerlo todo en el repositorio oficial

**Comment by aosucas499** [comment]
Por mi genial. Estas versiones no se autoactualizarían, ¿correcto?

**Comment by jasvazquez** [comment]
No termino de tenerlo claro pues podría ser necesario para probar según qué cosas.
Igual la IDEA es una tontería, es lo que mi amigo Teo llama una "idea cúbica": tengo que darle patadas hasta ponerla redonda.
La he dejado aquí anotada para que no se me olvide en las brumas de mi memoria 😅

**Comment by aosucas499** [comment]
Genial entonces. Mi duda es si tienes que decidirlo antes de generar nuestra última ISO "rolling release".

**Comment by jasvazquez** [comment]
Espero que no... 

El código que pueda añadir para implementarlo (si finalmente se implementa esta idea) se actualizaría automáticamente junto a `update-minino` en la próxima release que nos animemos a publicar.

¿Alguna "gracia/utilidad" debía tener la versión _rolling_ de Minino? 😉

**Comment by aosucas499** [comment]
Genial entonces!

**Comment by jasvazquez** [comment]
Como IDEA se me ocurre que sólo se actualice si existe determinado fichero en el `$HOME` o "perdido" en el sistema.
De este modo los "usuarios finales" no se verían "molestados" por las actualizaciones parciales y los desarrolladores tendríamos la opción de activar (dejando el fichero) o desactivar (borrándolo/renombrándolo) dicha posibilidad.

Se me ha pasado incluirlo como opción en `customize-minino` pero, para evitar disgustos y no cargarlo de opciones, quizás mejor ni mencionarlo 😉

**Comment by aosucas499** [comment]
Me parece genial ese "easter egg". Con lo de customize te refieres a que customize-minino también se actualizara a una prerelease si encontrara el huevo de pascua no?

**Comment by aosucas499** [comment]
Pienso que si lo hacemos en uno (update-minino), lo hacemos en otro no (customize)?

**Comment by jasvazquez** [comment]
Veo que ando "espeso" 🤣 😅 

En realidad me refería a incluir en `customize-minino` una opción tipo 

+ "Activar modo kamikaze e instalar cualquier actualización de desarrollo que pueda romper mi sistema" 
+ "Activar modo inestable de desarrollador sabiendo que me romperá Minino_TDE a la primera de cambio"

De modo que si se activa, metería el "easter egg" en el sistema y cualquier _release_ que se publique te la instala (aunque se cargue algo)

**Comment by aosucas499** [comment]
Ah vale, te entiendo ahora, yo también ando espeso leyendo los lunes...sin modos "huevo de pascua" en customize-minino mejor. Ese huevo de pascua lo metemos de forma manual cuando estemos de desarrollo y lo borramos al generar releases oficiales

**Comment by jasvazquez** [comment]
Yo no termino de verlo en `customize-minino`: sólo nos va a dar dolores de cabeza y quejas de los que lo activen
Yo prefiero hacer un `touch` con un nombre de fichero en algún sitio y listo

**Comment by aosucas499** [comment]
Si sí, con touch, meter la opción "developer" en customize no!!!
