### ISSUE TITLE
No autoactualiza con wifi Andared - versión pruebas rolling

### ISSUE THREAD

**Issue by jaimecarrascogarcia** [aosucas499/minino-TDE#85]
Adjunto capturas, del problema que hay a continuación: 

![photo_2021-05-19_09-14-59](https://user-images.githubusercontent.com/77231941/119034164-5b2c2580-b9ae-11eb-90d5-c685603a681e.jpg)
![photo_2021-05-20_20-58-27](https://user-images.githubusercontent.com/77231941/119034205-68491480-b9ae-11eb-81b6-708ecd20c735.jpg)

¿A qué puede ser debido?

**Comment by profeIAP** [comment]
Hola Jaime, ya me comentó @aosucas499 algo del problema pero no sé si llegó a hacer unas pruebas que comentó.

Tengo entendido que ibas a probar en otro equipo ¿te falla en ambos?

Teniendo en cuenta cómo va en mi centro Andared ¿podrías probar en casa con ese equipo? 🤔

**Comment by aosucas499** [comment]
Llegué a probar, en virtualbox iba bien. También me comentó el problema el compañero "Joaquín Cabrera". Primero me comentó el mismo problema que @jaimecarrascogarcia . Posteriormente se llevó el PC a casa y todo le iba genial con cable. Lo raro es que me dijo que también le iba bien con wifi en casa, cosa rara. A no ser que algo en la conexión TCP de Andared esté restringida y afecte al [código de comprobación de Internet](https://github.com/aosucas499/minino-TDE/blob/145a5da6244d98bad7ef20709a470e2ad98e6cfb/update-minino.sh#L540).

**Comment by aosucas499** [comment]
Como prueba para @jaimecarrascogarcia , si  los fallos fueron conectando el pc al wifi del centro, podríamos probar a cambiar el código de comprobación de Internet. Pasos:

1. Abrir terminal con el equipo en el centro conectado a Andared y escribir:
  `sudo pluma /usr/bin/customize-minino`

2. Se abrirá el archivo en el editor de texto gráfico y buscamos la variable que contiene el código:

`function isConnectionAvailable {`
`(echo -n >/dev/tcp/8.8.8.8/53) >/dev/null 2>&1 && echo "True" || echo "False"`
`}`

3. La dejamos así:

`function isConnectionAvailable {`
`echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1 && echo "True" || echo "False"`
`}`

4. Guarda el archivo con el editor de textos.

5. Ejecuta customize-minino desde el escritorio y cuando te pregunte si quieres actualizar a la nueva versión dile que "NO".

Como prueba podría valer.

**Comment by profeIAP** [comment]
Interesante alternativa (de más alto nivel en el protocolo TCP/IP) a la función que comprueba la conexión @aosucas499 👍🏻

**Comment by aosucas499** [comment]
Me alegro que te guste, busqué por internet alguna comprobación que usara algún método para puertos que seguro que no estaban capados en Andared.

**Comment by aosucas499** [comment]
@jaimecarrascogarcia me comentó en Telegram que la prueba le funcionó en el portátil conectado a Internet por wifi en el centro. También me comentó que otro compañero que la probó, "Oscar", no necesitaba este fix incluso en el centro, por lo que suponemos que algunos servidores en los centros tienen unos puertos capados y otros no en la conexión Wifi. 

Descartamos que sea un problema del código de comprobación de Internet sobre WiFi, es solo un problema de comprobación en algunos centros cuando conectas el sistema por Wifi.

Lanzo [nueva Release](https://github.com/aosucas499/minino-TDE/releases/tag/1.3.2) y genero una nueva ISO-Rolling de prueba para que los compañeros la prueben.

**Comment by chipygr** [comment]
Efectivamente, me comentó Jaime la situación y probé la version Rolling en el centro en dos Toshibas, uno verde y uno azul. En ambos podia trabajar con el customize sin problemas, así que entendimos que el problema deberia venir de la red del centro, no de parche en si.

**Comment by aosucas499** [comment]
El compañero Joaquín Cabrera me comenta por Telegram:

> Instalación sin problemas funciona bien el inicio automatico, control de presencia y apagado programado. Esto es lo que he probado hoy

**Comment by jaimecarrascogarcia** [comment]
Bravo equipo, ya lo teneis!!!!

**Comment by aosucas499** [comment]
Cuando @jaimecarrascogarcia lo pruebe en los próximos días en el cole con Andared y nos dé su opinión de increíble betatesters,  y probemos a actualizar en equipos con la anterior versión (yo mismo lo haré en mis chuck norris del cole) #86 , publicamos la ISO y la info. #80

**Comment by aosucas499** [comment]
Comprobado que funciona por @jaimecarrascogarcia y "Joaquín Cabrera"
