### ISSUE TITLE
Añadir aplicación para indicar temperatura de la CPU

### ISSUE THREAD

**Issue by jaimecarrascogarcia** [aosucas499/minino-TDE#87]
Se me ha planteado, algunos bloqueos de sistema, y creo que son por sobrecalentamiento.... en algunos dispositivos entre ellos algunos Acer aspire one d270 y toshiba nb500, ¿se podría añadir alguna aplicación que indique la temperatura?

Muchas gracias!!!

**Comment by aosucas499** [comment]
Comprueba como va cambiando la temperatura de la CPU en una terminal con:

`watch sensors`

La idea es buena como applet.

**Comment by aosucas499** [comment]
En la barra de tareas trae iconos para controlar gráficamente el porcentaje de carga de la CPU (azul) y de RAM (en rojo), para que vigiles si algo de eso sube y hace que se "freezeen" esos dispositivos.

**Comment by jaimecarrascogarcia** [comment]
Correcto compi, pero no indica la temperatura aproximada la que está el dispositivo.....no se si sería clave saberlo...

**Comment by aosucas499** [comment]
Minino trae ya el applet. Se añade pulsando con el botón derecho en la barra por la derecha y "añadir o quitar elementos". En el apartado "miniaplicaciones del panel" selecciona y añade "monitor de temperatura". Te saldrá un número en la barra indicando la temperatura. Abre un vídeo de youtube y verás como sube.

**Comment by aosucas499** [comment]
Si quieres estresar la CPU para que suba y no te vale con youtube. 

1. instala este programa:
`sudo apt-get install stress`

2. En la terminal ejecuta:
`sudo stress -c 'nº cpus del dispositivo' --io 4 --vm 2 --vm-bytes 128M`

**Comment by jaimecarrascogarcia** [comment]
Estupendo!!!! voy a probar, en cuando tengas un hueco, como hemos hablado a mi no me sale la opcion de control de temperatura, por si "puedes añadirla por defecto en la barra de tareas"........:)

**Comment by profeIAP** [comment]
Aunque útil, yo no sería partidario de cargar más la barra.

Inicialmente pensé en ponerlo en el `customize-minino` pero quizás mejor a la documentación (wiki). Si no hay muchas ganas/tiempo de hacerlo, con enlazar a esta tarea sería más que suficiente 🤔

**Comment by aosucas499** [comment]
Como se observó en su día, ya trae el control de temperatura. Solo que el applet detecta loa drivers o no del dispositivo. Por lo tanto aparece la opción dependiendo del dispositivo.
