### ISSUE TITLE
Jessie has been moved to archive.deb-multimedia.org (23/3/2021)

### ISSUE THREAD

**Issue by rbenit68** [aosucas499/minino-TDE#88]
Saludos,

Según https://deb-multimedia.org, es necesario actualizar en /etc/apt/sources.list.d/multimedia.list la linea

deb http://www.deb-multimedia.org ...

por

deb http://archive.deb-multimedia.org ...

para evitar los errores de apt update.

Gracias por vuestro trabajo, estaba usando Bodhi Linux 4.5/5.0.0 (Ubuntu) pero prefiero Debian.

**Comment by aosucas499** [comment]
Muchas gracias. Lo apunto para el próximo cambio en el sistema y lo añado en el autoupdate.

**Comment by aosucas499** [comment]
Disculpa la tardanza, solucionado. Se actualizar al reiniciar, tras confirmación del usuario.

https://github.com/aosucas499/minino-TDE/commit/1586505dc4ef4c2b14c5b128b309c2dfb50ffbfe

https://github.com/aosucas499/minino-TDE/releases/tag/1.3.6
