### ISSUE TITLE
¿Qué tal va esta distribución con los Toshiba NB500 y NB200?

### ISSUE THREAD

**Issue by Wendower** [aosucas499/minino-TDE#89]
Lo dicho ¿qué tal funciona con estos modelos?

**Comment by aosucas499** [comment]
Buenas compañero, la sección isuues es para pedir nuevas funciones, comentar fallos. Para preguntar por cómo va en un pc coméntalo en el grupo de telegram. En ambos va genial.

**Comment by Wendower** [comment]
¿Cómo se llama ese grupo de Telegram? No sabía ni que existía.

**Comment by aosucas499** [comment]
Perdón compañero no leí bien que escribías desde fuera de Andalucía. Este es el grupo de coordinadores tic de Andalucía. https://t.me/coordinacionTicAndalucia

Esos modelos son de los primeros que adaptamos con minino tde, pues tenemos muchos en los coles.
